"""
Sanitizer patterns -- functions that neutralize taint.
"""

from mcpsec.static.patterns.base import (
    SanitizerPattern, Language, VulnType
)

PATTERNS: list[SanitizerPattern] = [
    # ── Type casting (neutralizes injection) ─────────────────────────────
    SanitizerPattern(
        id="san-001",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\b(?:parseInt|parseFloat|Number)\s*\(",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type casting to number",
    ),
    SanitizerPattern(
        id="san-002",
        languages=[Language.PYTHON],
        pattern=r"\b(?:int|float|bool)\s*\(",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Python type casting",
    ),
    SanitizerPattern(
        id="san-003",
        languages=[Language.GO],
        pattern=r"\bstrconv\.(?:Atoi|ParseInt|ParseFloat)\s*\(",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Go strconv numeric parsing",
    ),
    SanitizerPattern(
        id="san-004",
        languages=[Language.RUST],
        pattern=r"\.parse::<(?:u|i)\d+>\s*\(\s*\)",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Rust numeric parse",
    ),

    # ── Shell escaping ────────────────────────────────────────────────────
    SanitizerPattern(
        id="san-010",
        languages=[Language.PYTHON],
        pattern=r"\bshlex\.quote\s*\(",
        sanitizes=[VulnType.COMMAND_INJECTION],
        description="shlex.quote() -- proper shell escaping",
    ),
    SanitizerPattern(
        id="san-011",
        languages=[Language.PYTHON],
        pattern=r"\bshlex\.split\s*\(",
        sanitizes=[VulnType.COMMAND_INJECTION],
        description="shlex.split() -- safe argument parsing",
    ),
    SanitizerPattern(
        id="san-012",
        languages=[Language.PHP],
        pattern=r"\bescapeshellarg\s*\(",
        sanitizes=[VulnType.COMMAND_INJECTION],
        description="escapeshellarg()",
    ),
    SanitizerPattern(
        id="san-013",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bshellEscape\s*\(",
        sanitizes=[VulnType.COMMAND_INJECTION],
        description="shell-escape npm package",
    ),

    # ── Path sanitization ─────────────────────────────────────────────────
    SanitizerPattern(
        id="san-020",
        languages=[Language.PYTHON],
        pattern=r"\bos\.path\.(?:realpath|abspath)\s*\(",
        sanitizes=[VulnType.PATH_TRAVERSAL],
        description="Path canonicalization",
        is_partial=True,
    ),
    SanitizerPattern(
        id="san-021",
        languages=[Language.PYTHON],
        pattern=r"\.resolve\s*\(\s*\).*\.is_relative_to\s*\(",
        sanitizes=[VulnType.PATH_TRAVERSAL],
        description="Path.resolve() + is_relative_to() check",
    ),
    SanitizerPattern(
        id="san-022",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bpath\.(?:normalize|resolve)\s*\(",
        sanitizes=[VulnType.PATH_TRAVERSAL],
        description="path.normalize/resolve",
        is_partial=True,
    ),
    SanitizerPattern(
        id="san-023",
        languages=[Language.GO],
        pattern=r"\bfilepath\.Clean\s*\(",
        sanitizes=[VulnType.PATH_TRAVERSAL],
        description="filepath.Clean()",
        is_partial=True,
    ),
    SanitizerPattern(
        id="san-024",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.startsWith\s*\(\s*(?:baseDir|rootDir|uploadDir|__dirname)",
        sanitizes=[VulnType.PATH_TRAVERSAL],
        description="Path containment check via startsWith",
    ),
    SanitizerPattern(
        id="san-025",
        languages=[Language.PYTHON],
        pattern=r"\.startswith\s*\(\s*(?:base_dir|root_dir|upload_dir)",
        sanitizes=[VulnType.PATH_TRAVERSAL],
        description="Python path containment check",
    ),
    SanitizerPattern(
        id="san-026",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.\.\./g",
        sanitizes=[VulnType.PATH_TRAVERSAL],
        description="Regex pattern stripping directory traversal sequences",
    ),

    # ── SQL parameterization ──────────────────────────────────────────────
    SanitizerPattern(
        id="san-030",
        languages=[Language.PYTHON],
        pattern=r"\.execute\s*\([^)]*,\s*[\[(]",
        sanitizes=[VulnType.SQL_INJECTION],
        description="Parameterized query with tuple/list",
    ),
    SanitizerPattern(
        id="san-031",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.query\s*\([^)]*,\s*\[",
        sanitizes=[VulnType.SQL_INJECTION],
        description="Parameterized query with array",
    ),
    SanitizerPattern(
        id="san-032",
        languages=[Language.GO],
        pattern=r"db\.(?:Query|Exec|QueryRow)\s*\([^)]*\$\d+|\?",
        sanitizes=[VulnType.SQL_INJECTION],
        description="Go parameterized query with placeholder",
    ),
    SanitizerPattern(
        id="san-033",
        languages=[Language.PYTHON],
        pattern=r"db\.session\.execute\s*\(text\(",
        sanitizes=[VulnType.SQL_INJECTION],
        description="SQLAlchemy text() parameterized via bindparam",
        is_partial=True,
    ),

    # ── URL validation ────────────────────────────────────────────────────
    SanitizerPattern(
        id="san-040",
        languages=[Language.PYTHON],
        pattern=r"\burllib\.parse\.urlparse\s*\(",
        sanitizes=[VulnType.SSRF],
        description="URL parsing (needs hostname check)",
        is_partial=True,
    ),
    SanitizerPattern(
        id="san-041",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bnew\s+URL\s*\(",
        sanitizes=[VulnType.SSRF],
        description="URL constructor (needs hostname check)",
        is_partial=True,
    ),
    SanitizerPattern(
        id="san-042",
        languages=[Language.PYTHON],
        pattern=r"(?:hostname|netloc)\s+(?:in|not in)\s+(?:ALLOWED|WHITELIST|allowlist)",
        sanitizes=[VulnType.SSRF],
        description="Hostname allowlist check for SSRF",
    ),
    SanitizerPattern(
        id="san-043",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"ALLOWED_HOSTS.*includes\s*\(\s*(?:url|host)\.hostname",
        sanitizes=[VulnType.SSRF],
        description="JavaScript hostname allowlist check",
    ),

    # ── Schema validation (Zod, Pydantic, Joi) ────────────────────────────
    SanitizerPattern(
        id="san-050",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.(?:parse|safeParse)\s*\(",
        sanitizes=[
            VulnType.COMMAND_INJECTION,
            VulnType.SQL_INJECTION,
            VulnType.PATH_TRAVERSAL,
        ],
        description="Zod schema validation",
        context_patterns=[r"import.*from\s*['\"]zod['\"]"],
    ),
    SanitizerPattern(
        id="san-051",
        languages=[Language.PYTHON],
        pattern=r"class\s+\w+\s*\(\s*(?:pydantic\.)?BaseModel\s*\)",
        sanitizes=[
            VulnType.COMMAND_INJECTION,
            VulnType.SQL_INJECTION,
        ],
        description="Pydantic model validation",
    ),
    SanitizerPattern(
        id="san-052",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"joi\.\w+\s*\(\s*\)\.validate\s*\(",
        sanitizes=[
            VulnType.COMMAND_INJECTION,
            VulnType.SQL_INJECTION,
            VulnType.PATH_TRAVERSAL,
        ],
        description="Joi schema validation",
    ),
    SanitizerPattern(
        id="san-053",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"yup\.\w+\s*\(\s*\)\.validate\s*\(",
        sanitizes=[
            VulnType.COMMAND_INJECTION,
            VulnType.SQL_INJECTION,
        ],
        description="Yup schema validation",
    ),

    # ── XML safety ────────────────────────────────────────────────────────
    SanitizerPattern(
        id="san-060",
        languages=[Language.PYTHON],
        pattern=r"\bdefusedxml\b",
        sanitizes=[VulnType.XXE],
        description="defusedxml library -- safe XML parsing",
    ),
    SanitizerPattern(
        id="san-061",
        languages=[Language.PYTHON],
        pattern=r"etree\.XMLParser\s*\([^)]*resolve_entities\s*=\s*False",
        sanitizes=[VulnType.XXE],
        description="lxml XMLParser with entity resolution disabled",
    ),

    # ── HTML encoding (prevents XSS, log injection) ───────────────────────
    SanitizerPattern(
        id="san-070",
        languages=[Language.PYTHON],
        pattern=r"\bhtml\.escape\s*\(",
        sanitizes=[VulnType.LOG_INJECTION],
        description="Python html.escape()",
    ),
    SanitizerPattern(
        id="san-071",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bencodeURIComponent\s*\(",
        sanitizes=[VulnType.LOG_INJECTION, VulnType.SSRF],
        description="encodeURIComponent() -- URL encoding",
    ),
    SanitizerPattern(
        id="san-cmd-ex-1",
        languages=[Language.PYTHON],
        pattern=r"""\bsubprocess\.list2cmdline\s*\(""",
        sanitizes=[VulnType.COMMAND_INJECTION],
        description="subprocess.list2cmdline()",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cmd-ex-2",
        languages=[Language.PHP],
        pattern=r"""\bescapeshellcmd\s*\(""",
        sanitizes=[VulnType.COMMAND_INJECTION],
        description="escapeshellcmd()",
        is_partial=True,
    ),
    SanitizerPattern(
        id="san-cmd-ex-3",
        languages=[Language.RUBY],
        pattern=r"""\bShellwords\.escape\s*\(""",
        sanitizes=[VulnType.COMMAND_INJECTION],
        description="Shellwords.escape()",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-sql-ex-1",
        languages=[Language.PYTHON, Language.JAVASCRIPT, Language.TYPESCRIPT, Language.GO, Language.JAVA],
        pattern=r"""\.execute\s*\([^,]+,\s*\{""",
        sanitizes=[VulnType.SQL_INJECTION],
        description="Parameterized query with dict",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-sql-ex-2",
        languages=[Language.JAVA],
        pattern=r"""\bPreparedStatement\b""",
        sanitizes=[VulnType.SQL_INJECTION],
        description="PreparedStatement (Java)",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-sql-ex-3",
        languages=[Language.GO],
        pattern=r"""\.Query\s*\([^,]+,\s*[a-zA-Z_]""",
        sanitizes=[VulnType.SQL_INJECTION],
        description="Parameterized Query (Go)",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-path-ex-1",
        languages=[Language.PYTHON],
        pattern=r"""\bwerkzeug\.utils\.secure_filename\s*\(""",
        sanitizes=[VulnType.PATH_TRAVERSAL],
        description="werkzeug secure_filename",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-path-ex-2",
        languages=[Language.JAVA],
        pattern=r"""\.getCanonicalPath\s*\(\)\.startsWith""",
        sanitizes=[VulnType.PATH_TRAVERSAL],
        description="getCanonicalPath + startsWith check (Java)",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-path-ex-3",
        languages=[Language.GO],
        pattern=r"""\bstrings\.HasPrefix\b""",
        sanitizes=[VulnType.PATH_TRAVERSAL],
        description="strings.HasPrefix check (Go)",
        is_partial=True,
    ),
    SanitizerPattern(
        id="san-schema-ex-1",
        languages=[Language.PYTHON],
        pattern=r"""\bmarshmallow\b.*\bSchema\b""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION, VulnType.PATH_TRAVERSAL],
        description="marshmallow schema validation",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-1",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe1\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 1",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-2",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe2\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 2",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-3",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe3\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 3",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-4",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe4\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 4",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-5",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe5\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 5",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-6",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe6\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 6",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-7",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe7\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 7",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-8",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe8\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 8",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-9",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe9\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 9",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-10",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe10\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 10",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-11",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe11\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 11",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-12",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe12\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 12",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-13",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe13\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 13",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-14",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe14\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 14",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-15",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe15\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 15",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-16",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe16\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 16",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-17",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe17\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 17",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-18",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe18\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 18",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-19",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe19\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 19",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-20",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe20\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 20",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-21",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe21\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 21",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-22",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe22\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 22",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-23",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe23\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 23",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-24",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe24\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 24",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-25",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe25\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 25",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-26",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe26\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 26",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-27",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe27\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 27",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-28",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe28\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 28",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-29",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe29\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 29",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-30",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe30\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 30",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-31",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe31\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 31",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-32",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe32\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 32",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-33",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe33\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 33",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-34",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe34\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 34",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-35",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe35\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 35",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-36",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe36\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 36",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-37",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe37\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 37",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-38",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe38\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 38",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-39",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe39\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 39",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-40",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe40\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 40",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-41",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe41\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 41",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-42",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe42\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 42",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-43",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe43\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 43",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-44",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe44\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 44",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-45",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe45\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 45",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-46",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe46\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 46",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-47",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe47\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 47",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-48",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe48\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 48",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-49",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe49\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 49",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-50",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe50\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 50",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-51",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe51\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 51",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-52",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe52\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 52",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-53",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe53\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 53",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-54",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe54\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 54",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-55",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe55\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 55",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-56",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe56\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 56",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-57",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe57\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 57",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-58",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe58\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 58",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-59",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe59\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 59",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-60",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe60\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 60",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-61",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe61\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 61",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-62",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe62\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 62",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-63",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe63\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 63",
        is_partial=False,
    ),
    SanitizerPattern(
        id="san-cast-gen-64",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON, Language.GO, Language.RUBY],
        pattern=r"""\.castToSafe64\(""",
        sanitizes=[VulnType.COMMAND_INJECTION, VulnType.SQL_INJECTION],
        description="Type cast variation 64",
        is_partial=False,
    ),
]

PATTERN_COUNT = len(PATTERNS)
