"""
Additional sink patterns -- LDAP injection, log injection, header injection,
ReDoS, file inclusion, memory safety, and miscellaneous web vulns.
Additional language coverage for existing vuln types.
"""

from mcpsec.static.patterns.base import (
    SinkPattern, Language, VulnType, Severity, Confidence
)

PATTERNS: list[SinkPattern] = []

# ==============================================================================
# LDAP INJECTION
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-ldap-001",
        vuln_type=VulnType.LDAP_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"client\.search\s*\([^,]+,\s*`[^`]*\$\{",
        function_name="ldap.search(`${filter}`)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="LDAP search with template literal filter",
        cwe="CWE-90",
        remediation="Escape special LDAP characters: \\*()\\\\\\x00",
    ),
    SinkPattern(
        id="js-ldap-002",
        vuln_type=VulnType.LDAP_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"ldap.*filter.*\$\{",
        function_name="ldap filter with interpolation",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="LDAP filter with user input interpolation",
        cwe="CWE-90",
    ),
    SinkPattern(
        id="js-ldap-003",
        vuln_type=VulnType.LDAP_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"ldapjs.*client\.search\s*\(",
        function_name="ldapjs.client.search()",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="ldapjs search -- check filter construction",
        cwe="CWE-90",
    ),
    SinkPattern(
        id="py-ldap-001",
        vuln_type=VulnType.LDAP_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"ldap\.search_s\s*\(\s*[^,]+,\s*[^,]+,\s*f['\"]",
        function_name="ldap.search_s(filter=f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Python ldap search with f-string filter",
        cwe="CWE-90",
    ),
    SinkPattern(
        id="py-ldap-002",
        vuln_type=VulnType.LDAP_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"ldap3.*Connection.*search\s*\([^)]*f['\"]",
        function_name="ldap3 Connection.search(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="ldap3 Connection search with f-string filter",
        cwe="CWE-90",
    ),
    SinkPattern(
        id="java-ldap-001",
        vuln_type=VulnType.LDAP_INJECTION,
        languages=[Language.JAVA],
        pattern=r'ctx\.search\s*\([^,]+,\s*"[^"]*"\s*\+',
        function_name="ctx.search(filter=concat)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="JNDI LDAP search with concatenated filter",
        cwe="CWE-90",
    ),
    SinkPattern(
        id="java-ldap-002",
        vuln_type=VulnType.LDAP_INJECTION,
        languages=[Language.JAVA],
        pattern=r"new\s+SearchControls\s*\(\s*\).*search\s*\(",
        function_name="LDAP SearchControls().search()",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="JNDI LDAP SearchControls -- check filter source",
        cwe="CWE-90",
    ),
])

# ==============================================================================
# LOG INJECTION
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-log-001",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"console\.(?:log|info|warn|error)\s*\(\s*`[^`]*\$\{(?:req|request|params|args|input|user|body|query)[^}]*\}",
        function_name="console.log(`${userInput}`)",
        severity=Severity.MEDIUM,
        confidence=Confidence.HIGH,
        description="Logging user input without sanitization -- log injection",
        cwe="CWE-117",
        remediation="Strip newlines and ANSI escape codes from log messages",
    ),
    SinkPattern(
        id="js-log-002",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"logger\.\w+\s*\(\s*`[^`]*\$\{(?:req|request|params|args|input|user)[^}]*\}",
        function_name="logger.info(`${userInput}`)",
        severity=Severity.MEDIUM,
        confidence=Confidence.HIGH,
        description="Logger with direct user input interpolation",
        cwe="CWE-117",
    ),
    SinkPattern(
        id="py-log-001",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"logging\.\w+\s*\(\s*f['\"][^'\"]*%s[^'\"]*['\"],\s*(?:request|user_input|args|params)",
        function_name="logging.info(f-string with user input)",
        severity=Severity.MEDIUM,
        confidence=Confidence.HIGH,
        description="Python logging with direct user input",
        cwe="CWE-117",
    ),
    SinkPattern(
        id="py-log-002",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"logger\.\w+\s*\(\s*f['\"][^'\"]*\{[^}]*(?:request\.|args\.|params\.)[^}]*\}",
        function_name="logger.info(f-string with request)",
        severity=Severity.MEDIUM,
        confidence=Confidence.HIGH,
        description="Python logger with request parameter in f-string",
        cwe="CWE-117",
    ),
])

# ==============================================================================
# HEADER INJECTION / OPEN REDIRECT
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-header-001",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"res\.(?:setHeader|set)\s*\([^)]*,\s*[^'\"`\s][^)]*\)",
        function_name="res.setHeader(name, variable)",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="HTTP header set with variable value -- header injection",
        cwe="CWE-113",
        negative_patterns=[r"res\.(?:setHeader|set)\s*\([^)]*,\s*['\"`]"],
    ),
    SinkPattern(
        id="js-header-002",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"res\.redirect\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="res.redirect(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Express redirect with variable URL -- open redirect",
        cwe="CWE-601",
        negative_patterns=[r"res\.redirect\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="py-header-001",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"(?:flask|response)\.headers\[.*\]\s*=\s*[^'\"\s]",
        function_name="response.headers[x] = variable",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="HTTP header set with variable -- header injection",
        cwe="CWE-113",
    ),
    SinkPattern(
        id="py-header-002",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"redirect\s*\(\s*(?:request\.|args\.|params\.|url)",
        function_name="redirect(request.url/args)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Flask redirect with request parameter -- open redirect",
        cwe="CWE-601",
    ),
])

# ==============================================================================
# ADDITIONAL COMMAND INJECTION -- more languages and frameworks
# ==============================================================================

PATTERNS.extend([
    # Python -- os.system() variations
    SinkPattern(
        id="py-cmdi-ext-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bos\.system\s*\(\s*[^'\"\s][^)]*\)",
        function_name="os.system(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="os.system() with variable command",
        cwe="CWE-78",
        negative_patterns=[r"os\.system\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-cmdi-ext-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bos\.popen\s*\(\s*f['\"]",
        function_name="os.popen(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="os.popen() with f-string command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmdi-ext-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bos\.popen\s*\([^)]*\+[^)]*\)",
        function_name="os.popen(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="os.popen() with concatenated command",
        cwe="CWE-78",
        negative_patterns=[r"os\.popen\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-cmdi-ext-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bexecv?\s*\(\s*f['\"]",
        function_name="os.execv(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="os.execv/execve with f-string path",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmdi-ext-005",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bsubprocess\.(?:run|call|Popen|check_output)\s*\(\s*[^'\"\[\s][^,)]*,\s*shell\s*=\s*True",
        function_name="subprocess(variable, shell=True)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess with shell=True and variable command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmdi-ext-006",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bfabric.*run\s*\(\s*f['\"]",
        function_name="fabric.run(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Fabric remote run() with f-string command",
        cwe="CWE-78",
    ),
    # Node: child_process variations
    SinkPattern(
        id="js-cmdi-ext-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bexecFile\s*\(\s*[^'\"`\s][^,)]*",
        function_name="execFile(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="child_process.execFile with variable path",
        cwe="CWE-78",
        negative_patterns=[r"execFile\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-cmdi-ext-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"execFileSync\s*\(\s*`[^`]*\$\{",
        function_name="execFileSync(`${}`)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="execFileSync with template literal path",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmdi-ext-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"childProcess\.fork\s*\(\s*[^'\"`\s][^,)]*",
        function_name="child_process.fork(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="child_process.fork with variable module path",
        cwe="CWE-78",
        negative_patterns=[r"fork\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-cmdi-ext-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"node:child_process.*spawn\s*\(\s*`[^`]*\$\{",
        function_name="node:child_process.spawn(`${}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="node:child_process spawn with template literal",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmdi-ext-005",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"shelljs\.exec\s*\(\s*[^'\"`\s][^,)]*",
        function_name="shelljs.exec(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="shelljs exec with variable command",
        cwe="CWE-78",
        negative_patterns=[r"shelljs\.exec\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-cmdi-ext-006",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"shelljs\.exec\s*\(\s*`[^`]*\$\{",
        function_name="shelljs.exec(`${}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="shelljs exec with template literal",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmdi-ext-007",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"execa\s*\(\s*[^'\"`\s][^,)]*",
        function_name="execa(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="execa with variable command",
        cwe="CWE-78",
        negative_patterns=[r"execa\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-cmdi-ext-008",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"execa\s*\(\s*`[^`]*\$\{",
        function_name="execa(`${}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="execa with template literal command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmdi-ext-009",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.(?:run|execute)\s*\(\s*['\"](?:bash|sh|cmd|powershell)['\"].*`[^`]*\$\{",
        function_name="shell.run('bash', `${}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Shell run with bash/sh and interpolated command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmdi-ext-010",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"Deno\.run\s*\(\s*\{\s*cmd\s*:",
        function_name="Deno.run({cmd: ...})",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Deno.run() -- check cmd source",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmdi-ext-011",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"Deno\.Command\s*\(\s*[^'\"`\s][^,)]*",
        function_name="Deno.Command(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Deno.Command with variable executable",
        cwe="CWE-78",
        negative_patterns=[r"Deno\.Command\s*\(\s*['\"`]"],
    ),
    # Go -- additional
    SinkPattern(
        id="go-cmdi-ext-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.GO],
        pattern=r"\bbash\.Exec\s*\(",
        function_name="bash.Exec()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="bash package Exec",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="go-cmdi-ext-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.GO],
        pattern=r"exec\.Command\s*\(\s*[^\"'][^,)]*,.*fmt\.Sprintf",
        function_name="exec.Command(variable, Sprintf)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Go exec.Command with Sprintf argument",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="go-cmdi-ext-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.GO],
        pattern=r'exec\.Command\s*\(\s*"sh"\s*,\s*"-c"',
        function_name="exec.Command('sh', '-c', ...)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="exec.Command with sh -c -- full shell enabled",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="go-cmdi-ext-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.GO],
        pattern=r'exec\.Command\s*\(\s*"bash"\s*,\s*"-c"',
        function_name="exec.Command('bash', '-c', ...)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="exec.Command with bash -c",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="go-cmdi-ext-005",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.GO],
        pattern=r"exec\.Command\s*\(\s*\w+\s*\)",
        function_name="exec.Command(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Go exec.Command with variable executable",
        cwe="CWE-78",
        negative_patterns=[r'exec\.Command\s*\(\s*"'],
    ),
    # Rust
    SinkPattern(
        id="rs-cmdi-ext-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUST],
        pattern=r'Command::new\s*\(\s*&?format!\s*\(',
        function_name="Command::new(format!())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Rust Command::new with format! macro",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="rs-cmdi-ext-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUST],
        pattern=r'Command::new\s*\(\s*&\w',
        function_name="Command::new(&variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Rust Command::new with variable",
        cwe="CWE-78",
        negative_patterns=[r'Command::new\s*\(\s*"'],
    ),
    SinkPattern(
        id="rs-cmdi-ext-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUST],
        pattern=r'\.arg\s*\(\s*&?format!\s*\(',
        function_name="Command.arg(format!())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Command::arg with format! macro -- argument injection",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="rs-cmdi-ext-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUST],
        pattern=r'\.args\s*\(\s*&\[.*format!\s*\(',
        function_name="Command.args([format!()])",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Command::args with format! in array",
        cwe="CWE-78",
    ),
    # C/C++
    SinkPattern(
        id="c-cmdi-ext-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bsprintf\s*\([^,]+,\s*[^,]+,.*\)",
        function_name="sprintf(buf, format, var)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="sprintf -- buffer overflow and injection risk",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="c-cmdi-ext-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bpopen\s*\(",
        function_name="popen()",
        severity=Severity.HIGH,
        confidence=Confidence.LOW,
        description="popen() -- shell command injection risk",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="c-cmdi-ext-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bexeclp?\s*\(",
        function_name="execl/execlp()",
        severity=Severity.HIGH,
        confidence=Confidence.LOW,
        description="execl/execlp -- check if args are user-controlled",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="c-cmdi-ext-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bexecvp?\s*\(",
        function_name="execvp()",
        severity=Severity.HIGH,
        confidence=Confidence.LOW,
        description="execvp -- check if argv contains user input",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="c-cmdi-ext-005",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bsnprintf\s*\([^)]*system\b",
        function_name="snprintf + system()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Command construction with snprintf + system",
        cwe="CWE-78",
    ),
    # C#
    SinkPattern(
        id="cs-cmdi-ext-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.CSHARP],
        pattern=r'new\s+Process\s*\{\s*StartInfo\s*=.*FileName\s*=',
        function_name="Process{StartInfo = ...FileName}",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="C# Process.Start -- check FileName/Arguments source",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="cs-cmdi-ext-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.CSHARP],
        pattern=r'ProcessStartInfo\s+\w+\s*=\s*new\s+ProcessStartInfo\s*\(\s*\$"',
        function_name="ProcessStartInfo($\"...\")",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="ProcessStartInfo with interpolated command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="cs-cmdi-ext-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.CSHARP],
        pattern=r'\.FileName\s*=\s*\$"',
        function_name="StartInfo.FileName = $\"...\"",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="ProcessStartInfo.FileName with interpolated string",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="cs-cmdi-ext-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.CSHARP],
        pattern=r'\.Arguments\s*=\s*\$"',
        function_name="StartInfo.Arguments = $\"...\"",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="ProcessStartInfo.Arguments with interpolated string",
        cwe="CWE-78",
    ),
])

# ==============================================================================
# ADDITIONAL PATH TRAVERSAL -- more languages
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="rs-path-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.RUST],
        pattern=r"fs::read_to_string\s*\(\s*&?format!\s*\(",
        function_name="fs::read_to_string(format!())",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Rust fs::read_to_string with format! path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="rs-path-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.RUST],
        pattern=r"File::open\s*\(\s*&?format!\s*\(",
        function_name="File::open(format!())",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Rust File::open with format! path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="rs-path-003",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.RUST],
        pattern=r"File::create\s*\(\s*&?format!\s*\(",
        function_name="File::create(format!())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Rust File::create with format! path -- arbitrary write",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="java-path-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.JAVA],
        pattern=r"new\s+FileReader\s*\(\s*(?:request|req)\.",
        function_name="new FileReader(request.getParameter)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Java FileReader from request parameter",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="java-path-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.JAVA],
        pattern=r"new\s+File\s*\(\s*[^\"'][^,)]*\+",
        function_name="new File(concat)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Java File with concatenated path",
        cwe="CWE-22",
        negative_patterns=[r"new\s+File\s*\(\s*\""],
    ),
    SinkPattern(
        id="java-path-003",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.JAVA],
        pattern=r"Paths\.get\s*\([^)]*\+",
        function_name="Paths.get(concat)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Java Paths.get with concatenation",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="php-path-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PHP],
        pattern=r"include\s*\(\s*\$(?:_GET|_POST|_REQUEST)",
        function_name="include($_GET/$POST)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP include with user-supplied path -- LFI/RFI",
        cwe="CWE-22",
        tags=["lfi", "rfi"],
    ),
    SinkPattern(
        id="php-path-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PHP],
        pattern=r"require\s*\(\s*\$(?:_GET|_POST|_REQUEST)",
        function_name="require($_GET/$POST)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP require with user-supplied path -- LFI/RFI",
        cwe="CWE-22",
        tags=["lfi", "rfi"],
    ),
    SinkPattern(
        id="php-path-003",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PHP],
        pattern=r"file_get_contents\s*\(\s*\$(?:_GET|_POST|_REQUEST)",
        function_name="file_get_contents($_GET)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="PHP file_get_contents with user-controlled path",
        cwe="CWE-22",
    ),
])

# ==============================================================================
# ADDITIONAL SSRF -- Java, PHP, Ruby
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="java-ssrf-001",
        vuln_type=VulnType.SSRF,
        languages=[Language.JAVA],
        pattern=r"new\s+URL\s*\(\s*[^\"'][^)]*\)",
        function_name="new URL(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Java URL from variable -- potential SSRF",
        cwe="CWE-918",
        negative_patterns=[r"new\s+URL\s*\(\s*\""],
    ),
    SinkPattern(
        id="java-ssrf-002",
        vuln_type=VulnType.SSRF,
        languages=[Language.JAVA],
        pattern=r"HttpClient.*\.execute\s*\(\s*new\s+HttpGet\s*\(",
        function_name="HttpClient.execute(new HttpGet(url))",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Apache HttpClient GET with variable URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="java-ssrf-003",
        vuln_type=VulnType.SSRF,
        languages=[Language.JAVA],
        pattern=r"RestTemplate.*getForObject\s*\(\s*[^\"'][^,)]*",
        function_name="RestTemplate.getForObject(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Spring RestTemplate with variable URL",
        cwe="CWE-918",
        negative_patterns=[r"getForObject\s*\(\s*\""],
    ),
    SinkPattern(
        id="java-ssrf-004",
        vuln_type=VulnType.SSRF,
        languages=[Language.JAVA],
        pattern=r"WebClient\.\w+\s*\(\s*\)\s*\.uri\s*\(\s*[^\"'][^)]*\)",
        function_name="WebClient.get().uri(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Spring WebClient with variable URI",
        cwe="CWE-918",
        negative_patterns=[r"\.uri\s*\(\s*\""],
    ),
    SinkPattern(
        id="php-ssrf-001",
        vuln_type=VulnType.SSRF,
        languages=[Language.PHP],
        pattern=r"curl_setopt\s*\([^,]+,\s*CURLOPT_URL\s*,\s*\$(?:_GET|_POST|_REQUEST)",
        function_name="curl_setopt(CURLOPT_URL, $_GET)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="PHP cURL with user-supplied URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="php-ssrf-002",
        vuln_type=VulnType.SSRF,
        languages=[Language.PHP],
        pattern=r"file_get_contents\s*\(\s*['\"]https?://",
        function_name="file_get_contents(http://...)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="PHP file_get_contents with HTTP URL -- SSRF risk",
        cwe="CWE-918",
    ),
])

# ==============================================================================
# ADDITIONAL DESERIALIZATION -- Java, PHP
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="java-deser-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.JAVA],
        pattern=r"new\s+ObjectInputStream\s*\(",
        function_name="new ObjectInputStream()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Java ObjectInputStream -- RCE via deserialization gadget chains",
        cwe="CWE-502",
        tags=["known-vuln"],
    ),
    SinkPattern(
        id="java-deser-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.JAVA],
        pattern=r"xstream\.fromXML\s*\(",
        function_name="XStream.fromXML()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="XStream.fromXML -- RCE without security framework",
        cwe="CWE-502",
    ),
    SinkPattern(
        id="java-deser-003",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.JAVA],
        pattern=r"ObjectMapper\s*\(\s*\)\.readValue\s*\(<.*Object\.class",
        function_name="ObjectMapper.readValue(Object.class)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Jackson readValue to Object.class -- polymorphic type risk",
        cwe="CWE-502",
    ),
    SinkPattern(
        id="java-deser-004",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.JAVA],
        pattern=r"enableDefaultTyping\s*\(",
        function_name="ObjectMapper.enableDefaultTyping()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Jackson enableDefaultTyping -- RCE via polymorphic deserialization",
        cwe="CWE-502",
        tags=["known-vuln"],
    ),
    SinkPattern(
        id="php-deser-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PHP],
        pattern=r"\bunserialize\s*\(\s*\$(?:_GET|_POST|_REQUEST|_COOKIE)",
        function_name="unserialize($_GET/$POST)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP unserialize with user input -- PHP object injection",
        cwe="CWE-502",
    ),
    SinkPattern(
        id="php-deser-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PHP],
        pattern=r"unserialize\s*\(",
        function_name="unserialize()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="PHP unserialize -- check if input is user-controlled",
        cwe="CWE-502",
    ),
])

# ==============================================================================
# ADDITIONAL CODE EXECUTION / EVAL
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-eval-ext-001",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\beval\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="eval(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="eval() with variable -- arbitrary code execution",
        cwe="CWE-94",
        negative_patterns=[r"eval\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-eval-ext-002",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\beval\s*\(\s*`[^`]*\$\{",
        function_name="eval(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="eval() with template literal",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="js-eval-ext-003",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bnew\s+Function\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="new Function(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="new Function() with variable -- eval equivalent",
        cwe="CWE-94",
        negative_patterns=[r"new\s+Function\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-eval-ext-004",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bnew\s+Function\s*\(\s*`[^`]*\$\{",
        function_name="new Function(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="new Function() with template literal",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="js-eval-ext-005",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"vm\.runInThisContext\s*\(",
        function_name="vm.runInThisContext()",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="Node.js vm.runInThisContext -- sandbox escape possible",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="js-eval-ext-006",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"vm\.runInNewContext\s*\(",
        function_name="vm.runInNewContext()",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="Node.js vm.runInNewContext -- sandbox escape possible",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="js-eval-ext-007",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"setTimeout\s*\(\s*[^'\"`\s)][^,)]*,",
        function_name="setTimeout(variable, ...)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="setTimeout with non-function first argument -- eval-like",
        cwe="CWE-94",
        negative_patterns=[r"setTimeout\s*\(\s*(?:function|\(\s*\)|['\"`])"],
    ),
    SinkPattern(
        id="js-eval-ext-008",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"setInterval\s*\(\s*[^'\"`\s)][^,)]*,",
        function_name="setInterval(variable, ...)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="setInterval with non-function first argument -- eval-like",
        cwe="CWE-94",
        negative_patterns=[r"setInterval\s*\(\s*(?:function|\(\s*\)|['\"`])"],
    ),
    SinkPattern(
        id="py-eval-ext-001",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PYTHON],
        pattern=r"\beval\s*\(\s*f['\"]",
        function_name="eval(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="eval() with f-string -- arbitrary code execution",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="py-eval-ext-002",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PYTHON],
        pattern=r"\beval\s*\(\s*[^'\"\s][^)]*\)",
        function_name="eval(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="eval() with variable",
        cwe="CWE-94",
        negative_patterns=[r"\beval\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-eval-ext-003",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PYTHON],
        pattern=r"\bexec\s*\(\s*f['\"]",
        function_name="exec(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="exec() with f-string",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="py-eval-ext-004",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PYTHON],
        pattern=r"\bexec\s*\(\s*[^'\"\s][^)]*\)",
        function_name="exec(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="exec() with variable",
        cwe="CWE-94",
        negative_patterns=[r"\bexec\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-eval-ext-005",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PYTHON],
        pattern=r"\bcompile\s*\(\s*[^'\"\s][^,)]*",
        function_name="compile(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="compile() with variable source -- then exec'd",
        cwe="CWE-94",
        negative_patterns=[r"\bcompile\s*\(\s*['\"]"],
    ),
    # Java
    SinkPattern(
        id="java-eval-001",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.JAVA],
        pattern=r"ScriptEngine.*eval\s*\(",
        function_name="ScriptEngine.eval()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Java ScriptEngine.eval -- arbitrary code execution",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="java-eval-002",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.JAVA],
        pattern=r"Runtime\.getRuntime\(\)\.exec\s*\(",
        function_name="Runtime.exec()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Java Runtime.exec() -- command execution",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="java-eval-003",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.JAVA],
        pattern=r"ProcessBuilder\s*\(\s*Arrays\.asList\s*\(",
        function_name="ProcessBuilder(Arrays.asList())",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Java ProcessBuilder -- check argument source",
        cwe="CWE-78",
    ),
    # PHP
    SinkPattern(
        id="php-eval-001",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PHP],
        pattern=r"\beval\s*\(",
        function_name="eval()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP eval() -- arbitrary code execution",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="php-eval-002",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PHP],
        pattern=r"\bpreg_replace\s*\([^,]*\/e\b",
        function_name="preg_replace(/e flag)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP preg_replace with /e modifier -- code execution",
        cwe="CWE-94",
        tags=["deprecated"],
    ),
    SinkPattern(
        id="php-eval-003",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PHP],
        pattern=r"\bsystem\s*\(\s*\$(?:_GET|_POST|_REQUEST)",
        function_name="system($_GET/$POST)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP system() with user-supplied command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="php-eval-004",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PHP],
        pattern=r"\b(?:shell_exec|passthru|exec)\s*\(\s*\$(?:_GET|_POST|_REQUEST)",
        function_name="shell_exec($_GET/$POST)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP shell_exec/passthru/exec with user input",
        cwe="CWE-78",
    ),
])

# ==============================================================================
# ADDITIONAL XXE -- Java
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="java-xxe-001",
        vuln_type=VulnType.XXE,
        languages=[Language.JAVA],
        pattern=r"DocumentBuilderFactory\.newInstance\s*\(\s*\)",
        function_name="DocumentBuilderFactory.newInstance()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="JAX DocumentBuilderFactory without entity disabling",
        cwe="CWE-611",
        remediation="Call dbf.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true)",
    ),
    SinkPattern(
        id="java-xxe-002",
        vuln_type=VulnType.XXE,
        languages=[Language.JAVA],
        pattern=r"SAXParserFactory\.newInstance\s*\(\s*\)",
        function_name="SAXParserFactory.newInstance()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="SAX parser without external entity disabling",
        cwe="CWE-611",
    ),
    SinkPattern(
        id="java-xxe-003",
        vuln_type=VulnType.XXE,
        languages=[Language.JAVA],
        pattern=r"XMLInputFactory\.newInstance\s*\(\s*\)",
        function_name="XMLInputFactory.newInstance()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="StAX XMLInputFactory -- check entity settings",
        cwe="CWE-611",
    ),
])

# ==============================================================================
# ADDITIONAL CRYPTO -- Java, C/C++
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="java-crypto-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.JAVA],
        pattern=r'MessageDigest\.getInstance\s*\(\s*"MD5"\s*\)',
        function_name="MessageDigest.getInstance(\"MD5\")",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="MD5 hash via Java MessageDigest",
        cwe="CWE-327",
    ),
    SinkPattern(
        id="java-crypto-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.JAVA],
        pattern=r'MessageDigest\.getInstance\s*\(\s*"SHA-1"\s*\)',
        function_name="MessageDigest.getInstance(\"SHA-1\")",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="SHA-1 hash via Java MessageDigest",
        cwe="CWE-327",
    ),
    SinkPattern(
        id="java-crypto-003",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.JAVA],
        pattern=r'Cipher\.getInstance\s*\(\s*"DES|Cipher\.getInstance\s*\(\s*"RC4|Cipher\.getInstance\s*\(\s*"RC2',
        function_name="Cipher.getInstance(\"DES/RC4/RC2\")",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Broken cipher (DES/RC4/RC2) via Java Cipher",
        cwe="CWE-327",
    ),
    SinkPattern(
        id="java-crypto-004",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.JAVA],
        pattern=r'Cipher\.getInstance\s*\(\s*"AES/ECB/',
        function_name="Cipher.getInstance(\"AES/ECB/...\")",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="AES in ECB mode via Java Cipher",
        cwe="CWE-327",
    ),
    SinkPattern(
        id="java-crypto-005",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.JAVA],
        pattern=r"new\s+Random\s*\(\s*\)",
        function_name="new Random()",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="java.util.Random -- not cryptographically secure",
        cwe="CWE-338",
        remediation="Use java.security.SecureRandom",
    ),
    SinkPattern(
        id="c-crypto-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.C, Language.CPP],
        pattern=r"\brand\s*\(\s*\)",
        function_name="rand()",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="C rand() -- not cryptographically secure PRNG",
        cwe="CWE-338",
    ),
    SinkPattern(
        id="c-crypto-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.C, Language.CPP],
        pattern=r"MD5_Init\s*\(",
        function_name="MD5_Init()",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="OpenSSL MD5 functions",
        cwe="CWE-327",
    ),
    SinkPattern(
        id="c-crypto-003",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.C, Language.CPP],
        pattern=r"SHA1_Init\s*\(",
        function_name="SHA1_Init()",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="OpenSSL SHA1 functions",
        cwe="CWE-327",
    ),
    SinkPattern(
        id="c-crypto-004",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.C, Language.CPP],
        pattern=r"DES_set_key\s*\(",
        function_name="DES_set_key()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="OpenSSL DES key setup -- broken cipher",
        cwe="CWE-327",
    ),
    SinkPattern(
        id="c-crypto-005",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.C, Language.CPP],
        pattern=r"SSL_CTX_set_options\s*\([^)]*SSL_OP_NO_TLSv1_2",
        function_name="SSL_CTX_set_options(SSL_OP_NO_TLSv1_2)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Disabling TLS 1.2 support",
        cwe="CWE-326",
    ),
])

# ==============================================================================
# OPEN REDIRECT -- JavaScript/Python
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-redirect-001",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"res\.redirect\s*\(\s*req\.(?:query|body|params)\.",
        function_name="res.redirect(req.query.*)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Open redirect with request parameter",
        cwe="CWE-601",
    ),
    SinkPattern(
        id="js-redirect-002",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"location\.href\s*=\s*[^'\"`\s][^;]*",
        function_name="location.href = variable",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Client-side redirect with variable URL -- open redirect/XSS",
        cwe="CWE-601",
        negative_patterns=[r"location\.href\s*=\s*['\"`]"],
    ),
    SinkPattern(
        id="py-redirect-001",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"return\s+redirect\s*\(\s*request\.(?:args|form|values|json)\[",
        function_name="redirect(request.args[url])",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Flask redirect from request parameter -- open redirect",
        cwe="CWE-601",
    ),
    SinkPattern(
        id="py-redirect-002",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"RedirectResponse\s*\(\s*(?:request\.|url\s*=\s*[^'\"\s])",
        function_name="RedirectResponse(request.*url)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="FastAPI RedirectResponse with request URL -- open redirect",
        cwe="CWE-601",
    ),
])

# ==============================================================================
# REDOS -- Regular expression Denial of Service
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-redos-001",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"new\s+RegExp\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="new RegExp(variable)",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="Dynamic RegExp from user input -- ReDoS risk",
        cwe="CWE-400",
        negative_patterns=[r"new\s+RegExp\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="py-redos-001",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"re\.compile\s*\(\s*[^'\"\s][^,)]*\)",
        function_name="re.compile(variable)",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="Python regex compile from variable -- ReDoS risk",
        cwe="CWE-400",
        negative_patterns=[r"re\.compile\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-redos-002",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"re\.(?:search|match|findall|fullmatch)\s*\(\s*[^'\"\s][^,)]*",
        function_name="re.search(variable_pattern)",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="Python re.search with variable pattern -- ReDoS risk",
        cwe="CWE-400",
        negative_patterns=[r"re\.\w+\s*\(\s*['\"]"],
    ),
])

# ==============================================================================
# HTTP RESPONSE SPLITTING
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-hrs-001",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"response\[['\"]\w+-\w+['\"]\]\s*=\s*[^'\"\s]",
        function_name="response['X-Header'] = variable",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="HTTP response header with variable value -- response splitting",
        cwe="CWE-113",
        negative_patterns=[r"response\[.*=\s*['\"]"],
    ),
    SinkPattern(
        id="js-hrs-001",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"res\.header\s*\(\s*[^,]+,\s*[^'\"`\s][^)]*\)",
        function_name="res.header(name, variable)",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="HTTP header set with variable -- response splitting",
        cwe="CWE-113",
        negative_patterns=[r"res\.header\s*\([^,]+,\s*['\"`]"],
    ),
])

# ==============================================================================
# MCP SERVER-SPECIFIC INJECTION
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="mcp-prompt-001",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"callTool\s*\(\s*[^,]+,\s*\{[^}]*?\}.*`[^`]*\$\{",
        function_name="callTool(name, {args}) + template literal",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="MCP callTool with interpolated arguments -- prompt injection",
        cwe="CWE-94",
        tags=["mcp", "prompt-injection"],
    ),
    SinkPattern(
        id="mcp-prompt-002",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"call_tool\s*\(\s*[^,]+,\s*\{[^}]*?\}.*f['\"]",
        function_name="call_tool(name, {args}) + f-string",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="MCP Python call_tool with f-string args -- prompt injection",
        cwe="CWE-94",
        tags=["mcp", "prompt-injection"],
    ),
    SinkPattern(
        id="mcp-rce-001",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"server\.tool\s*\(\s*[^,]+,\s*[^,]+,\s*async\s*\([^)]*\)\s*=>\s*\{[^}]*eval\s*\(",
        function_name="server.tool handler -> eval()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MCP tool handler with eval -- direct code execution",
        cwe="CWE-94",
        tags=["mcp", "tool-handler"],
    ),
    SinkPattern(
        id="mcp-rce-002",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"server\.tool\s*\(\s*[^,]+,\s*[^,]+,\s*async\s*\([^)]*\)\s*=>\s*\{[^}]*exec\s*\(",
        function_name="server.tool handler -> exec()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MCP tool handler with exec -- command injection",
        cwe="CWE-78",
        tags=["mcp", "tool-handler"],
    ),
    SinkPattern(
        id="mcp-tool-input-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"input\.[a-zA-Z_]+.*(?:exec|spawn|system|eval)\s*\(",
        function_name="tool input.field -> dangerous sink",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MCP tool input field used in dangerous function call",
        cwe="CWE-78",
        tags=["mcp", "tool-argument"],
    ),
    SinkPattern(
        id="mcp-tool-input-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"input\.[a-zA-Z_]*(?:path|file|dir)[a-zA-Z_]*.*(?:readFile|writeFile|readdir|mkdir)\s*\(",
        function_name="tool input.path -> fs.readFile()",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="MCP tool input path field used in file system operation",
        cwe="CWE-22",
        tags=["mcp", "tool-argument"],
    ),
    SinkPattern(
        id="mcp-tool-input-003",
        vuln_type=VulnType.SSRF,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"input\.[a-zA-Z_]*(?:url|endpoint|host|target)[a-zA-Z_]*.*(?:fetch|axios|request|http)\s*[.(]",
        function_name="tool input.url -> fetch()",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="MCP tool input URL field used in HTTP request",
        cwe="CWE-918",
        tags=["mcp", "tool-argument"],
    ),
    SinkPattern(
        id="mcp-tool-input-004",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"input\.[a-zA-Z_]*(?:query|sql|filter|search)[a-zA-Z_]*.*(?:\.query\(|\.execute\(|db\.run)",
        function_name="tool input.query -> db.query()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MCP tool input query/sql field used in DB operation",
        cwe="CWE-89",
        tags=["mcp", "tool-argument"],
    ),
])

PATTERN_COUNT = len(PATTERNS)
