"""
Bulk extension -- smaller gap-fill patterns to reach 800+ total.
Covers prototype pollution, race conditions, and additional vuln variants.
MCP-specific: includes tool argument flows into dangerous sinks.
"""


from mcpsec.static.patterns.base import (
    SinkPattern, Language, VulnType, Severity, Confidence
)

PATTERNS: list[SinkPattern] = []

# ==============================================================================
# PROTOTYPE POLLUTION -- JS/TS
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-pp-001",
        vuln_type=VulnType.PROTOTYPE_POLLUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"Object\.assign\s*\(\s*[^,)]+,\s*JSON\.parse\s*\(",
        function_name="Object.assign(target, JSON.parse(user))",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Object.assign from parsed JSON -- prototype pollution",
        cwe="CWE-1321",
    ),
    SinkPattern(
        id="js-pp-002",
        vuln_type=VulnType.PROTOTYPE_POLLUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"Object\.assign\s*\(\s*[^,)]+,\s*req\.body",
        function_name="Object.assign(target, req.body)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Object.assign from req.body -- prototype pollution",
        cwe="CWE-1321",
    ),
    SinkPattern(
        id="js-pp-003",
        vuln_type=VulnType.PROTOTYPE_POLLUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\[['\"]\s*__proto__\s*['\"]\]",
        function_name="['__proto__'] access",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Direct __proto__ property access -- prototype pollution",
        cwe="CWE-1321",
    ),
    SinkPattern(
        id="js-pp-004",
        vuln_type=VulnType.PROTOTYPE_POLLUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"obj\[key\]\s*=\s*value.*(?:for|forEach|reduce)",
        function_name="obj[key] = value in loop",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="Dynamic property assignment in loop -- check for __proto__",
        cwe="CWE-1321",
    ),
    SinkPattern(
        id="js-pp-005",
        vuln_type=VulnType.PROTOTYPE_POLLUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"deepmerge\s*\(\s*[^,)]+,\s*(?:req\.|JSON\.parse)",
        function_name="deepmerge(target, user_input)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="deepmerge with user input -- prototype pollution",
        cwe="CWE-1321",
    ),
    SinkPattern(
        id="js-pp-006",
        vuln_type=VulnType.PROTOTYPE_POLLUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"merge\s*\(\s*\{[^}]*\},\s*(?:req\.body|req\.query|req\.params)",
        function_name="merge({}, req.body)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Object merge with request data -- prototype pollution",
        cwe="CWE-1321",
    ),
    SinkPattern(
        id="js-pp-007",
        vuln_type=VulnType.PROTOTYPE_POLLUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"Object\.setPrototypeOf\s*\(",
        function_name="Object.setPrototypeOf()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Object.setPrototypeOf -- intentional prototype modification",
        cwe="CWE-1321",
    ),
    SinkPattern(
        id="js-pp-008",
        vuln_type=VulnType.PROTOTYPE_POLLUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"Object\.defineProperty\s*\(\s*Object\.prototype",
        function_name="Object.defineProperty(Object.prototype)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Direct modification of Object.prototype",
        cwe="CWE-1321",
    ),
])

# ==============================================================================
# MORE SQL INJECTION -- ORM specific
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-sql-orm-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.find\s*\(\s*\{\s*where\s*:\s*\{[^}]*\$\{",
        function_name=".find({where: {`${}`}})",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Sequelize/TypeORM find where with template literal",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-orm-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.count\s*\(\s*\{[^}]*where.*\$\{",
        function_name=".count({where: ... `${}`})",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="ORM count with template literal in where",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-orm-003",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.update\s*\(\s*[^,]+,\s*\{\s*where.*\$\{",
        function_name=".update(data, {where: `${}`})",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="ORM update with template literal in where",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-orm-004",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.destroy\s*\(\s*\{\s*where.*\$\{",
        function_name=".destroy({where: `${}`})",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="ORM destroy with template literal in where",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-orm-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"filter_by\s*\(\s*\*\*[^)]+\)",
        function_name="filter_by(**user_dict)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQLAlchemy filter_by with unpacked user dict",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-orm-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\.order_by\s*\(\s*f['\"]",
        function_name=".order_by(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="ORM order_by with f-string -- SQL injection in ORDER BY",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-orm-003",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\.having\s*\(\s*f['\"]",
        function_name=".having(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="ORM having with f-string -- SQL injection",
        cwe="CWE-89",
    ),
])

# ==============================================================================
# MORE COMMAND INJECTION -- CI/CD and tools context
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-ci-tool-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"(?:nmap|masscan|nuclei).*\w+\s*=\s*f['\"]",
        function_name="security_tool(f-string target)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Security scanning tool invoked with f-string argument",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-ci-tool-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"git\.Repo\(\)\.git\.(?:clone|pull|fetch)\s*\(",
        function_name="gitpython.git.clone()",
        severity=Severity.HIGH,
        confidence=Confidence.LOW,
        description="GitPython git operation -- check URL source",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-ci-tool-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"simple-git.*\.\w+\s*\(\s*[^'\"`\s][^,)]*",
        function_name="simple-git.operation(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="simple-git operation with variable argument",
        cwe="CWE-78",
        negative_patterns=[r"\.\w+\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-ci-tool-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"nodegit\.\w+\.\w+\s*\(\s*[^'\"`\s][^,)]*",
        function_name="nodegit.operation(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="nodegit operation with variable",
        cwe="CWE-78",
        negative_patterns=[r"\.\w+\s*\(\s*['\"`]"],
    ),
])

# ==============================================================================
# MORE SSRF -- WebSocket, gRPC, database connections as SSRF
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-ssrf-ws-001",
        vuln_type=VulnType.SSRF,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"new\s+WebSocket\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="new WebSocket(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="WebSocket connection to variable URL -- SSRF",
        cwe="CWE-918",
        negative_patterns=[r"new\s+WebSocket\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-ssrf-ws-002",
        vuln_type=VulnType.SSRF,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"new\s+WebSocket\s*\(\s*`[^`]*\$\{",
        function_name="new WebSocket(`${url}`)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="WebSocket with template literal URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="py-ssrf-ws-001",
        vuln_type=VulnType.SSRF,
        languages=[Language.PYTHON],
        pattern=r"websockets\.connect\s*\(\s*f['\"]",
        function_name="websockets.connect(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Python websockets.connect with f-string URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="py-ssrf-ws-002",
        vuln_type=VulnType.SSRF,
        languages=[Language.PYTHON],
        pattern=r"websocket\.create_connection\s*\(\s*f['\"]",
        function_name="websocket.create_connection(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="websocket-client create_connection with f-string",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="go-ssrf-ws-001",
        vuln_type=VulnType.SSRF,
        languages=[Language.GO],
        pattern=r"websocket\.Dial\s*\(\s*fmt\.Sprintf\s*\(",
        function_name="websocket.Dial(Sprintf())",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Go websocket.Dial with Sprintf URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="rs-ssrf-001",
        vuln_type=VulnType.SSRF,
        languages=[Language.RUST],
        pattern=r"reqwest::get\s*\(\s*&?format!\s*\(",
        function_name="reqwest::get(format!())",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Rust reqwest::get with format! URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="rs-ssrf-002",
        vuln_type=VulnType.SSRF,
        languages=[Language.RUST],
        pattern=r"reqwest::Client.*get\s*\(\s*&?format!\s*\(",
        function_name="reqwest::Client.get(format!())",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Rust reqwest Client.get with format! URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="cs-ssrf-001",
        vuln_type=VulnType.SSRF,
        languages=[Language.CSHARP],
        pattern=r"new\s+HttpClient\s*\(\s*\)\.GetAsync\s*\(\s*\$\"",
        function_name="HttpClient.GetAsync($\"...\")",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="C# HttpClient.GetAsync with interpolated URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="cs-ssrf-002",
        vuln_type=VulnType.SSRF,
        languages=[Language.CSHARP],
        pattern=r"new\s+HttpClient\s*\(\s*\)\.PostAsync\s*\(\s*\$\"",
        function_name="HttpClient.PostAsync($\"...\")",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="C# HttpClient.PostAsync with interpolated URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="cs-ssrf-003",
        vuln_type=VulnType.SSRF,
        languages=[Language.CSHARP],
        pattern=r"WebClient\s*\(\s*\)\.DownloadString\s*\(\s*\$\"",
        function_name="WebClient.DownloadString($\"...\")",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="C# WebClient.DownloadString with interpolated URL",
        cwe="CWE-918",
    ),
])

# ==============================================================================
# MORE PATH TRAVERSAL -- Go and Rust
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="go-pt-extra-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.GO],
        pattern=r"os\.Open\s*\(\s*fmt\.Sprintf\s*\(",
        function_name="os.Open(fmt.Sprintf())",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Go os.Open with Sprintf path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="go-pt-extra-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.GO],
        pattern=r"os\.Create\s*\(\s*fmt\.Sprintf\s*\(",
        function_name="os.Create(fmt.Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Go os.Create with Sprintf path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="go-pt-extra-003",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.GO],
        pattern=r"ioutil\.ReadFile\s*\(\s*fmt\.Sprintf\s*\(",
        function_name="ioutil.ReadFile(Sprintf())",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Go ioutil.ReadFile with Sprintf path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="go-pt-extra-004",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.GO],
        pattern=r"ioutil\.WriteFile\s*\(\s*fmt\.Sprintf\s*\(",
        function_name="ioutil.WriteFile(Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Go ioutil.WriteFile with Sprintf path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="go-pt-extra-005",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.GO],
        pattern=r"os\.Remove\s*\(\s*fmt\.Sprintf\s*\(",
        function_name="os.Remove(Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Go os.Remove with Sprintf path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="go-pt-extra-006",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.GO],
        pattern=r"filepath\.Join\s*\([^)]*\+[^)]*\)",
        function_name="filepath.Join(concat)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="filepath.Join with concatenated component -- path traversal risk",
        cwe="CWE-22",
        negative_patterns=[r"filepath\.Join\s*\(\s*\""],
    ),
    SinkPattern(
        id="rs-pt-extra-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.RUST],
        pattern=r"std::fs::remove_file\s*\(\s*&?format!\s*\(",
        function_name="fs::remove_file(format!())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Rust fs::remove_file with format! path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="rs-pt-extra-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.RUST],
        pattern=r"Path::new\s*\(\s*&?format!\s*\(",
        function_name="Path::new(format!())",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Rust Path::new with format! -- check for traversal",
        cwe="CWE-22",
    ),
])

# ==============================================================================
# MORE DESERIALIZATION -- C#, Go
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="cs-deser-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.CSHARP],
        pattern=r"BinaryFormatter\s*\(\s*\)\.Deserialize\s*\(",
        function_name="BinaryFormatter.Deserialize()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="C# BinaryFormatter.Deserialize -- RCE via gadget chains",
        cwe="CWE-502",
        tags=["known-vuln"],
    ),
    SinkPattern(
        id="cs-deser-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.CSHARP],
        pattern=r"SoapFormatter\s*\(\s*\)\.Deserialize\s*\(",
        function_name="SoapFormatter.Deserialize()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="C# SoapFormatter.Deserialize -- RCE",
        cwe="CWE-502",
        tags=["known-vuln"],
    ),
    SinkPattern(
        id="cs-deser-003",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.CSHARP],
        pattern=r"JsonConvert\.DeserializeObject\s*<object>",
        function_name="JsonConvert.DeserializeObject<object>()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Newtonsoft DeserializeObject to Object -- TypeNameHandling risk",
        cwe="CWE-502",
    ),
    SinkPattern(
        id="cs-deser-004",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.CSHARP],
        pattern=r"TypeNameHandling\.\s*(?:All|Objects|Auto)",
        function_name="TypeNameHandling.All/Objects/Auto",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Newtonsoft TypeNameHandling enabled -- RCE via gadgets",
        cwe="CWE-502",
        tags=["known-vuln"],
    ),
    SinkPattern(
        id="go-deser-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.GO],
        pattern=r"encoding/gob.*Decode\s*\(",
        function_name="gob.Decode()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Go gob Decode -- check if input is trusted",
        cwe="CWE-502",
    ),
    SinkPattern(
        id="go-deser-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.GO],
        pattern=r"yaml\.Unmarshal\s*\([^,]+,\s*&[^)]+interface",
        function_name="yaml.Unmarshal(data, &interface{})",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Go YAML unmarshal to interface{} -- check for type coercion",
        cwe="CWE-502",
    ),
])

# ==============================================================================
# MORE XXE -- additional frameworks
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="cs-xxe-001",
        vuln_type=VulnType.XXE,
        languages=[Language.CSHARP],
        pattern=r"XmlDocument\s*\(\s*\)\.Load\s*\(",
        function_name="XmlDocument.Load()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="C# XmlDocument.Load -- check ProhibitDtd",
        cwe="CWE-611",
        remediation="Set XmlDocument.XmlResolver = null",
    ),
    SinkPattern(
        id="cs-xxe-002",
        vuln_type=VulnType.XXE,
        languages=[Language.CSHARP],
        pattern=r"XDocument\.Load\s*\(",
        function_name="XDocument.Load()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="C# XDocument.Load -- check DTD settings",
        cwe="CWE-611",
    ),
    SinkPattern(
        id="go-xxe-001",
        vuln_type=VulnType.XXE,
        languages=[Language.GO],
        pattern=r"xml\.Unmarshal\s*\(",
        function_name="xml.Unmarshal()",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="Go xml.Unmarshal -- Go's stdlib is not XXE vulnerable, but check custom parsers",
        cwe="CWE-611",
    ),
    SinkPattern(
        id="rs-xxe-001",
        vuln_type=VulnType.XXE,
        languages=[Language.RUST],
        pattern=r"quick_xml::Reader::from_str\s*\(",
        function_name="quick_xml::Reader::from_str()",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="quick_xml parser -- verify entity expansion settings",
        cwe="CWE-611",
    ),
])

# ==============================================================================
# GRAPHQL INJECTION
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-graphql-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"gql`[^`]*\$\{(?!gql)[^}]+\}",
        function_name="gql`...${var}...`",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="GraphQL template tag with raw variable interpolation -- injection",
        cwe="CWE-89",
        remediation="Use GraphQL variables instead of interpolating into queries",
    ),
    SinkPattern(
        id="js-graphql-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"buildSchema\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="buildSchema(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="GraphQL buildSchema from variable -- schema injection",
        cwe="CWE-89",
        negative_patterns=[r"buildSchema\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="py-graphql-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"graphql\s*\(\s*schema,\s*f['\"]",
        function_name="graphql(schema, f-string query)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="GraphQL execution with f-string query",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-graphql-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"client\.execute\s*\(\s*gql\s*\(\s*f['\"]",
        function_name="client.execute(gql(f-string))",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="GQL client execute with f-string query",
        cwe="CWE-89",
    ),
])

# ==============================================================================
# REDIS KEY INJECTION
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-redis-001",
        vuln_type=VulnType.NOSQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"redis\.\w+\.(?:get|set|delete|hget|hset)\s*\(\s*f['\"]",
        function_name="redis.client.get/set(f-string key)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Redis operation with f-string key -- key injection",
        cwe="CWE-943",
    ),
    SinkPattern(
        id="py-redis-002",
        vuln_type=VulnType.NOSQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"redis\.\w+\.eval\s*\(\s*[^,)]+,",
        function_name="redis.eval(script, numkeys, ...)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Redis EVAL -- Lua script code execution",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="js-redis-001",
        vuln_type=VulnType.NOSQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"redis\.(?:get|set|del|hget|hset)\s*\(\s*`[^`]*\$\{",
        function_name="redis.get/set(`${key}`)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Redis operation with template literal key",
        cwe="CWE-943",
    ),
    SinkPattern(
        id="js-redis-002",
        vuln_type=VulnType.NOSQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"redis\.eval\s*\(\s*[^'\"`\s][^,)]*,",
        function_name="redis.eval(script, ...)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Redis EVAL with variable script -- Lua code execution",
        cwe="CWE-94",
        negative_patterns=[r"redis\.eval\s*\(\s*['\"`]"],
    ),
])

# ==============================================================================
# MCP TOOL ARGUMENT SINKS -- specific to MCP server vulnerabilities
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="mcp-ci-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"args\[(?:['\"]command['\"]|\w+)\].*(?:exec|spawn|system)\s*\(",
        function_name="args[command] -> exec()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MCP tool argument 'command' passed to shell execution",
        cwe="CWE-78",
        tags=["mcp", "tool-argument"],
    ),
    SinkPattern(
        id="mcp-ci-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"arguments\[(?:['\"]command['\"]|\w+)\].*(?:subprocess|os\.system|os\.popen)",
        function_name="arguments[command] -> subprocess",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MCP Python tool argument to subprocess",
        cwe="CWE-78",
        tags=["mcp", "tool-argument"],
    ),
    SinkPattern(
        id="mcp-pt-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"args\[(?:['\"]path['\"]|['\"]file['\"]|['\"]filename['\"]|\w+)\].*(?:readFile|writeFile|readdir)",
        function_name="args[path] -> fs.readFile()",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="MCP tool argument 'path' or 'file' passed to fs operations",
        cwe="CWE-22",
        tags=["mcp", "tool-argument"],
    ),
    SinkPattern(
        id="mcp-pt-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"arguments\[(?:['\"]path['\"]|['\"]file['\"]|\w+)\].*(?:open|read|write)",
        function_name="arguments[path] -> open()",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="MCP Python tool argument to file operations",
        cwe="CWE-22",
        tags=["mcp", "tool-argument"],
    ),
    SinkPattern(
        id="mcp-ssrf-001",
        vuln_type=VulnType.SSRF,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"args\[(?:['\"]url['\"]|['\"]endpoint['\"]|['\"]host['\"]|\w+)\].*(?:fetch|axios|request)",
        function_name="args[url] -> fetch()",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="MCP tool argument 'url' or 'endpoint' passed to HTTP request",
        cwe="CWE-918",
        tags=["mcp", "tool-argument"],
    ),
    SinkPattern(
        id="mcp-ssrf-002",
        vuln_type=VulnType.SSRF,
        languages=[Language.PYTHON],
        pattern=r"arguments\[(?:['\"]url['\"]|['\"]endpoint['\"]|\w+)\].*(?:requests\.|httpx\.|urllib)",
        function_name="arguments[url] -> requests.get()",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="MCP Python tool argument to HTTP request",
        cwe="CWE-918",
        tags=["mcp", "tool-argument"],
    ),
    SinkPattern(
        id="mcp-sql-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"args\[(?:['\"]query['\"]|['\"]sql['\"]|['\"]filter['\"]|\w+)\].*(?:\.query\(|\.execute\()",
        function_name="args[query] -> db.query()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MCP tool argument 'query' or 'sql' passed to DB query",
        cwe="CWE-89",
        tags=["mcp", "tool-argument"],
    ),
    SinkPattern(
        id="mcp-eval-001",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"args\[(?:['\"]code['\"]|['\"]script['\"]|['\"]expression['\"]|\w+)\].*(?:eval|new Function|vm\.)",
        function_name="args[code] -> eval()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MCP tool argument 'code' or 'script' passed to eval",
        cwe="CWE-94",
        tags=["mcp", "tool-argument"],
    ),
])

# ==============================================================================
# AI/ML MODEL LOADING SINKS
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-mlsec-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern=r"huggingface_hub.*hf_hub_download\s*\(\s*[^'\"\s][^,)]*",
        function_name="hf_hub_download(variable repo)",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="HuggingFace model download from variable repo -- supply chain",
        cwe="CWE-502",
        tags=["mlsec", "supply-chain"],
        negative_patterns=[r"hf_hub_download\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-mlsec-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern=r"AutoModel\.from_pretrained\s*\(\s*[^'\"\s][^,)]*",
        function_name="AutoModel.from_pretrained(variable)",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="HuggingFace from_pretrained with variable path -- unsafe pickle",
        cwe="CWE-502",
        tags=["mlsec"],
        negative_patterns=[r"from_pretrained\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-mlsec-003",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PYTHON],
        pattern=r"pickle\.load\s*\(\s*open\s*\(\s*f['\"]",
        function_name="pickle.load(open(f-string))",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Pickle load from f-string path",
        cwe="CWE-502",
    ),
    SinkPattern(
        id="py-mlsec-004",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PYTHON],
        pattern=r"safetensors\.torch\.load_file\s*\(.*pickle",
        function_name="safetensors fallback to pickle",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="safetensors load falling back to pickle",
        cwe="CWE-502",
        tags=["mlsec"],
    ),
])

# ==============================================================================
# FINAL TOP-UP -- 10 patterns to cross 800
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-taint-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"subprocess\.run\s*\(\s*shlex\.split\s*\(\s*[^'\"\s][^)]*\)",
        function_name="subprocess.run(shlex.split(variable))",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess.run with shlex.split of variable -- still injectable via split tokens",
        cwe="CWE-78",
        negative_patterns=[r"shlex\.split\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-taint-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"session\.execute\s*\(\s*text\s*\(\s*f['\"]",
        function_name="session.execute(text(f-string))",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQLAlchemy session execute with text() f-string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-taint-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"kysely.*\braw\s*\(\s*`[^`]*\$\{",
        function_name="kysely.raw(`${}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Kysely raw SQL with template literal",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="go-taint-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.GO],
        pattern=r"exec\.Command\s*\(\s*\"sh\"\s*,\s*\"-c\"\s*,\s*\w+\s*\+",
        function_name="exec.Command('sh', '-c', concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Go sh -c with concatenated command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-taint-002",
        vuln_type=VulnType.SSRF,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"got\s*\.\s*(?:get|post|put|delete)\s*\(\s*[^'\"`\s][^,)]*",
        function_name="got.get/post(variable url)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="got HTTP client with variable URL",
        cwe="CWE-918",
        negative_patterns=[r"got\.\w+\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="py-taint-003",
        vuln_type=VulnType.SSRF,
        languages=[Language.PYTHON],
        pattern=r"aiohttp\.ClientSession\s*\(\s*\).*\.(get|post)\s*\(\s*f['\"]",
        function_name="aiohttp.ClientSession.get(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="aiohttp ClientSession with f-string URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="rs-taint-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUST],
        pattern=r"std::process::Command::new\s*\(\s*&?format!\s*\(",
        function_name="std::process::Command::new(format!())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Rust std::process::Command with format! executable",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="cs-taint-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.CSHARP],
        pattern=r"File\.ReadAllText\s*\(\s*\$\"",
        function_name="File.ReadAllText($\"...\")",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="C# File.ReadAllText with interpolated path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="cs-taint-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.CSHARP],
        pattern=r"File\.WriteAllText\s*\(\s*\$\"",
        function_name="File.WriteAllText($\"...\")",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="C# File.WriteAllText with interpolated path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="java-taint-001",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.JAVA],
        pattern=r"ThymeleafTemplateEngine.*process\s*\(\s*[^\",)][^,)]*",
        function_name="Thymeleaf.process(variable_template)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Thymeleaf template engine with variable template name -- SSTI",
        cwe="CWE-94",
        negative_patterns=[r"process\s*\(\s*\""],
    ),
])

PATTERN_COUNT = len(PATTERNS)

