"""
Command Injection patterns -- ~200 patterns across 6 languages.

Coverage:
- TypeScript/JavaScript: child_process, vm, eval, Deno, Bun, shelljs, execa, zx (50+)
- Python: os, subprocess, eval/exec, fabric, paramiko, asyncio (50+)
- Go: os/exec, syscall (30+)
- Rust: std::process, tokio::process (20+)
- C/C++: system, popen, exec*, CreateProcess (30+)
- C#: Process, PowerShell (20+)
"""

from mcpsec.static.patterns.base import (
    SinkPattern, Language, VulnType, Severity, Confidence
)

PATTERNS: list[SinkPattern] = []

# ==============================================================================
# TYPESCRIPT / JAVASCRIPT -- child_process
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-cmd-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bexec\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="exec(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="child_process.exec() with non-literal argument",
        cwe="CWE-78",
        remediation="Use execFile() with arguments array, or spawn() with shell:false",
        negative_patterns=[
            r"exec\s*\(\s*['\"]",
            r"\.exec\s*\(",
            r"cursor\.exec",
            r"db\.exec",
            r"stmt\.exec",
        ],
    ),
    SinkPattern(
        id="js-cmd-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bexec\s*\(\s*`[^`]*\$\{[^}]+\}",
        function_name="exec(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="exec() with template literal interpolation",
        cwe="CWE-78",
        remediation="Never use template literals in exec(). Use execFile() with args array.",
    ),
    SinkPattern(
        id="js-cmd-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bexec\s*\([^)]*\+[^)]*\)",
        function_name="exec(a + b)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="exec() with string concatenation",
        cwe="CWE-78",
        remediation="Use execFile() with args array instead of string concatenation.",
        negative_patterns=[r"\.exec\s*\("],
    ),
    SinkPattern(
        id="js-cmd-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bexecSync\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="execSync(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="execSync() with non-literal argument",
        cwe="CWE-78",
        negative_patterns=[r"execSync\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="js-cmd-005",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bexecSync\s*\(\s*`[^`]*\$\{",
        function_name="execSync(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="execSync() with template literal interpolation",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmd-006",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bexecFile\s*\(\s*[^'\"`\s][^,)]*,\s*\[[^\]]*\$\{",
        function_name="execFile(variable, [${...}])",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="execFile() with interpolated arguments array",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmd-007",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bexecFileSync\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="execFileSync(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="execFileSync() with variable command",
        cwe="CWE-78",
        negative_patterns=[r"execFileSync\s*\(\s*['\"]"],
    ),
])

# -- spawn / spawnSync --
PATTERNS.extend([
    SinkPattern(
        id="js-cmd-010",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bspawn\s*\([^)]*shell\s*:\s*true",
        function_name="spawn({shell:true})",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="spawn() with shell:true enables command injection",
        cwe="CWE-78",
        remediation="Use shell:false (default) and pass arguments as array",
    ),
    SinkPattern(
        id="js-cmd-011",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bspawn\s*\(\s*['\"](?:sh|bash|cmd|cmd\.exe|powershell|pwsh)['\"]",
        function_name="spawn('sh')",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="spawn() invoking shell directly",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmd-012",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bspawnSync\s*\([^)]*shell\s*:\s*true",
        function_name="spawnSync({shell:true})",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="spawnSync() with shell:true",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmd-013",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bspawn\s*\(\s*[^'\"\s][^,)]*,",
        function_name="spawn(variable, ...)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="spawn() with variable command name",
        cwe="CWE-78",
        negative_patterns=[r"\bspawn\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="js-cmd-014",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bspawnSync\s*\(\s*[^'\"\s][^,)]*,",
        function_name="spawnSync(variable, ...)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="spawnSync() with variable command name",
        cwe="CWE-78",
        negative_patterns=[r"\bspawnSync\s*\(\s*['\"]"],
    ),
])

# -- eval / Function constructor --
PATTERNS.extend([
    SinkPattern(
        id="js-cmd-020",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"(?<!\w)\beval\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="eval(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="eval() with non-literal -- arbitrary code execution",
        cwe="CWE-94",
        negative_patterns=[r"\.eval\s*\(", r"eval\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="js-cmd-021",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bnew\s+Function\s*\([^)]*[^'\"`][^)]*\)",
        function_name="new Function(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Function constructor with dynamic code",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="js-cmd-022",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\beval\s*\(\s*`[^`]*\$\{",
        function_name="eval(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="eval() with template literal",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="js-cmd-023",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bsetTimeout\s*\(\s*[^'\"\[]\w",
        function_name="setTimeout(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="setTimeout() with non-function first arg executes eval",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="js-cmd-024",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bsetInterval\s*\(\s*[^'\"\[]\w",
        function_name="setInterval(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="setInterval() with non-function first arg executes eval",
        cwe="CWE-94",
    ),
])

# -- vm module --
PATTERNS.extend([
    SinkPattern(
        id="js-cmd-030",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bvm\.runInNewContext\s*\(",
        function_name="vm.runInNewContext()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="vm.runInNewContext -- sandbox escapes exist",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="js-cmd-031",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bvm\.runInThisContext\s*\(",
        function_name="vm.runInThisContext()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="vm.runInThisContext -- no isolation",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="js-cmd-032",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bvm2\b",
        function_name="vm2",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="vm2 library -- multiple known sandbox escapes (CVE-2023-29199)",
        cwe="CWE-94",
        tags=["known-vuln"],
    ),
    SinkPattern(
        id="js-cmd-033",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bvm\.runInContext\s*\(",
        function_name="vm.runInContext()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="vm.runInContext -- limited sandboxing",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="js-cmd-034",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bvm\.Script\s*\(",
        function_name="new vm.Script()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="vm.Script with dynamic code",
        cwe="CWE-94",
    ),
])

# -- Shell libraries: execa, shelljs, zx, cross-spawn --
PATTERNS.extend([
    SinkPattern(
        id="js-cmd-040",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bexeca\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="execa(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="execa with variable command",
        cwe="CWE-78",
        negative_patterns=[r"execa\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="js-cmd-041",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\b(?:shelljs|shell)\.exec\s*\(",
        function_name="shelljs.exec()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="shelljs.exec() -- shell command execution",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmd-042",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\$`[^`]*\$\{[^}]+\}",
        function_name="zx $`${...}`",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="zx shell template with interpolation",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmd-043",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bcrossSpawn\s*\([^)]*shell\s*:\s*true",
        function_name="crossSpawn(shell:true)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="cross-spawn with shell:true",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmd-044",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\b(?:execa|execaSync)\.(?:command|commandSync)\s*\(",
        function_name="execa.command()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="execa.command() parses shell-style string",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmd-045",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bshell\.exec\s*\([^)]*\+",
        function_name="shell.exec(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="shelljs exec with string concatenation",
        cwe="CWE-78",
    ),
])

# -- Deno / Bun --
PATTERNS.extend([
    SinkPattern(
        id="js-cmd-050",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bDeno\.Command\s*\(",
        function_name="Deno.Command()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Deno.Command -- command execution",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmd-051",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bBun\.spawn\s*\(",
        function_name="Bun.spawn()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Bun.spawn() -- command execution",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmd-052",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bDeno\.run\s*\(",
        function_name="Deno.run()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Deno.run() -- deprecated but still used",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmd-053",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bBun\.spawnSync\s*\(",
        function_name="Bun.spawnSync()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Bun.spawnSync() -- command execution",
        cwe="CWE-78",
    ),
])

# -- Node.js worker_threads / require edge cases --
PATTERNS.extend([
    SinkPattern(
        id="js-cmd-060",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\brequire\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="require(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Dynamic require() with variable -- arbitrary module load",
        cwe="CWE-94",
        negative_patterns=[r"require\s*\(\s*['\"]", r"require\.resolve"],
    ),
    SinkPattern(
        id="js-cmd-061",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bimport\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="import(variable)",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="Dynamic import() with variable path",
        cwe="CWE-94",
        negative_patterns=[r"import\s*\(\s*['\"]"],
    ),
])

# ==============================================================================
# PYTHON -- os module
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-cmd-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bos\.system\s*\(",
        function_name="os.system()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="os.system() executes shell commands",
        cwe="CWE-78",
        remediation="Use subprocess.run() with shell=False and args list",
    ),
    SinkPattern(
        id="py-cmd-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bos\.popen\s*\(",
        function_name="os.popen()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="os.popen() executes shell commands",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmd-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bos\.spawn[lv]?[pe]?\s*\(",
        function_name="os.spawn*()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="os.spawn family -- process execution",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmd-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bos\.exec[lv]?[pe]?\s*\(",
        function_name="os.exec*()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="os.exec family -- replaces process",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmd-005",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bos\.popen2\s*\(",
        function_name="os.popen2()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="os.popen2() deprecated but still used",
        cwe="CWE-78",
    ),
])

# -- subprocess --
PATTERNS.extend([
    SinkPattern(
        id="py-cmd-010",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bsubprocess\.(?:run|call|Popen|check_output|check_call)\s*\([^)]*shell\s*=\s*True",
        function_name="subprocess(shell=True)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess with shell=True enables injection",
        cwe="CWE-78",
        remediation="Use shell=False and pass args as list: subprocess.run(['cmd', 'arg'])",
    ),
    SinkPattern(
        id="py-cmd-011",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bsubprocess\.(?:run|call|Popen)\s*\(\s*f['\"]",
        function_name="subprocess(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess with f-string command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmd-012",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bsubprocess\.(?:run|call|Popen)\s*\([^)]*\.format\s*\(",
        function_name="subprocess(.format())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess with .format() interpolation",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmd-013",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bsubprocess\.(?:run|call|Popen)\s*\([^)]*%[^)]*%",
        function_name="subprocess(% format)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess with % string formatting",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmd-014",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bsubprocess\.getoutput\s*\(",
        function_name="subprocess.getoutput()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess.getoutput() always uses shell",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmd-015",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bsubprocess\.getstatusoutput\s*\(",
        function_name="subprocess.getstatusoutput()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess.getstatusoutput() always uses shell",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmd-016",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bPopen\s*\([^)]*shell\s*=\s*True",
        function_name="Popen(shell=True)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Popen direct import with shell=True",
        cwe="CWE-78",
    ),
])

# -- eval/exec --
PATTERNS.extend([
    SinkPattern(
        id="py-cmd-020",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"(?<!\w)\beval\s*\(\s*[^'\"\s][^)]*\)",
        function_name="eval(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="eval() with non-literal -- code execution",
        cwe="CWE-94",
        negative_patterns=[r"eval\s*\(\s*['\"]", r"literal_eval"],
    ),
    SinkPattern(
        id="py-cmd-021",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"(?<!\w)\bexec\s*\(\s*[^'\"\s][^)]*\)",
        function_name="exec(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="exec() with non-literal -- code execution",
        cwe="CWE-94",
        negative_patterns=[r"exec\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-cmd-022",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bcompile\s*\([^)]+['\"]exec['\"]",
        function_name="compile(mode='exec')",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="compile() with exec mode",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="py-cmd-023",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\b__import__\s*\(\s*[^'\"\s][^)]*\)",
        function_name="__import__(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Dynamic __import__() with variable",
        cwe="CWE-94",
        negative_patterns=[r"__import__\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-cmd-024",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bimportlib\.import_module\s*\(\s*[^'\"\s][^)]*\)",
        function_name="importlib.import_module(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="importlib with variable module name",
        cwe="CWE-94",
        negative_patterns=[r"import_module\s*\(\s*['\"]"],
    ),
])

# -- asyncio subprocess --
PATTERNS.extend([
    SinkPattern(
        id="py-cmd-030",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\basyncio\.create_subprocess_shell\s*\(",
        function_name="asyncio.create_subprocess_shell()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="asyncio shell subprocess",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmd-031",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\basyncio\.create_subprocess_exec\s*\([^)]*shell\s*=\s*True",
        function_name="asyncio.create_subprocess_exec(shell=True)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="asyncio exec subprocess with shell=True",
        cwe="CWE-78",
    ),
])

# -- Third-party: fabric, paramiko, pexpect, invoke --
PATTERNS.extend([
    SinkPattern(
        id="py-cmd-040",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bfabric\.(?:run|local|sudo)\s*\(",
        function_name="fabric.run/local/sudo()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Fabric command execution",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmd-041",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\.exec_command\s*\(",
        function_name="paramiko.exec_command()",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="Paramiko SSH command execution",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmd-042",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bpexpect\.(?:spawn|run)\s*\(",
        function_name="pexpect.spawn/run()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="pexpect command execution",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmd-043",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bc\.run\s*\(",
        function_name="invoke/fabric c.run()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Invoke/Fabric context run()",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmd-044",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bplumbum\b",
        function_name="plumbum",
        severity=Severity.HIGH,
        confidence=Confidence.LOW,
        description="Plumbum shell library usage",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmd-045",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bsh\.\w+\s*\(",
        function_name="sh.command()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Python 'sh' library command execution",
        cwe="CWE-78",
    ),
])

# ==============================================================================
# GO
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="go-cmd-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.GO],
        pattern=r"\bexec\.Command\s*\(\s*[^\"'][^)]*\)",
        function_name="exec.Command(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="exec.Command() with variable command",
        cwe="CWE-78",
        negative_patterns=[r"exec\.Command\s*\(\s*\""],
    ),
    SinkPattern(
        id="go-cmd-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.GO],
        pattern=r"\bexec\.Command\s*\(\s*[\"'](?:sh|bash|cmd|/bin/sh)[\"']\s*,\s*[\"']-c[\"']",
        function_name="exec.Command('sh', '-c')",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="exec.Command invoking shell with -c",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="go-cmd-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.GO],
        pattern=r"fmt\.Sprintf\s*\(",
        function_name="exec.Command(Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Command built with fmt.Sprintf",
        cwe="CWE-78",
        context_patterns=[r"exec\.Command"],
    ),
    SinkPattern(
        id="go-cmd-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.GO],
        pattern=r"\bsyscall\.Exec\s*\(",
        function_name="syscall.Exec()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="syscall.Exec -- low-level exec",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="go-cmd-005",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.GO],
        pattern=r"\bsyscall\.StartProcess\s*\(",
        function_name="syscall.StartProcess()",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="syscall.StartProcess()",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="go-cmd-006",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.GO],
        pattern=r"\.CombinedOutput\s*\(\)|\b\.Output\s*\(\)",
        function_name="cmd.Output()/CombinedOutput()",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="Command output collection -- check command source",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="go-cmd-007",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.GO],
        pattern=r"\bexec\.CommandContext\s*\([^,]+,\s*[^\"'][^,)]*",
        function_name="exec.CommandContext(ctx, variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="exec.CommandContext with variable command",
        cwe="CWE-78",
        negative_patterns=[r"exec\.CommandContext\s*\([^,]+,\s*\""],
    ),
])

# ==============================================================================
# C / C++
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="c-cmd-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bsystem\s*\(",
        function_name="system()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="system() executes shell command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="c-cmd-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bpopen\s*\(",
        function_name="popen()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="popen() executes shell command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="c-cmd-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bexec[lv]p?e?\s*\(",
        function_name="exec*()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="exec family -- process execution",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="c-cmd-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bposix_spawn\s*\(",
        function_name="posix_spawn()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="posix_spawn() -- process creation",
        cwe="CWE-78",
    ),
    # Radare2 specific (for r2mcp and similar)
    SinkPattern(
        id="c-cmd-010",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C],
        pattern=r"\br2_(?:core_)?cmd(?:_str)?\s*\(",
        function_name="r2_cmd()/r2_core_cmd()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="radare2 command execution",
        cwe="CWE-78",
        tags=["radare2", "r2mcp"],
    ),
    SinkPattern(
        id="c-cmd-011",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C],
        pattern=r"\br2pipe_cmd\s*\(",
        function_name="r2pipe_cmd()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="r2pipe command execution",
        cwe="CWE-78",
        tags=["radare2"],
    ),
    SinkPattern(
        id="c-cmd-012",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C],
        pattern=r"\br_core_cmd_str\s*\(",
        function_name="r_core_cmd_str()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="radare2 r_core_cmd_str() execute and return",
        cwe="CWE-78",
        tags=["radare2"],
    ),
    # Windows
    SinkPattern(
        id="c-cmd-020",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bCreateProcess[AW]?\s*\(",
        function_name="CreateProcess()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Windows CreateProcess",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="c-cmd-021",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bShellExecute[AW]?\s*\(",
        function_name="ShellExecute()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Windows ShellExecute",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="c-cmd-022",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bCreateProcessAsUser[AW]?\s*\(",
        function_name="CreateProcessAsUser()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Windows CreateProcessAsUser",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="c-cmd-023",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bWinExec\s*\(",
        function_name="WinExec()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="WinExec() -- deprecated but dangerous",
        cwe="CWE-78",
    ),
])

# ==============================================================================
# C# / .NET
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="cs-cmd-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.CSHARP],
        pattern=r"\bProcess\.Start\s*\(",
        function_name="Process.Start()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Process.Start() -- command execution",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="cs-cmd-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.CSHARP],
        pattern=r"\.Arguments\s*=\s*\$\"",
        function_name="ProcessStartInfo.Arguments (interpolated)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="ProcessStartInfo with interpolated arguments",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="cs-cmd-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.CSHARP],
        pattern=r"UseShellExecute\s*=\s*true",
        function_name="UseShellExecute = true",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Shell execution enabled",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="cs-cmd-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.CSHARP],
        pattern=r"\bPowerShell\.Create\s*\(\s*\)\.AddScript\s*\(",
        function_name="PowerShell.Create().AddScript()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PowerShell script execution via .NET",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="cs-cmd-005",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.CSHARP],
        pattern=r"\.FileName\s*=\s*[^\"@][^\n;]+;",
        function_name="ProcessStartInfo.FileName (variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="ProcessStartInfo FileName set from variable",
        cwe="CWE-78",
        negative_patterns=[r"\.FileName\s*=\s*[@\"]"],
    ),
])

# ==============================================================================
# RUST
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="rs-cmd-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUST],
        pattern=r"\bCommand::new\s*\(\s*[^\"'][^)]*\)",
        function_name="Command::new(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="std::process::Command with variable",
        cwe="CWE-78",
        negative_patterns=[r"Command::new\s*\(\s*\""],
    ),
    SinkPattern(
        id="rs-cmd-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUST],
        pattern=r"\bCommand::new\s*\(\s*[\"'](?:sh|bash|cmd|/bin/sh)[\"']\s*\)",
        function_name="Command::new('sh')",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Command invoking shell",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="rs-cmd-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUST],
        pattern=r"\.arg\s*\(\s*&?format!\s*\(",
        function_name=".arg(format!())",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Command argument with format! macro",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="rs-cmd-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUST],
        pattern=r"\btokio::process::Command::new\s*\(",
        function_name="tokio::process::Command::new()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Tokio async process Command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="rs-cmd-005",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUST],
        pattern=r"\.args\s*\(\s*&?\[.*format!\s*\(",
        function_name=".args([format!()])",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Command args array with format! macro",
        cwe="CWE-78",
    ),
])

PATTERN_COUNT = len(PATTERNS)
