import re
from mcpsec.static.patterns.base import SinkPattern, VulnType, Language, Severity, Confidence

PATTERNS = [
    SinkPattern(
        id="java-crypto-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.JAVA],
        pattern='MessageDigest\\.getInstance\\s*\\(\\s*"MD5"\\s*\\)',
        function_name='MessageDigest.getInstance("MD5")',
        confidence=Confidence.HIGH,
        description='MD5 hash via Java MessageDigest',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="java-crypto-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.JAVA],
        pattern='MessageDigest\\.getInstance\\s*\\(\\s*"SHA-1"\\s*\\)',
        function_name='MessageDigest.getInstance("SHA-1")',
        confidence=Confidence.HIGH,
        description='SHA-1 hash via Java MessageDigest',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="java-crypto-003",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.JAVA],
        pattern='Cipher\\.getInstance\\s*\\(\\s*"DES|Cipher\\.getInstance\\s*\\(\\s*"RC4|Cipher\\.getInstance\\s*\\(\\s*"RC2',
        function_name='Cipher.getInstance("DES/RC4/RC2")',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Broken cipher (DES/RC4/RC2) via Java Cipher',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="java-crypto-004",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.JAVA],
        pattern='Cipher\\.getInstance\\s*\\(\\s*"AES/ECB/',
        function_name='Cipher.getInstance("AES/ECB/...")',
        confidence=Confidence.HIGH,
        description='AES in ECB mode via Java Cipher',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="java-crypto-005",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.JAVA],
        pattern='new\\s+Random\\s*\\(\\s*\\)',
        function_name='new Random()',
        severity=Severity.MEDIUM,
        description='java.util.Random -- not cryptographically secure',
        cwe='CWE-338',
        remediation='Use java.security.SecureRandom',
    ),
    SinkPattern(
        id="c-crypto-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.C, Language.CPP],
        pattern='\\brand\\s*\\(\\s*\\)',
        function_name='rand()',
        severity=Severity.MEDIUM,
        description='C rand() -- not cryptographically secure PRNG',
        cwe='CWE-338',
    ),
    SinkPattern(
        id="c-crypto-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.C, Language.CPP],
        pattern='MD5_Init\\s*\\(',
        function_name='MD5_Init()',
        confidence=Confidence.HIGH,
        description='OpenSSL MD5 functions',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="c-crypto-003",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.C, Language.CPP],
        pattern='SHA1_Init\\s*\\(',
        function_name='SHA1_Init()',
        confidence=Confidence.HIGH,
        description='OpenSSL SHA1 functions',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="c-crypto-004",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.C, Language.CPP],
        pattern='DES_set_key\\s*\\(',
        function_name='DES_set_key()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='OpenSSL DES key setup -- broken cipher',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="c-crypto-005",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.C, Language.CPP],
        pattern='SSL_CTX_set_options\\s*\\([^)]*SSL_OP_NO_TLSv1_2',
        function_name='SSL_CTX_set_options(SSL_OP_NO_TLSv1_2)',
        confidence=Confidence.HIGH,
        description='Disabling TLS 1.2 support',
        cwe='CWE-326',
    ),
    SinkPattern(
        id="js-crypto-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='createHash\\s*\\(\\s*[\'\\"]md5[\'\\"]',
        function_name="createHash('md5')",
        confidence=Confidence.HIGH,
        description='MD5 hash -- cryptographically broken',
        cwe='CWE-327',
        remediation='Use SHA-256 or SHA-3 for integrity. Use bcrypt/argon2 for passwords.',
    ),
    SinkPattern(
        id="js-crypto-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='createHash\\s*\\(\\s*[\'\\"]sha1[\'\\"]',
        function_name="createHash('sha1')",
        confidence=Confidence.HIGH,
        description='SHA1 hash -- deprecated, collision attacks known',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="js-crypto-003",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='createCipheriv\\s*\\(\\s*[\'\\"](?:des|rc2|rc4|blowfish)[\'\\"]',
        function_name="createCipheriv('des/rc4')",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Broken cipher algorithm (DES/RC4/RC2/Blowfish)',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="js-crypto-004",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='createCipheriv\\s*\\(\\s*[\'\\"]aes-\\d+-ecb[\'\\"]',
        function_name="createCipheriv('aes-XXX-ecb')",
        confidence=Confidence.HIGH,
        description='AES in ECB mode -- deterministic, patterns visible',
        cwe='CWE-327',
        remediation='Use AES-GCM or AES-CBC with random IV',
    ),
    SinkPattern(
        id="js-crypto-005",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='\\bMath\\.random\\s*\\(\\s*\\)',
        function_name='Math.random()',
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description='Math.random() -- not cryptographically secure',
        cwe='CWE-338',
        remediation='Use crypto.getRandomValues() or crypto.randomBytes()',
    ),
    SinkPattern(
        id="js-crypto-006",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='crypto\\.createHash\\s*\\(\\s*[\'\\"]md4[\'\\"]',
        function_name="createHash('md4')",
        confidence=Confidence.HIGH,
        description='MD4 hash -- extremely weak',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="js-crypto-007",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='process\\.env\\.\\w+\\s*\\|\\|\\s*[\'\\"][a-zA-Z0-9+/=_\\-]{16,}[\'\\"]',
        function_name="process.env.SECRET || 'hardcoded'",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Hardcoded secret fallback -- insecure default',
        cwe='CWE-798',
    ),
    SinkPattern(
        id="py-crypto-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='\\bhashlib\\.md5\\s*\\(',
        function_name='hashlib.md5()',
        confidence=Confidence.HIGH,
        description='MD5 hash -- cryptographically broken',
        cwe='CWE-327',
        remediation='Use hashlib.sha256() or hashlib.sha3_256()',
    ),
    SinkPattern(
        id="py-crypto-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='\\bhashlib\\.sha1\\s*\\(',
        function_name='hashlib.sha1()',
        confidence=Confidence.HIGH,
        description='SHA1 hash -- deprecated for security use',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="py-crypto-003",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='\\bDES\\b|\\bDES3\\b|\\bARC4\\b|\\bBlowfish\\b',
        function_name='DES/DES3/RC4/Blowfish',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Broken cipher (DES/RC4/Blowfish) from pycryptodome',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="py-crypto-004",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='AES\\.MODE_ECB',
        function_name='AES.MODE_ECB',
        confidence=Confidence.HIGH,
        description='AES in ECB mode -- deterministic encryption',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="py-crypto-005",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='\\brandom\\.(?:random|randint|choice|seed)\\s*\\(',
        function_name='random.random()',
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description='Python random module -- not cryptographically secure',
        cwe='CWE-338',
        remediation='Use secrets module or os.urandom() for security purposes',
    ),
    SinkPattern(
        id="py-crypto-006",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='\\bos\\.urandom\\s*\\(\\s*[1-9]\\b',
        function_name='os.urandom(small_n)',
        severity=Severity.MEDIUM,
        description='os.urandom() with too few bytes -- insufficient entropy',
        cwe='CWE-331',
    ),
    SinkPattern(
        id="py-crypto-007",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='\\bRSA\\.generate\\s*\\(\\s*(?:512|768|1024)\\b',
        function_name='RSA.generate(< 2048)',
        confidence=Confidence.HIGH,
        description='RSA key size < 2048 bits -- factoring attacks feasible',
        cwe='CWE-326',
    ),
    SinkPattern(
        id="go-crypto-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern='\\bmd5\\.New\\s*\\(\\s*\\)',
        function_name='md5.New()',
        confidence=Confidence.HIGH,
        description='MD5 hash usage',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="go-crypto-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern='\\bsha1\\.New\\s*\\(\\s*\\)',
        function_name='sha1.New()',
        confidence=Confidence.HIGH,
        description='SHA1 hash usage',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="go-crypto-003",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern='\\bdes\\.NewCipher\\s*\\(',
        function_name='des.NewCipher()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='DES cipher -- cryptographically broken',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="go-crypto-004",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern='\\brc4\\.NewCipher\\s*\\(',
        function_name='rc4.NewCipher()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='RC4 cipher -- broken',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="go-crypto-005",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern='\\bcipher\\.NewECBEncrypter\\b|\\bNewECBDecrypter\\b',
        function_name='ECB mode cipher',
        confidence=Confidence.HIGH,
        description='ECB mode cipher -- non-standard Go, look for third-party',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="go-crypto-006",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern='\\bmath/rand\\b',
        function_name='math/rand',
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description='math/rand import -- not cryptographically secure',
        cwe='CWE-338',
        remediation='Use crypto/rand for security-sensitive operations',
    ),
    SinkPattern(
        id="go-crypto-007",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern='InsecureSkipVerify\\s*:\\s*true',
        function_name='InsecureSkipVerify: true',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='TLS certificate verification disabled',
        cwe='CWE-295',
    ),
    SinkPattern(
        id="all-crypto-hc-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT, Language.PYTHON, Language.GO, Language.RUST],
        pattern='(?i)(?:password|passwd|secret|api_key|apikey|private_key|access_token|auth_token)\\s*[=:]\\s*[\'\\"][a-zA-Z0-9!@#$%^&*_\\-+=]{12,}[\'\\"]',
        function_name='hardcoded credential',
        severity=Severity.CRITICAL,
        description='Hardcoded credential/secret value',
        cwe='CWE-798',
        remediation='Use environment variables or a secrets manager',
        negative_patterns=['(?i)example|placeholder|changeme|your_|my_|insert|REPLACE', '(?i)test|spec|dummy|fake|mock'],
    ),
    SinkPattern(
        id="all-crypto-hc-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT, Language.PYTHON, Language.GO],
        pattern='(?i)jwt.*secret.*=.*[\'\\"][a-zA-Z0-9_\\-]{10,}[\'\\"]',
        function_name='hardcoded JWT secret',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Hardcoded JWT signing secret',
        cwe='CWE-798',
    ),
    SinkPattern(
        id="js-jwt-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='jwt\\.verify\\s*\\([^)]*algorithms\\s*:\\s*\\[[^\\]]*none',
        function_name='jwt.verify(algorithms:[none])',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="JWT verify allows 'none' algorithm -- algorithm confusion",
        cwe='CWE-327',
        tags=['jwt'],
    ),
    SinkPattern(
        id="js-jwt-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='jwt\\.decode\\s*\\([^)]*(?!verify)[^)]*\\)',
        function_name='jwt.decode() without verify',
        description="jwt.decode without signature verification -- trust but don't verify",
        cwe='CWE-347',
        negative_patterns=['jwt\\.verify'],
    ),
    SinkPattern(
        id="py-jwt-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='jwt\\.decode\\s*\\([^)]*options\\s*=\\s*\\{[^}]*verify_signature\\s*:\\s*False',
        function_name='jwt.decode(verify_signature=False)',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='PyJWT decode with signature verification disabled',
        cwe='CWE-347',
    ),
    SinkPattern(
        id="py-jwt-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='jwt\\.decode\\s*\\([^)]*algorithms\\s*=\\s*\\[[^\\]]*none',
        function_name="jwt.decode(algorithms=['none'])",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PyJWT allows 'none' algorithm",
        cwe='CWE-327',
    ),
    SinkPattern(
        id="py-tls-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='ssl\\.PROTOCOL_SSLv2\\b|ssl\\.PROTOCOL_SSLv3\\b|ssl\\.PROTOCOL_TLSv1\\b',
        function_name='ssl.PROTOCOL_SSLv2/3/TLSv1',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Deprecated SSL/TLS protocol version',
        cwe='CWE-326',
        remediation='Use ssl.PROTOCOL_TLS_CLIENT with ssl.TLSVersion.TLSv1_2 minimum',
    ),
    SinkPattern(
        id="py-tls-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='verify\\s*=\\s*False',
        function_name='verify=False',
        severity=Severity.CRITICAL,
        description='TLS verification disabled in requests/httpx',
        cwe='CWE-295',
        context_patterns=['requests\\.|httpx\\.'],
    ),
    SinkPattern(
        id="js-tls-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='rejectUnauthorized\\s*:\\s*false',
        function_name='rejectUnauthorized: false',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='TLS certificate validation disabled in Node.js HTTPS',
        cwe='CWE-295',
    ),
    SinkPattern(
        id="js-tls-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='NODE_TLS_REJECT_UNAUTHORIZED\\s*=\\s*[\'\\"]0[\'\\"]',
        function_name='NODE_TLS_REJECT_UNAUTHORIZED=0',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='TLS verification disabled via environment variable',
        cwe='CWE-295',
    ),
    SinkPattern(
        id="js-crypto-extra-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='createCipheriv\\s*\\(\\s*[\'\\"]aes-128-',
        function_name="createCipheriv('aes-128-*')",
        severity=Severity.MEDIUM,
        description='AES-128 -- weaker than AES-256, prefer 256-bit keys',
        cwe='CWE-326',
    ),
    SinkPattern(
        id="js-crypto-extra-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='\\.generateKeyPairSync\\s*\\(\\s*[\'\\"]rsa[\'\\"],\\s*\\{[^}]*modulusLength\\s*:\\s*(?:512|768|1024)\\b',
        function_name='generateKeyPairSync(rsa, {modulusLength: <2048})',
        confidence=Confidence.HIGH,
        description='RSA key generation < 2048 bits',
        cwe='CWE-326',
    ),
    SinkPattern(
        id="py-crypto-extra-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='Fernet\\s*\\(\\s*[\'\\"][a-zA-Z0-9+/=]{43,}[\'\\"]',
        function_name='Fernet(hardcoded_key)',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Hardcoded Fernet key',
        cwe='CWE-798',
    ),
    SinkPattern(
        id="py-crypto-extra-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='SECRET_KEY\\s*=\\s*[\'\\"][a-zA-Z0-9!@#$%^&*_\\-+=]{16,}[\'\\"]',
        function_name="SECRET_KEY = 'hardcoded'",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Hardcoded Django/Flask SECRET_KEY',
        cwe='CWE-798',
        negative_patterns=['(?i)example|changeme|replace|your_secret|os\\.environ'],
    ),
    SinkPattern(
        id="go-crypto-extra-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern='rsa\\.GenerateKey\\s*\\([^,]+,\\s*(?:512|768|1024)\\s*\\)',
        function_name='rsa.GenerateKey(rand, <2048)',
        confidence=Confidence.HIGH,
        description='RSA key generation < 2048 bits in Go',
        cwe='CWE-326',
    ),
    SinkPattern(
        id="go-crypto-extra-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern='ecdsa\\.GenerateKey\\s*\\(\\s*elliptic\\.P224',
        function_name='ecdsa.GenerateKey(P-224)',
        confidence=Confidence.HIGH,
        description='ECDSA with P-224 curve -- weak, prefer P-256/P-384',
        cwe='CWE-326',
    ),
    SinkPattern(
        id="js-crypto-hw-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='crypto\\.createCipher\\s*\\(',
        function_name='crypto.createCipher() -- deprecated',
        confidence=Confidence.HIGH,
        description='Node.js crypto.createCipher -- deprecated, uses null IV',
        cwe='CWE-327',
        tags=['deprecated'],
    ),
    SinkPattern(
        id="js-crypto-hw-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='createHmac\\s*\\(\\s*[\'\\"]md5[\'\\"]',
        function_name="createHmac('md5')",
        confidence=Confidence.HIGH,
        description='HMAC with MD5 -- weak hash',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="js-crypto-hw-003",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='createHmac\\s*\\(\\s*[\'\\"]sha1[\'\\"]',
        function_name="createHmac('sha1')",
        confidence=Confidence.HIGH,
        description='HMAC with SHA-1 -- weak hash',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="py-crypto-hw-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='SSL_PROTOCOL_SSLv2|SSLContext.*PROTOCOL_SSLv2',
        function_name='SSLv2 protocol',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='SSLv2 protocol -- critically vulnerable',
        cwe='CWE-326',
    ),
    SinkPattern(
        id="py-crypto-hw-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='hmac\\.new\\s*\\([^,]+,\\s*[^,]+,\\s*hashlib\\.md5\\s*\\)',
        function_name='hmac.new(key, msg, md5)',
        confidence=Confidence.HIGH,
        description='HMAC with MD5',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="go-crypto-hw-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern='hmac\\.New\\s*\\(\\s*md5\\.New\\b',
        function_name='hmac.New(md5.New)',
        confidence=Confidence.HIGH,
        description='HMAC with MD5',
        cwe='CWE-327',
    ),
    SinkPattern(
        id="go-crypto-hw-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern='\\btls\\.Config\\s*\\{[^}]*MaxVersion\\s*:\\s*tls\\.VersionTLS10\\b',
        function_name='tls.Config{MaxVersion: TLS1.0}',
        confidence=Confidence.HIGH,
        description='TLS max version set to TLS 1.0 -- weak',
        cwe='CWE-326',
    ),
    SinkPattern(
        id="go-crypto-hw-003",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern='rand\\.Read\\s*\\((?!.*crypto/rand)',
        function_name='rand.Read (math/rand)',
        severity=Severity.MEDIUM,
        description='Non-crypto rand.Read',
        cwe='CWE-338',
    ),
    SinkPattern(
        id="js-jwt-001_2",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='jwt\\.sign\\s*\\([^,]+,\\s*[\'\\"][^\'\\"]{1,15}[\'\\"]',
        function_name='jwt.sign(payload, short_secret)',
        confidence=Confidence.HIGH,
        description='JWT signed with short/weak secret',
        cwe='CWE-326',
    ),
    SinkPattern(
        id="js-jwt-002_2",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='jwt\\.sign\\s*\\([^,]+,\\s*[\'\\"][\'\\"]',
        function_name="jwt.sign(payload, '')",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='JWT signed with empty secret',
        cwe='CWE-326',
    ),
    SinkPattern(
        id="js-jwt-003",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='jwt\\.verify\\s*\\([^,]+,\\s*[^,)]*algorithm.*none',
        function_name='jwt.verify(token, ..., {algorithm: none})',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="JWT verify with 'none' algorithm -- authentication bypass",
        cwe='CWE-327',
        tags=['known-vuln'],
    ),
    SinkPattern(
        id="py-jwt-001_2",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='jwt\\.decode\\s*\\([^,]+,\\s*[^,]+,\\s*algorithms\\s*=\\s*\\[\\s*[\'\\"]none[\'\\"]\\s*\\]',
        function_name="jwt.decode(token, ..., algorithms=['none'])",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PyJWT decode with 'none' algorithm",
        cwe='CWE-327',
    ),
    SinkPattern(
        id="py-jwt-002_2",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern='jwt\\.decode\\s*\\([^,]+,\\s*options\\s*=\\s*\\{[^}]*verify_signature\\s*:\\s*False',
        function_name='jwt.decode(verify_signature=False)',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='PyJWT disabled signature verification',
        cwe='CWE-347',
    )
]

