import re
from mcpsec.static.patterns.base import SinkPattern, VulnType, Language, Severity, Confidence

PATTERNS = [
    SinkPattern(
        id="java-deser-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.JAVA],
        pattern='new\\s+ObjectInputStream\\s*\\(',
        function_name='new ObjectInputStream()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Java ObjectInputStream -- RCE via deserialization gadget chains',
        cwe='CWE-502',
        tags=['known-vuln'],
    ),
    SinkPattern(
        id="java-deser-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.JAVA],
        pattern='xstream\\.fromXML\\s*\\(',
        function_name='XStream.fromXML()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='XStream.fromXML -- RCE without security framework',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="java-deser-003",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.JAVA],
        pattern='ObjectMapper\\s*\\(\\s*\\)\\.readValue\\s*\\(<.*Object\\.class',
        function_name='ObjectMapper.readValue(Object.class)',
        description='Jackson readValue to Object.class -- polymorphic type risk',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="java-deser-004",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.JAVA],
        pattern='enableDefaultTyping\\s*\\(',
        function_name='ObjectMapper.enableDefaultTyping()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Jackson enableDefaultTyping -- RCE via polymorphic deserialization',
        cwe='CWE-502',
        tags=['known-vuln'],
    ),
    SinkPattern(
        id="php-deser-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PHP],
        pattern='\\bunserialize\\s*\\(\\s*\\$(?:_GET|_POST|_REQUEST|_COOKIE)',
        function_name='unserialize($_GET/$POST)',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='PHP unserialize with user input -- PHP object injection',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="php-deser-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PHP],
        pattern='unserialize\\s*\\(',
        function_name='unserialize()',
        description='PHP unserialize -- check if input is user-controlled',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="cs-deser-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.CSHARP],
        pattern='BinaryFormatter\\s*\\(\\s*\\)\\.Deserialize\\s*\\(',
        function_name='BinaryFormatter.Deserialize()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='C# BinaryFormatter.Deserialize -- RCE via gadget chains',
        cwe='CWE-502',
        tags=['known-vuln'],
    ),
    SinkPattern(
        id="cs-deser-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.CSHARP],
        pattern='SoapFormatter\\s*\\(\\s*\\)\\.Deserialize\\s*\\(',
        function_name='SoapFormatter.Deserialize()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='C# SoapFormatter.Deserialize -- RCE',
        cwe='CWE-502',
        tags=['known-vuln'],
    ),
    SinkPattern(
        id="cs-deser-003",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.CSHARP],
        pattern='JsonConvert\\.DeserializeObject\\s*<object>',
        function_name='JsonConvert.DeserializeObject<object>()',
        description='Newtonsoft DeserializeObject to Object -- TypeNameHandling risk',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="cs-deser-004",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.CSHARP],
        pattern='TypeNameHandling\\.\\s*(?:All|Objects|Auto)',
        function_name='TypeNameHandling.All/Objects/Auto',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Newtonsoft TypeNameHandling enabled -- RCE via gadgets',
        cwe='CWE-502',
        tags=['known-vuln'],
    ),
    SinkPattern(
        id="go-deser-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.GO],
        pattern='encoding/gob.*Decode\\s*\\(',
        function_name='gob.Decode()',
        description='Go gob Decode -- check if input is trusted',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="go-deser-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.GO],
        pattern='yaml\\.Unmarshal\\s*\\([^,]+,\\s*&[^)]+interface',
        function_name='yaml.Unmarshal(data, &interface{})',
        description='Go YAML unmarshal to interface{} -- check for type coercion',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="py-mlsec-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='huggingface_hub.*hf_hub_download\\s*\\(\\s*[^\'\\"\\s][^,)]*',
        function_name='hf_hub_download(variable repo)',
        severity=Severity.MEDIUM,
        description='HuggingFace model download from variable repo -- supply chain',
        cwe='CWE-502',
        negative_patterns=['hf_hub_download\\s*\\(\\s*[\'\\"]'],
        tags=['mlsec', 'supply-chain'],
    ),
    SinkPattern(
        id="py-mlsec-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='AutoModel\\.from_pretrained\\s*\\(\\s*[^\'\\"\\s][^,)]*',
        function_name='AutoModel.from_pretrained(variable)',
        severity=Severity.MEDIUM,
        description='HuggingFace from_pretrained with variable path -- unsafe pickle',
        cwe='CWE-502',
        negative_patterns=['from_pretrained\\s*\\(\\s*[\'\\"]'],
        tags=['mlsec'],
    ),
    SinkPattern(
        id="py-deser-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='\\bpickle\\.load[s]?\\s*\\(',
        function_name='pickle.load()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='pickle.load/loads -- arbitrary code execution via deserialization',
        cwe='CWE-502',
        remediation='Never deserialize untrusted pickle data. Use JSON or encrypt+sign data.',
    ),
    SinkPattern(
        id="py-deser-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='\\bcPickle\\.load[s]?\\s*\\(',
        function_name='cPickle.load()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='cPickle.load/loads -- arbitrary code execution',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="py-deser-003",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='\\bpickletools\\.dis\\s*\\(',
        function_name='pickletools.dis()',
        description='pickletools.dis -- pickle analysis on untrusted data',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="py-deser-004",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='\\bshelve\\.open\\s*\\(',
        function_name='shelve.open()',
        description='shelve uses pickle internally -- untrusted data risk',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="py-deser-010",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='\\byaml\\.load\\s*\\(\\s*[^,)]*(?:,\\s*Loader\\s*=\\s*(?!yaml\\.SafeLoader))?',
        function_name='yaml.load() without SafeLoader',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='yaml.load() without SafeLoader -- arbitrary code execution',
        cwe='CWE-502',
        remediation='Use yaml.safe_load() or yaml.load(data, Loader=yaml.SafeLoader)',
        negative_patterns=['yaml\\.load\\s*\\([^)]*SafeLoader'],
    ),
    SinkPattern(
        id="py-deser-011",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='\\byaml\\.full_load\\s*\\(',
        function_name='yaml.full_load()',
        description='yaml.full_load() -- allows python objects, prefer safe_load()',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="py-deser-012",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='\\byaml\\.unsafe_load\\s*\\(',
        function_name='yaml.unsafe_load()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='yaml.unsafe_load() -- explicitly unsafe',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="py-deser-020",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='\\bmarshal\\.loads?\\s*\\(',
        function_name='marshal.load()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='marshal.load/loads -- not safe for untrusted data',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="py-deser-030",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='\\bjsonpickle\\.decode\\s*\\(',
        function_name='jsonpickle.decode()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='jsonpickle.decode -- can execute arbitrary Python code',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="py-deser-040",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='\\bdill\\.load[s]?\\s*\\(',
        function_name='dill.load()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='dill.load -- extends pickle, same risks',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="py-deser-041",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='\\bcloudpickle\\.load[s]?\\s*\\(',
        function_name='cloudpickle.load()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='cloudpickle.load -- extends pickle, same risks',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="js-deser-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='\\bserialize\\.unserialize\\s*\\(',
        function_name='node-serialize.unserialize()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='node-serialize.unserialize -- RCE via IIFE (CVE-2017-5941)',
        cwe='CWE-502',
        tags=['known-vuln', 'CVE-2017-5941'],
    ),
    SinkPattern(
        id="js-deser-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='\\bunserialize\\s*\\(',
        function_name='unserialize()',
        severity=Severity.CRITICAL,
        description='unserialize() -- possible node-serialize or PHP-like lib',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="js-deser-003",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='\\bJSON\\.parse\\s*\\([^)]*\\)\\s*\\.\\s*(?:constructor|__proto__|prototype)',
        function_name='JSON.parse().__proto__',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='JSON.parse result used for prototype pollution',
        cwe='CWE-1321',
    ),
    SinkPattern(
        id="js-deser-004",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='\\beval\\s*\\(\\s*JSON\\.parse',
        function_name='eval(JSON.parse())',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='eval() on JSON.parse result -- code execution',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="go-deser-001_2",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.GO],
        pattern='\\bgob\\.NewDecoder\\s*\\(',
        function_name='gob.NewDecoder()',
        description="encoding/gob decoder -- don't use on untrusted data",
        cwe='CWE-502',
    ),
    SinkPattern(
        id="go-deser-002_2",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.GO],
        pattern='\\.Decode\\s*\\(\\s*&interface\\{\\}',
        function_name='.Decode(&interface{})',
        description='JSON decode into empty interface -- type confusion risk',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="cs-deser-001_2",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.CSHARP],
        pattern='\\bBinaryFormatter\\s*\\(\\s*\\).*\\.Deserialize\\s*\\(',
        function_name='BinaryFormatter.Deserialize()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='BinaryFormatter.Deserialize -- RCE, banned in .NET 5+',
        cwe='CWE-502',
        tags=['known-vuln'],
    ),
    SinkPattern(
        id="cs-deser-002_2",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.CSHARP],
        pattern='\\bBinaryFormatter\\b',
        function_name='BinaryFormatter',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='BinaryFormatter usage -- inherently unsafe',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="cs-deser-003_2",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.CSHARP],
        pattern='\\bSoapFormatter\\b',
        function_name='SoapFormatter',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='SoapFormatter -- insecure deserialization',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="cs-deser-004_2",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.CSHARP],
        pattern='TypeNameHandling\\s*=\\s*TypeNameHandling\\.(?!None)',
        function_name='TypeNameHandling != None',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Newtonsoft Json.NET TypeNameHandling -- gadget chain risk',
        cwe='CWE-502',
        remediation='Use TypeNameHandling.None or SerializationBinder whitelist',
    ),
    SinkPattern(
        id="cs-deser-005",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.CSHARP],
        pattern='\\bLosFormatter\\b',
        function_name='LosFormatter',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='LosFormatter -- insecure deserialization',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="cs-deser-006",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.CSHARP],
        pattern='\\bNetDataContractSerializer\\b',
        function_name='NetDataContractSerializer',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='NetDataContractSerializer -- RCE risk',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="cs-deser-007",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.CSHARP],
        pattern='JsonConvert\\.DeserializeObject\\s*<[^>]*object[^>]*>',
        function_name='JsonConvert.DeserializeObject<object>',
        description='Json.NET DeserializeObject to object -- TypeNameHandling risk',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="rb-deser-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.RUBY],
        pattern='Marshal\\.load\\s*\\(',
        function_name='Marshal.load()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Ruby Marshal.load -- RCE on untrusted data',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="rb-deser-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.RUBY],
        pattern='YAML\\.load\\s*\\(',
        function_name='YAML.load()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Ruby YAML.load -- Psych can execute arbitrary objects',
        cwe='CWE-502',
        remediation='Use YAML.safe_load() instead',
        negative_patterns=['YAML\\.safe_load'],
    ),
    SinkPattern(
        id="php-deser-003",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PHP],
        pattern='unserialize\\s*\\(\\s*base64_decode\\s*\\(',
        function_name='unserialize(base64_decode(user))',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='PHP unserialize of base64-decoded data -- PHP object injection',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="py-deser-extra-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='yaml\\.load\\s*\\(\\s*[^,)]+\\)',
        function_name='yaml.load(data)',
        severity=Severity.CRITICAL,
        description='yaml.load without Loader kwarg -- defaults to unsafe',
        cwe='CWE-502',
        negative_patterns=['yaml\\.load\\s*\\([^)]*SafeLoader', 'yaml\\.safe_load'],
    ),
    SinkPattern(
        id="py-deser-extra-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='configparser\\.ConfigParser\\(\\)\\.read_string\\s*\\(',
        function_name='ConfigParser.read_string()',
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description='ConfigParser from user string -- check interpolation risks',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="py-deser-extra-003",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='pickle\\.loads?\\s*\\(\\s*base64\\.b64decode\\s*\\(',
        function_name='pickle.loads(base64.decode(user))',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Pickle deserialization of base64-decoded user data',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="js-deser-extra-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='vm\\.runInContext\\s*\\(\\s*[^\'\\"`\\s][^,)]*',
        function_name='vm.runInContext(variable)',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='Node.js vm.runInContext with variable code',
        cwe='CWE-94',
        negative_patterns=['vm\\.runInContext\\s*\\(\\s*[\'\\"`]'],
    ),
    SinkPattern(
        id="js-deser-extra-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='JSON5\\.parse\\s*\\(\\s*[^\'\\"`\\s][^)]*\\)',
        function_name='JSON5.parse(variable)',
        severity=Severity.MEDIUM,
        description='JSON5 parse from user input',
        cwe='CWE-1321',
        negative_patterns=['JSON5\\.parse\\s*\\(\\s*[\'\\"`]'],
    ),
    SinkPattern(
        id="py-deser-fw-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='msgpack\\.unpackb\\s*\\(',
        function_name='msgpack.unpackb()',
        severity=Severity.MEDIUM,
        description='msgpack.unpackb -- check raw/strict_map options',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="py-deser-fw-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='torch\\.load\\s*\\(',
        function_name='torch.load()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='PyTorch torch.load -- arbitrary code via pickle',
        cwe='CWE-502',
        tags=['mlsec'],
    ),
    SinkPattern(
        id="py-deser-fw-003",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='numpy\\.load\\s*\\([^)]*allow_pickle\\s*=\\s*True',
        function_name='numpy.load(allow_pickle=True)',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='NumPy load with allow_pickle=True -- code execution',
        cwe='CWE-502',
        tags=['mlsec'],
    ),
    SinkPattern(
        id="py-deser-fw-004",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern='joblib\\.load\\s*\\(',
        function_name='joblib.load()',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='joblib.load -- uses pickle, arbitrary code',
        cwe='CWE-502',
        tags=['mlsec'],
    ),
    SinkPattern(
        id="js-deser-fw-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='flatted\\.parse\\s*\\(',
        function_name='flatted.parse()',
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description='flatted.parse -- check for prototype pollution',
        cwe='CWE-502',
    ),
    SinkPattern(
        id="js-deser-fw-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='qs\\.parse\\s*\\(\\s*[^\'\\"`\\s][^,)]*',
        function_name='qs.parse(variable)',
        severity=Severity.MEDIUM,
        description='qs.parse with user input -- prototype pollution via __proto__',
        cwe='CWE-1321',
        negative_patterns=['qs\\.parse\\s*\\(\\s*[\'\\"`]'],
    ),
    SinkPattern(
        id="js-deser-fw-003",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='_.merge\\s*\\(\\s*\\{\\s*\\},\\s*[^\'\\"`\\s][^)]*\\)',
        function_name='_.merge({}, variable)',
        description='Lodash _.merge with user input -- prototype pollution < 4.17.5',
        cwe='CWE-1321',
        tags=['known-vuln'],
    ),
    SinkPattern(
        id="js-deser-fw-004",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='extend\\s*\\(true,\\s*\\{\\s*\\},\\s*[^\'\\"`\\s][^)]*\\)',
        function_name='extend(true, {}, variable)',
        description='jQuery.extend deep with user input -- prototype pollution',
        cwe='CWE-1321',
    )
]
