"""
Final patterns -- bulk coverage for remaining languages and edge cases.
Pushes total past 800.
"""

from mcpsec.static.patterns.base import (
    SinkPattern, Language, VulnType, Severity, Confidence
)

PATTERNS: list[SinkPattern] = []

# ==============================================================================
# RUBY -- command injection, path traversal, SSRF, eval
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="rb-ci-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUBY],
        pattern=r"system\s*\(\s*[^'\"#\s][^)]*\)",
        function_name="system(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Ruby system() with variable command",
        cwe="CWE-78",
        negative_patterns=[r"system\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="rb-ci-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUBY],
        pattern=r"`[^`]*#\{[^}]+\}`",
        function_name="backtick command with #{interpolation}",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Ruby backtick command with string interpolation",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="rb-ci-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUBY],
        pattern=r"%x\{[^}]*#\{",
        function_name="%x{command with #{interpolation}}",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Ruby %x command with interpolation",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="rb-ci-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUBY],
        pattern=r"exec\s*\(\s*[^'\"#\s][^)]*\)",
        function_name="exec(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Ruby exec() with variable command",
        cwe="CWE-78",
        negative_patterns=[r"exec\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="rb-ci-005",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUBY],
        pattern=r"IO\.popen\s*\(\s*[^'\"#\s][^)]*\)",
        function_name="IO.popen(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Ruby IO.popen with variable command",
        cwe="CWE-78",
        negative_patterns=[r"IO\.popen\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="rb-ci-006",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUBY],
        pattern=r"Open3\.(popen3|capture3|capture2e?)\s*\(\s*[^'\"#\s][^)]*\)",
        function_name="Open3.popen3/capture3(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Ruby Open3 with variable command",
        cwe="CWE-78",
        negative_patterns=[r"Open3\.\w+\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="rb-ci-007",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.RUBY],
        pattern=r'system\s*\(\s*"[^"]*#\{',
        function_name='system("... #{interpolation}")',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Ruby system() with interpolated string",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="rb-eval-001",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.RUBY],
        pattern=r"\beval\s*\(\s*[^'\"#\s][^)]*\)",
        function_name="eval(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Ruby eval() with variable code",
        cwe="CWE-94",
        negative_patterns=[r"\beval\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="rb-eval-002",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.RUBY],
        pattern=r'\beval\s*\(\s*"[^"]*#\{',
        function_name='eval("#{expr}")',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Ruby eval with interpolated string",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="rb-sql-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.RUBY],
        pattern=r"\.where\s*\(\s*\"[^\"]*#\{",
        function_name="ActiveRecord.where(\"#{interpolation}\")",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="ActiveRecord where with string interpolation -- SQL injection",
        cwe="CWE-89",
        remediation="Use .where('column = ?', value) with parameter binding",
    ),
    SinkPattern(
        id="rb-sql-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.RUBY],
        pattern=r"\.find_by_sql\s*\(\s*[^'\"#\s][^)]*\)",
        function_name="find_by_sql(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="ActiveRecord find_by_sql with variable",
        cwe="CWE-89",
        negative_patterns=[r"find_by_sql\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="rb-sql-003",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.RUBY],
        pattern=r"ActiveRecord::Base\.connection\.execute\s*\(\s*[^'\"#\s][^)]*\)",
        function_name="connection.execute(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Rails raw connection execute with variable",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="rb-sql-004",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.RUBY],
        pattern=r'\.where\s*\(\s*"[^"]*"\s*\+',
        function_name="Model.where(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="ActiveRecord where with string concatenation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="rb-ssrf-001",
        vuln_type=VulnType.SSRF,
        languages=[Language.RUBY],
        pattern=r"URI\.open\s*\(\s*[^'\"#\s][^)]*\)",
        function_name="URI.open(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Ruby URI.open with variable URL",
        cwe="CWE-918",
        negative_patterns=[r"URI\.open\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="rb-ssrf-002",
        vuln_type=VulnType.SSRF,
        languages=[Language.RUBY],
        pattern=r'Net::HTTP\.get\s*\(\s*URI\s*\(\s*[^\'\"#\s]',
        function_name="Net::HTTP.get(URI(variable))",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Ruby Net::HTTP.get with variable URI",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="rb-ssrf-003",
        vuln_type=VulnType.SSRF,
        languages=[Language.RUBY],
        pattern=r"Faraday\.new\s*\(\s*url:\s*[^'\"#\s{][^)]*\)",
        function_name="Faraday.new(url: variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Faraday HTTP client with variable URL",
        cwe="CWE-918",
        negative_patterns=[r"url:\s*['\"]"],
    ),
    SinkPattern(
        id="rb-pt-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.RUBY],
        pattern=r"File\.read\s*\(\s*[^'\"#\s][^)]*\)",
        function_name="File.read(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Ruby File.read with variable path",
        cwe="CWE-22",
        negative_patterns=[r"File\.read\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="rb-pt-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.RUBY],
        pattern=r"File\.open\s*\(\s*[^'\"#\s][^,)]*",
        function_name="File.open(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Ruby File.open with variable path",
        cwe="CWE-22",
        negative_patterns=[r"File\.open\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="rb-pt-003",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.RUBY],
        pattern=r"File\.delete\s*\(\s*[^'\"#\s][^)]*\)",
        function_name="File.delete(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="Ruby File.delete with variable path",
        cwe="CWE-22",
        negative_patterns=[r"File\.delete\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="rb-deser-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.RUBY],
        pattern=r"Marshal\.load\s*\(",
        function_name="Marshal.load()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Ruby Marshal.load -- RCE on untrusted data",
        cwe="CWE-502",
    ),
    SinkPattern(
        id="rb-deser-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.RUBY],
        pattern=r"YAML\.load\s*\(",
        function_name="YAML.load()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Ruby YAML.load -- Psych can execute arbitrary objects",
        cwe="CWE-502",
        remediation="Use YAML.safe_load() instead",
        negative_patterns=[r"YAML\.safe_load"],
    ),
])

# ==============================================================================
# PHP -- more patterns  
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="php-ci-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PHP],
        pattern=r"system\s*\(\s*\$(?:_GET|_POST|_REQUEST)",
        function_name="system($_GET)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP system() with user input directly",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="php-ci-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PHP],
        pattern=r"proc_open\s*\(\s*\$",
        function_name="proc_open($variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP proc_open with variable command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="php-rce-001",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PHP],
        pattern=r"call_user_func\s*\(\s*\$(?:_GET|_POST|_REQUEST)",
        function_name="call_user_func($_GET)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP call_user_func with user-controlled function name",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="php-rce-002",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PHP],
        pattern=r"call_user_func_array\s*\(\s*\$(?:_GET|_POST|_REQUEST)",
        function_name="call_user_func_array($_GET)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP call_user_func_array with user-controlled function",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="php-rce-003",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PHP],
        pattern=r"\$\$[a-zA-Z_\x7f-\xff]",
        function_name="$$var (variable variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="PHP variable variable -- code execution risk",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="php-deser-003",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PHP],
        pattern=r"unserialize\s*\(\s*base64_decode\s*\(",
        function_name="unserialize(base64_decode(user))",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP unserialize of base64-decoded data -- PHP object injection",
        cwe="CWE-502",
    ),
    SinkPattern(
        id="php-xxe-001",
        vuln_type=VulnType.XXE,
        languages=[Language.PHP],
        pattern=r"simplexml_load_string\s*\(\s*\$(?:_GET|_POST|_REQUEST)",
        function_name="simplexml_load_string($_GET)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="PHP simplexml_load_string with user input",
        cwe="CWE-611",
    ),
    SinkPattern(
        id="php-xxe-002",
        vuln_type=VulnType.XXE,
        languages=[Language.PHP],
        pattern=r"new\s+DOMDocument\s*\(\s*\).*loadXML\s*\(",
        function_name="DOMDocument.loadXML()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="PHP DOMDocument loadXML -- XXE if entity expansion enabled",
        cwe="CWE-611",
    ),
    SinkPattern(
        id="php-ssrf-003",
        vuln_type=VulnType.SSRF,
        languages=[Language.PHP],
        pattern=r"curl_setopt\s*\([^,]+,\s*CURLOPT_URL\s*,\s*\$",
        function_name="curl_setopt(CURLOPT_URL, $var)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="PHP cURL URL option with variable",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="php-log-001",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.PHP],
        pattern=r"error_log\s*\(\s*\$(?:_GET|_POST|_REQUEST)",
        function_name="error_log($_GET)",
        severity=Severity.MEDIUM,
        confidence=Confidence.HIGH,
        description="PHP error_log with user input -- log injection",
        cwe="CWE-117",
    ),
    SinkPattern(
        id="php-sql-003",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PHP],
        pattern=r"\$(?:wpdb|db)->query\s*\(\s*\$",
        function_name="wpdb->query($var)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="WordPress wpdb->query with variable",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="php-sql-004",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PHP],
        pattern=r"PDO::prepare\s*\(\s*['\"][^'\"]*['\"].*\+",
        function_name="PDO::prepare(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PDO prepare with query concatenation",
        cwe="CWE-89",
    ),
])

# ==============================================================================
# JAVA -- more command injection, code execution
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="java-ci-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.JAVA],
        pattern=r"Runtime\.getRuntime\(\)\.exec\s*\(\s*new\s+String\[\]",
        function_name="Runtime.exec(String[])",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Java Runtime.exec with array -- check arg sources",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="java-ci-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.JAVA],
        pattern=r"new\s+ProcessBuilder\s*\(\s*[^)]*\+",
        function_name="new ProcessBuilder(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Java ProcessBuilder with concatenated command",
        cwe="CWE-78",
        negative_patterns=[r'ProcessBuilder\s*\(\s*"'],
    ),
    SinkPattern(
        id="java-ci-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.JAVA],
        pattern=r"ProcessBuilder.*\.command\s*\(\s*Arrays\.asList\s*\([^)]*\+",
        function_name="ProcessBuilder.command(Arrays.asList(concat))",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Java ProcessBuilder.command with concatenated element",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="java-rce-001",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.JAVA],
        pattern=r"ScriptEngineManager\s*\(\s*\)\.getEngineByName\s*\(",
        function_name="ScriptEngineManager().getEngineByName()",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="Java ScriptEngine -- nashorn/rhino code execution",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="java-rce-002",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.JAVA],
        pattern=r"Class\.forName\s*\(\s*[^\"'][^)]*\)",
        function_name="Class.forName(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Java Class.forName with variable -- reflection abuse",
        cwe="CWE-94",
        negative_patterns=[r"Class\.forName\s*\(\s*\""],
    ),
    SinkPattern(
        id="java-pt-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.JAVA],
        pattern=r"new\s+FileInputStream\s*\(\s*[^\"'][^)]*\)",
        function_name="new FileInputStream(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Java FileInputStream with variable path",
        cwe="CWE-22",
        negative_patterns=[r"FileInputStream\s*\(\s*\""],
    ),
    SinkPattern(
        id="java-pt-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.JAVA],
        pattern=r"new\s+FileOutputStream\s*\(\s*[^\"'][^)]*\)",
        function_name="new FileOutputStream(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="Java FileOutputStream with variable path",
        cwe="CWE-22",
        negative_patterns=[r"FileOutputStream\s*\(\s*\""],
    ),
    SinkPattern(
        id="java-pt-003",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.JAVA],
        pattern=r"Files\.readAllBytes\s*\(\s*Paths\.get\s*\(\s*[^\"'][^)]*\)",
        function_name="Files.readAllBytes(Paths.get(variable))",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Java Files.readAllBytes with variable path",
        cwe="CWE-22",
        negative_patterns=[r"Paths\.get\s*\(\s*\""],
    ),
    SinkPattern(
        id="java-ssrf-005",
        vuln_type=VulnType.SSRF,
        languages=[Language.JAVA],
        pattern=r"OkHttpClient.*\.newCall\s*\(\s*new\s+Request\.Builder\s*\(\s*\)\.url\s*\(\s*[^\"'][^)]*\)",
        function_name="OkHttp Request.url(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="OkHttp request with variable URL",
        cwe="CWE-918",
        negative_patterns=[r"\.url\s*\(\s*\""],
    ),
])

# ==============================================================================
# C/C++ -- more patterns
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="c-ci-extra-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bsystem\s*\(\s*(?!NULL)[^\")][^)]*\)",
        function_name="system(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="C system() with variable command",
        cwe="CWE-78",
        negative_patterns=[r"system\s*\(\s*\""],
    ),
    SinkPattern(
        id="c-ci-extra-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bsystem\s*\(\s*buf\b",
        function_name="system(buf)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="C system() with buffer variable -- likely user-controlled",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="c-buf-001",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bgets\s*\(",
        function_name="gets()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="gets() -- unchecked buffer overflow",
        cwe="CWE-121",
        tags=["deprecated", "buffer-overflow"],
    ),
    SinkPattern(
        id="c-buf-002",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bstrcpy\s*\(",
        function_name="strcpy()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="strcpy -- unchecked buffer overflow risk",
        cwe="CWE-121",
        remediation="Use strncpy() or strlcpy()",
    ),
    SinkPattern(
        id="c-buf-003",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bstrcat\s*\(",
        function_name="strcat()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="strcat -- buffer overflow risk",
        cwe="CWE-121",
        remediation="Use strncat() or strlcat()",
    ),
    SinkPattern(
        id="c-buf-004",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bsprintf\s*\(\s*\w+\s*,",
        function_name="sprintf(buf, ...)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="sprintf without bound -- buffer overflow risk",
        cwe="CWE-121",
        remediation="Use snprintf(buf, sizeof(buf), ...)",
    ),
    SinkPattern(
        id="c-format-001",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bprintf\s*\(\s*[^\"'][^)]*\)",
        function_name="printf(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="printf with variable format string -- format string attack",
        cwe="CWE-134",
        negative_patterns=[r"printf\s*\(\s*\""],
    ),
    SinkPattern(
        id="c-format-002",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.C, Language.CPP],
        pattern=r"\bsyslog\s*\(\s*\w+,\s*[^\"'][^)]*\)",
        function_name="syslog(priority, variable)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="syslog with variable format string",
        cwe="CWE-134",
        negative_patterns=[r"syslog\s*\(\s*\w+,\s*\""],
    ),
])

# ==============================================================================
# TEMPLATE INJECTION -- additional patterns
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-tpl-extra-001",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"jinja2\.Environment\s*\([^)]*\)\.get_template\s*\(\s*[^'\"\s][^)]*\)",
        function_name="Environment().get_template(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Jinja2 get_template with variable name -- path injection to SSTI",
        cwe="CWE-94",
        negative_patterns=[r"get_template\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-tpl-extra-002",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"render\s*\(\s*[^'\"\s][^,)]*",
        function_name="render(variable_template)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Template render with variable template name",
        cwe="CWE-94",
        negative_patterns=[r"render\s*\(\s*['\"]", r"render_template"],
        context_patterns=[r"jinja2|flask|django|fastapi|starlette"],
    ),
    SinkPattern(
        id="js-tpl-extra-001",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"twig\.renderString\s*\(\s*[^'\"`\s][^,)]*",
        function_name="twig.renderString(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Twig.js renderString with user input -- SSTI",
        cwe="CWE-94",
        negative_patterns=[r"renderString\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-tpl-extra-002",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"consolidate\.\w+\s*\(\s*[^'\"`\s][^,)]*",
        function_name="consolidate.engine(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="consolidate.js template engine with variable template",
        cwe="CWE-94",
        negative_patterns=[r"consolidate\.\w+\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="rb-tpl-001",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.RUBY],
        pattern=r"ERB\.new\s*\(\s*[^'\"#\s][^)]*\)",
        function_name="ERB.new(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Ruby ERB template from user input -- SSTI",
        cwe="CWE-94",
        negative_patterns=[r"ERB\.new\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="rb-tpl-002",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.RUBY],
        pattern=r'ERB\.new\s*\(\s*"[^"]*#\{',
        function_name='ERB.new("#{interpolation}")',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Ruby ERB::new with interpolated template",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="java-tpl-001",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.JAVA],
        pattern=r"Velocity\.evaluate\s*\(",
        function_name="Velocity.evaluate()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Apache Velocity template evaluation -- SSTI",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="java-tpl-002",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.JAVA],
        pattern=r"FreeMarker.*Template.*process\s*\(",
        function_name="FreeMarker Template.process()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="FreeMarker template processing -- check template source",
        cwe="CWE-94",
    ),
])

PATTERN_COUNT = len(PATTERNS)
