"""
Injection extra -- additional patterns to ensure 800+ total sink coverage.

Covers edge cases, specific libraries, and additional language variants
across all vulnerability categories.
"""

from mcpsec.static.patterns.base import (
    SinkPattern, Language, VulnType, Severity, Confidence
)

PATTERNS: list[SinkPattern] = []

# ==============================================================================
# COMMAND INJECTION -- Python subprocess/os edge cases
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-ci-extra-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"subprocess\.run\s*\(\s*f['\"]",
        function_name="subprocess.run(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess.run with f-string command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-ci-extra-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"subprocess\.call\s*\(\s*f['\"]",
        function_name="subprocess.call(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess.call with f-string",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-ci-extra-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"subprocess\.check_output\s*\(\s*f['\"]",
        function_name="subprocess.check_output(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess.check_output with f-string",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-ci-extra-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"subprocess\.check_call\s*\(\s*f['\"]",
        function_name="subprocess.check_call(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess.check_call with f-string",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-ci-extra-005",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"subprocess\.Popen\s*\(\s*f['\"]",
        function_name="subprocess.Popen(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess.Popen with f-string command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-ci-extra-006",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"subprocess\.run\s*\([^)]*\.format\s*\(",
        function_name="subprocess.run(.format())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess.run with .format() command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-ci-extra-007",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"subprocess\.Popen\s*\([^)]*\.format\s*\(",
        function_name="subprocess.Popen(.format())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess.Popen with .format() command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-ci-extra-008",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"subprocess\.run\s*\([^)]*\+[^)]*\)",
        function_name="subprocess.run(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="subprocess.run with concatenated command",
        cwe="CWE-78",
        negative_patterns=[r"subprocess\.run\s*\(\s*\["],
    ),
    SinkPattern(
        id="py-ci-extra-009",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"os\.system\s*\(\s*f['\"]",
        function_name="os.system(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="os.system with f-string command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-ci-extra-010",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"os\.system\s*\([^)]*\.format\s*\(",
        function_name="os.system(.format())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="os.system with .format() command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-ci-extra-011",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"os\.system\s*\([^)]*\+[^)]*\)",
        function_name="os.system(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="os.system with concatenated command",
        cwe="CWE-78",
        negative_patterns=[r"os\.system\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-ci-extra-012",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"os\.popen\s*\([^)]*\.format\s*\(",
        function_name="os.popen(.format())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="os.popen with .format() command",
        cwe="CWE-78",
    ),
])

# ==============================================================================
# COMMAND INJECTION -- JavaScript 
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-ci-extra-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bexec\s*\(\s*[^'\"`\s][^,)]*",
        function_name="exec(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="child_process exec with variable command",
        cwe="CWE-78",
        negative_patterns=[r"\bexec\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-ci-extra-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bexec\s*\(\s*`[^`]*\$\{",
        function_name="exec(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="child_process exec with template literal",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-ci-extra-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bexecSync\s*\(\s*[^'\"`\s][^,)]*",
        function_name="execSync(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="execSync with variable command",
        cwe="CWE-78",
        negative_patterns=[r"\bexecSync\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-ci-extra-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bexecSync\s*\(\s*`[^`]*\$\{",
        function_name="execSync(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="execSync with template literal",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-ci-extra-005",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bspawn\s*\(\s*[^'\"`\s][^,)]*",
        function_name="spawn(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="spawn with variable executable",
        cwe="CWE-78",
        negative_patterns=[r"\bspawn\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-ci-extra-006",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bspawn\s*\(\s*`[^`]*\$\{",
        function_name="spawn(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="spawn with template literal executable",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-ci-extra-007",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bspawnSync\s*\(\s*[^'\"`\s][^,)]*",
        function_name="spawnSync(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="spawnSync with variable executable",
        cwe="CWE-78",
        negative_patterns=[r"\bspawnSync\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-ci-extra-008",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bspawnSync\s*\(\s*`[^`]*\$\{",
        function_name="spawnSync(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="spawnSync with template literal",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-ci-extra-009",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bexec\s*\([^)]*\+[^)]*\)",
        function_name="exec(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="child_process exec with concatenation",
        cwe="CWE-78",
        negative_patterns=[r"\bexec\s*\(\s*['\"`]"],
    ),
])

# ==============================================================================
# PATH TRAVERSAL -- more Python specific
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-pt-extra-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bopen\s*\([^)]*\bos\.path\.join\s*\(",
        function_name="open(os.path.join(...))",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="File open using os.path.join -- check user control of components",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-pt-extra-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bos\.makedirs\s*\(\s*f['\"]",
        function_name="os.makedirs(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="os.makedirs with f-string path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-pt-extra-003",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bos\.mkdir\s*\(\s*f['\"]",
        function_name="os.mkdir(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="os.mkdir with f-string path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-pt-extra-004",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bos\.rename\s*\(\s*f['\"]",
        function_name="os.rename(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="os.rename with f-string path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-pt-extra-005",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bshutil\.move\s*\(\s*f['\"]",
        function_name="shutil.move(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="shutil.move with f-string path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-pt-extra-006",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bglob\.glob\s*\(\s*f['\"]",
        function_name="glob.glob(f-string)",
        severity=Severity.MEDIUM,
        confidence=Confidence.HIGH,
        description="glob with f-string pattern -- directory enumeration",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-pt-extra-007",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bimportlib\.machinery\.SourceFileLoader\s*\(\s*[^,]+,\s*[^'\"\s]",
        function_name="SourceFileLoader(name, variable_path)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Dynamic source loading with variable path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-pt-extra-008",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"with\s+open\s*\(\s*[^'\"\s][^,)]*",
        function_name="with open(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Context manager file open with variable path",
        cwe="CWE-22",
        negative_patterns=[r"with\s+open\s*\(\s*['\"]"],
    ),
])

# ==============================================================================
# PATH TRAVERSAL -- JavaScript
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-pt-extra-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"Deno\.readFile\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="Deno.readFile(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Deno.readFile with variable path",
        cwe="CWE-22",
        negative_patterns=[r"Deno\.readFile\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-pt-extra-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"Deno\.writeFile\s*\(\s*[^'\"`\s][^,)]*",
        function_name="Deno.writeFile(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="Deno.writeFile with variable path",
        cwe="CWE-22",
        negative_patterns=[r"Deno\.writeFile\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-pt-extra-003",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"Deno\.remove\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="Deno.remove(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="Deno.remove with variable path",
        cwe="CWE-22",
        negative_patterns=[r"Deno\.remove\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-pt-extra-004",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"Bun\.file\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="Bun.file(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Bun.file() with variable path",
        cwe="CWE-22",
        negative_patterns=[r"Bun\.file\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-pt-extra-005",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"fs\.promises\.readFile\s*\(\s*[^'\"`\s][^,)]*",
        function_name="fs.promises.readFile(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="fs.promises.readFile with variable path",
        cwe="CWE-22",
        negative_patterns=[r"promises\.readFile\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-pt-extra-006",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"fs\.promises\.writeFile\s*\(\s*[^'\"`\s][^,)]*",
        function_name="fs.promises.writeFile(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="fs.promises.writeFile with variable path",
        cwe="CWE-22",
        negative_patterns=[r"promises\.writeFile\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-pt-extra-007",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"fs\.promises\.unlink\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="fs.promises.unlink(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="fs.promises.unlink with variable path",
        cwe="CWE-22",
        negative_patterns=[r"promises\.unlink\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-pt-extra-008",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"require\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="require(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Dynamic require() with variable module path",
        cwe="CWE-22",
        negative_patterns=[r"require\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-pt-extra-009",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"import\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="import(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Dynamic import() with variable path -- path traversal + code exec",
        cwe="CWE-22",
        negative_patterns=[r"import\s*\(\s*['\"`]"],
    ),
])

# ==============================================================================
# SSRF -- additional patterns fetch/axios variants
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-ssrf-extra-001",
        vuln_type=VulnType.SSRF,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"(?:await\s+)?fetch\s*\(\s*(?:process\.env\.\w+|config\.\w+|settings\.\w+)",
        function_name="fetch(env/config variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="fetch() with environment/config variable URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="js-ssrf-extra-002",
        vuln_type=VulnType.SSRF,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"axios\.(?:get|post|put|delete|patch)\s*\(\s*`[^`]*\$\{",
        function_name="axios.method(`${url}`)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="axios method with template literal URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="js-ssrf-extra-003",
        vuln_type=VulnType.SSRF,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"supertest\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="supertest(variable)",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="supertest with variable URL",
        cwe="CWE-918",
        negative_patterns=[r"supertest\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="py-ssrf-extra-001",
        vuln_type=VulnType.SSRF,
        languages=[Language.PYTHON],
        pattern=r"requests\.get\s*\([^)]*\+[^)]*\)",
        function_name="requests.get(concat URL)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="requests.get with concatenated URL",
        cwe="CWE-918",
        negative_patterns=[r"requests\.get\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-ssrf-extra-002",
        vuln_type=VulnType.SSRF,
        languages=[Language.PYTHON],
        pattern=r"requests\.post\s*\(\s*f['\"]",
        function_name="requests.post(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="requests.post with f-string URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="py-ssrf-extra-003",
        vuln_type=VulnType.SSRF,
        languages=[Language.PYTHON],
        pattern=r"requests\.(?:put|patch|delete|head|options)\s*\(\s*f['\"]",
        function_name="requests.*(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="requests method with f-string URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="py-ssrf-extra-004",
        vuln_type=VulnType.SSRF,
        languages=[Language.PYTHON],
        pattern=r"httpx\.get\s*\(\s*f['\"]",
        function_name="httpx.get(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="httpx.get with f-string URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="py-ssrf-extra-005",
        vuln_type=VulnType.SSRF,
        languages=[Language.PYTHON],
        pattern=r"httpx\.post\s*\(\s*f['\"]",
        function_name="httpx.post(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="httpx.post with f-string URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="go-ssrf-extra-001",
        vuln_type=VulnType.SSRF,
        languages=[Language.GO],
        pattern=r"http\.Get\s*\(\s*[^\"'][^)]*\+",
        function_name="http.Get(concat)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="http.Get with string concatenation",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="go-ssrf-extra-002",
        vuln_type=VulnType.SSRF,
        languages=[Language.GO],
        pattern=r"http\.Post\s*\(\s*fmt\.Sprintf\s*\(",
        function_name="http.Post(Sprintf())",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="http.Post with Sprintf URL",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="go-ssrf-extra-003",
        vuln_type=VulnType.SSRF,
        languages=[Language.GO],
        pattern=r"(?:resty|cleanhttp)\.\w+\s*\(\s*\).*Get\s*\(\s*[^\"'][^)]*\)",
        function_name="resty/cleanhttp.Get(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="resty/cleanhttp with variable URL",
        cwe="CWE-918",
    ),
])

# ==============================================================================
# SQL INJECTION -- more database-specific
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-sql-extra-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"cursor\.execute\s*\(\s*\"SELECT",
        function_name="cursor.execute(\"SELECT...\")",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="cursor.execute with literal SELECT -- check for format injection",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-extra-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"pymongo.*\$regex.*:\s*[^'\"{\s]",
        function_name="MongoDB $regex with variable",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="MongoDB $regex with user input -- ReDoS + injection",
        cwe="CWE-943",
    ),
    SinkPattern(
        id="js-sql-extra-005",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"mongodb.*\$regex.*:\s*[^'\"{\s]",
        function_name="MongoDB $regex with variable",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="MongoDB $regex with user input -- ReDoS",
        cwe="CWE-943",
    ),
    SinkPattern(
        id="cs-sql-extra-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.CSHARP],
        pattern=r"NpgsqlCommand\s*\(\s*\$\"",
        function_name="NpgsqlCommand($\"...\")",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PostgreSQL NpgsqlCommand with interpolation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="cs-sql-extra-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.CSHARP],
        pattern=r"MySqlCommand\s*\(\s*\$\"",
        function_name="MySqlCommand($\"...\")",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MySQL MySqlCommand with interpolation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="cs-sql-extra-003",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.CSHARP],
        pattern=r"SqliteCommand\s*\(\s*\$\"",
        function_name="SqliteCommand($\"...\")",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQLite SqliteCommand with interpolation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="cs-sql-extra-004",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.CSHARP],
        pattern=r"\.FromSqlRaw\s*\([^)]*\+",
        function_name="FromSqlRaw(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="EF Core FromSqlRaw with concatenation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="go-sql-extra-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r"db\.QueryContext\s*\(\s*ctx,\s*fmt\.Sprintf\s*\(",
        function_name="db.QueryContext(ctx, Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQL QueryContext with Sprintf",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="go-sql-extra-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r"db\.ExecContext\s*\(\s*ctx,\s*fmt\.Sprintf\s*\(",
        function_name="db.ExecContext(ctx, Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQL ExecContext with Sprintf",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="rs-sql-extra-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.RUST],
        pattern=r"diesel::dsl::sql\s*::<[^>]+>\s*\(\s*&?format!\s*\(",
        function_name="diesel::dsl::sql(format!())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Diesel dsl::sql with format! macro",
        cwe="CWE-89",
    ),
])

# ==============================================================================
# CODE EXECUTION -- more patterns
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-exec-extra-001",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PYTHON],
        pattern=r"\b__import__\s*\(\s*[^'\"\s][^)]*\)",
        function_name="__import__(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="__import__ with variable module name",
        cwe="CWE-94",
        negative_patterns=[r"__import__\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-exec-extra-002",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PYTHON],
        pattern=r"\b__import__\s*\(\s*f['\"]",
        function_name="__import__(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="__import__ with f-string module name",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="py-exec-extra-003",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PYTHON],
        pattern=r"importlib\.import_module\s*\([^)]*\+[^)]*\)",
        function_name="import_module(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Dynamic module import with string concatenation",
        cwe="CWE-94",
        negative_patterns=[r"import_module\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-exec-extra-004",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PYTHON],
        pattern=r"runpy\.run_module\s*\(\s*[^'\"\s][^,)]*",
        function_name="runpy.run_module(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="runpy.run_module with variable module name",
        cwe="CWE-94",
        negative_patterns=[r"run_module\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-exec-extra-005",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PYTHON],
        pattern=r"execfile\s*\(\s*[^'\"\s][^)]*\)",
        function_name="execfile(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Python 2 execfile with variable -- code execution",
        cwe="CWE-94",
        negative_patterns=[r"execfile\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="js-exec-extra-001",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"vm\.Script\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="vm.Script(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Node.js vm.Script with variable code",
        cwe="CWE-94",
        negative_patterns=[r"vm\.Script\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-exec-extra-002",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"vm\.Script\s*\(\s*`[^`]*\$\{",
        function_name="vm.Script(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Node.js vm.Script with template literal code",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="js-exec-extra-003",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"vm\.compileFunction\s*\(\s*[^'\"`\s][^,)]*",
        function_name="vm.compileFunction(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Node.js vm.compileFunction with variable code",
        cwe="CWE-94",
        negative_patterns=[r"vm\.compileFunction\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-exec-extra-004",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"Worker\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="new Worker(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Web Worker from variable script URL",
        cwe="CWE-94",
        negative_patterns=[r"Worker\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-exec-extra-005",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.innerHTML\s*=\s*[^'\"`\s][^;]*",
        function_name=".innerHTML = variable",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="innerHTML assignment with variable -- DOM XSS",
        cwe="CWE-79",
        negative_patterns=[r"\.innerHTML\s*=\s*['\"`]"],
    ),
    SinkPattern(
        id="js-exec-extra-006",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.innerHTML\s*=\s*`[^`]*\$\{",
        function_name=".innerHTML = `${...}`",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="innerHTML with template literal -- DOM XSS",
        cwe="CWE-79",
    ),
    SinkPattern(
        id="js-exec-extra-007",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"document\.write\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="document.write(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="document.write with variable -- DOM XSS",
        cwe="CWE-79",
        negative_patterns=[r"document\.write\s*\(\s*['\"`]"],
    ),
])

# ==============================================================================
# DESERIALIZATION -- more patterns
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-deser-extra-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern=r"yaml\.load\s*\(\s*[^,)]+\)",
        function_name="yaml.load(data)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="yaml.load without Loader kwarg -- defaults to unsafe",
        cwe="CWE-502",
        negative_patterns=[
            r"yaml\.load\s*\([^)]*SafeLoader",
            r"yaml\.safe_load",
        ],
    ),
    SinkPattern(
        id="py-deser-extra-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern=r"configparser\.ConfigParser\(\)\.read_string\s*\(",
        function_name="ConfigParser.read_string()",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="ConfigParser from user string -- check interpolation risks",
        cwe="CWE-502",
    ),
    SinkPattern(
        id="py-deser-extra-003",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern=r"pickle\.loads?\s*\(\s*base64\.b64decode\s*\(",
        function_name="pickle.loads(base64.decode(user))",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Pickle deserialization of base64-decoded user data",
        cwe="CWE-502",
    ),
    SinkPattern(
        id="js-deser-extra-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"vm\.runInContext\s*\(\s*[^'\"`\s][^,)]*",
        function_name="vm.runInContext(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Node.js vm.runInContext with variable code",
        cwe="CWE-94",
        negative_patterns=[r"vm\.runInContext\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-deser-extra-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"JSON5\.parse\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="JSON5.parse(variable)",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="JSON5 parse from user input",
        cwe="CWE-1321",
        negative_patterns=[r"JSON5\.parse\s*\(\s*['\"`]"],
    ),
])

# ==============================================================================
# CRYPTO -- additional patterns
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-crypto-extra-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"createCipheriv\s*\(\s*['\"]aes-128-",
        function_name="createCipheriv('aes-128-*')",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="AES-128 -- weaker than AES-256, prefer 256-bit keys",
        cwe="CWE-326",
    ),
    SinkPattern(
        id="js-crypto-extra-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.generateKeyPairSync\s*\(\s*['\"]rsa['\"],\s*\{[^}]*modulusLength\s*:\s*(?:512|768|1024)\b",
        function_name="generateKeyPairSync(rsa, {modulusLength: <2048})",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="RSA key generation < 2048 bits",
        cwe="CWE-326",
    ),
    SinkPattern(
        id="py-crypto-extra-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern=r"Fernet\s*\(\s*['\"][a-zA-Z0-9+/=]{43,}['\"]",
        function_name="Fernet(hardcoded_key)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Hardcoded Fernet key",
        cwe="CWE-798",
    ),
    SinkPattern(
        id="py-crypto-extra-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern=r"SECRET_KEY\s*=\s*['\"][a-zA-Z0-9!@#$%^&*_\-+=]{16,}['\"]",
        function_name="SECRET_KEY = 'hardcoded'",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Hardcoded Django/Flask SECRET_KEY",
        cwe="CWE-798",
        negative_patterns=[
            r"(?i)example|changeme|replace|your_secret|os\.environ",
        ],
    ),
    SinkPattern(
        id="go-crypto-extra-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern=r"rsa\.GenerateKey\s*\([^,]+,\s*(?:512|768|1024)\s*\)",
        function_name="rsa.GenerateKey(rand, <2048)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="RSA key generation < 2048 bits in Go",
        cwe="CWE-326",
    ),
    SinkPattern(
        id="go-crypto-extra-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern=r"ecdsa\.GenerateKey\s*\(\s*elliptic\.P224",
        function_name="ecdsa.GenerateKey(P-224)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="ECDSA with P-224 curve -- weak, prefer P-256/P-384",
        cwe="CWE-326",
    ),
])

# ==============================================================================
# LOG INJECTION -- more patterns
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-log-extra-001",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"logging\.\w+\s*\(\s*f['\"][^'\"]*\{[^}]*(?:request|args|params|user|input)[^}]*\}",
        function_name="logging.*(f-string with input)",
        severity=Severity.MEDIUM,
        confidence=Confidence.HIGH,
        description="Logging user input with f-string -- log injection",
        cwe="CWE-117",
    ),
    SinkPattern(
        id="go-log-001",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.GO],
        pattern=r"log\.Printf\s*\(\s*[^\"'][^,)]*",
        function_name="log.Printf(variable format)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="log.Printf with variable format string -- format injection",
        cwe="CWE-117",
        negative_patterns=[r"log\.Printf\s*\(\s*\""],
    ),
    SinkPattern(
        id="go-log-002",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.GO],
        pattern=r"fmt\.Fprintf\s*\(\s*\w+,\s*[^\"'][^,)]*",
        function_name="fmt.Fprintf(w, variable format)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="fmt.Fprintf with variable format string",
        cwe="CWE-117",
        negative_patterns=[r"fmt\.Fprintf\s*\(\s*\w+,\s*\""],
    ),
    SinkPattern(
        id="cs-log-001",
        vuln_type=VulnType.LOG_INJECTION,
        languages=[Language.CSHARP],
        pattern=r"_logger\.\w+\s*\(\s*\$\"[^\"]*\{[^}]*(?:request|input|user|arg)",
        function_name="_logger.*(f-interpolation with user data)",
        severity=Severity.MEDIUM,
        confidence=Confidence.HIGH,
        description="C# logger with user data interpolation",
        cwe="CWE-117",
    ),
])

# ==============================================================================
# LDAP -- more patterns
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="cs-ldap-001",
        vuln_type=VulnType.LDAP_INJECTION,
        languages=[Language.CSHARP],
        pattern=r"DirectorySearcher\s*\(\s*\$\"",
        function_name="DirectorySearcher($\"...\")",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="LDAP DirectorySearcher with interpolated filter",
        cwe="CWE-90",
    ),
    SinkPattern(
        id="cs-ldap-002",
        vuln_type=VulnType.LDAP_INJECTION,
        languages=[Language.CSHARP],
        pattern=r"\.Filter\s*=\s*\$\"",
        function_name=".Filter = $\"...\"",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="LDAP SearchFilter with interpolated string",
        cwe="CWE-90",
    ),
    SinkPattern(
        id="go-ldap-001",
        vuln_type=VulnType.LDAP_INJECTION,
        languages=[Language.GO],
        pattern=r"ldap\.NewSearchRequest\s*\([^,]+,\s*[^,]+,\s*[^,]+,\s*[^,]+,\s*fmt\.Sprintf\s*\(",
        function_name="ldap.NewSearchRequest(Sprintf filter)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Go LDAP search with Sprintf filter",
        cwe="CWE-90",
    ),
])

PATTERN_COUNT = len(PATTERNS)
