"""
Path Traversal patterns -- ~150 patterns across 6 languages.

Coverage:
- TypeScript/JavaScript: fs.readFile, writeFile, path.join, send(), statSync
- Python: open(), Path(), os.path, shutil, send_file()
- Go: os.Open(), filepath.Join(), http.ServeFile()
- C/C++: fopen(), open(), stat()
- C#: File.ReadAllText, FileStream, Path.Combine
- Rust: fs::read(), File::open()
"""

from mcpsec.static.patterns.base import (
    SinkPattern, Language, VulnType, Severity, Confidence
)

PATTERNS: list[SinkPattern] = []

# ==============================================================================
# TYPESCRIPT / JAVASCRIPT
# ==============================================================================

# -- fs module --
PATTERNS.extend([
    SinkPattern(
        id="js-path-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bfs\.readFile(?:Sync)?\s*\(\s*[^'\"`\s][^,)]*",
        function_name="fs.readFile(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="fs.readFile with variable path -- possible traversal",
        cwe="CWE-22",
        remediation="Validate path is within expected directory using path.resolve() and startsWith()",
        negative_patterns=[r"fs\.readFile(?:Sync)?\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-path-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bfs\.readFile(?:Sync)?\s*\(\s*`[^`]*\$\{[^}]+\}",
        function_name="fs.readFile(`${...}`)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="fs.readFile with template literal path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="js-path-003",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bfs\.writeFile(?:Sync)?\s*\(\s*[^'\"`\s][^,)]*",
        function_name="fs.writeFile(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="fs.writeFile with variable path",
        cwe="CWE-22",
        negative_patterns=[r"fs\.writeFile(?:Sync)?\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-path-004",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bfs\.writeFile(?:Sync)?\s*\(\s*`[^`]*\$\{[^}]+\}",
        function_name="fs.writeFile(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="fs.writeFile with template literal path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="js-path-005",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bfs\.unlink(?:Sync)?\s*\(\s*[^'\"`\s][^,)]*",
        function_name="fs.unlink(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="fs.unlink with variable path -- arbitrary file deletion",
        cwe="CWE-22",
        negative_patterns=[r"fs\.unlink(?:Sync)?\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-path-006",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bfs\.open(?:Sync)?\s*\(\s*[^'\"`\s][^,)]*",
        function_name="fs.open(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="fs.open with variable path",
        cwe="CWE-22",
        negative_patterns=[r"fs\.open(?:Sync)?\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-path-007",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bfs\.stat(?:Sync)?\s*\(\s*[^'\"`\s][^,)]*",
        function_name="fs.stat(variable)",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="fs.stat with variable path -- path probing",
        cwe="CWE-22",
        negative_patterns=[r"fs\.stat(?:Sync)?\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-path-008",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bfs\.readdir(?:Sync)?\s*\(\s*[^'\"`\s][^,)]*",
        function_name="fs.readdir(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="fs.readdir with variable path -- directory listing",
        cwe="CWE-22",
        negative_patterns=[r"fs\.readdir(?:Sync)?\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-path-009",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bfs\.copyFile(?:Sync)?\s*\(\s*[^'\"`\s][^,)]*",
        function_name="fs.copyFile(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="fs.copyFile with variable path",
        cwe="CWE-22",
        negative_patterns=[r"fs\.copyFile(?:Sync)?\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-path-010",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bfs\.rm(?:Sync)?\s*\(\s*[^'\"`\s][^,)]*",
        function_name="fs.rm(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="fs.rm with variable path -- arbitrary file removal",
        cwe="CWE-22",
        negative_patterns=[r"fs\.rm(?:Sync)?\s*\(\s*['\"`]"],
    ),
])

# -- path.join with user input --
PATTERNS.extend([
    SinkPattern(
        id="js-path-020",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bpath\.join\s*\([^)]*\$\{[^}]+\}",
        function_name="path.join(${...})",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="path.join with interpolated user input",
        cwe="CWE-22",
        remediation="Validate with path.resolve() and check startsWith(baseDir)",
    ),
    SinkPattern(
        id="js-path-021",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bpath\.resolve\s*\([^)]*\$\{[^}]+\}",
        function_name="path.resolve(${...})",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="path.resolve with interpolated user input",
        cwe="CWE-22",
        remediation="Check that resolved path starts with expected base directory",
    ),
    SinkPattern(
        id="js-path-022",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bpath\.join\s*\(.*,\s*[^'\"`\)\s][^)]*\)",
        function_name="path.join(base, variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="path.join with variable final component",
        cwe="CWE-22",
        negative_patterns=[r"path\.join\s*\([^)]*,\s*['\"`]"],
    ),
])

# -- Express/Fastify send/sendFile --
PATTERNS.extend([
    SinkPattern(
        id="js-path-030",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"res\.sendFile\s*\(\s*[^'\"`\s][^,)]*",
        function_name="res.sendFile(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Express sendFile with variable path",
        cwe="CWE-22",
        negative_patterns=[r"res\.sendFile\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-path-031",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"res\.sendFile\s*\(\s*`[^`]*\$\{[^}]+\}",
        function_name="res.sendFile(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Express sendFile with template literal path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="js-path-032",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"res\.download\s*\(\s*[^'\"`\s][^,)]*",
        function_name="res.download(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Express download with variable path",
        cwe="CWE-22",
        negative_patterns=[r"res\.download\s*\(\s*['\"`]"],
    ),
])

# -- Node.js streams / createReadStream --
PATTERNS.extend([
    SinkPattern(
        id="js-path-040",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bfs\.createReadStream\s*\(\s*[^'\"`\s][^,)]*",
        function_name="fs.createReadStream(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="createReadStream with variable path",
        cwe="CWE-22",
        negative_patterns=[r"createReadStream\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-path-041",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bfs\.createReadStream\s*\(\s*`[^`]*\$\{[^}]+\}",
        function_name="fs.createReadStream(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="createReadStream with template literal path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="js-path-042",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\bfs\.createWriteStream\s*\(\s*[^'\"`\s][^,)]*",
        function_name="fs.createWriteStream(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="createWriteStream with variable path -- arbitrary write",
        cwe="CWE-22",
        negative_patterns=[r"createWriteStream\s*\(\s*['\"`]"],
    ),
])

# ==============================================================================
# PYTHON
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-path-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bopen\s*\(\s*f['\"]",
        function_name="open(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="File open with f-string path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-path-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bopen\s*\([^)]*\.format\s*\(",
        function_name="open(.format())",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="File open with format() path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-path-003",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bopen\s*\([^)]*\+[^)]*\)",
        function_name="open(concat)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="File open with concatenated path",
        cwe="CWE-22",
        negative_patterns=[r"\bopen\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-path-004",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bPath\s*\([^)]*\+[^)]*\)",
        function_name="Path(concat)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="pathlib.Path with concatenated path",
        cwe="CWE-22",
        negative_patterns=[r"Path\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-path-005",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bPath\s*\(\s*f['\"]",
        function_name="Path(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="pathlib.Path with f-string",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-path-006",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bos\.path\.join\s*\([^)]*[^'\",\s)][^)]*\)",
        function_name="os.path.join(variable)",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="os.path.join -- check if user input is a component",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-path-007",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bshutil\.copy\s*\(\s*f['\"]",
        function_name="shutil.copy(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="shutil.copy with f-string path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-path-008",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bshutil\.rmtree\s*\(\s*f['\"]",
        function_name="shutil.rmtree(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="shutil.rmtree with f-string -- arbitrary directory deletion",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-path-009",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bos\.remove\s*\(\s*f['\"]",
        function_name="os.remove(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="os.remove with f-string path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-path-010",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bsend_file\s*\(\s*[^'\"\s][^,)]*",
        function_name="flask.send_file(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Flask send_file with variable path",
        cwe="CWE-22",
        negative_patterns=[r"send_file\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-path-011",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bsend_from_directory\s*\([^)]*f['\"]",
        function_name="flask.send_from_directory(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Flask send_from_directory with f-string",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-path-012",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"\bpathlib\.Path\s*\(/",
        function_name="Path('/...')",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="Path starting with / -- absolute path construction",
        cwe="CWE-22",
    ),
])

# ==============================================================================
# GO
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="go-path-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.GO],
        pattern=r"\bos\.Open\s*\(\s*[^\"'][^)]*\)",
        function_name="os.Open(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="os.Open with variable path",
        cwe="CWE-22",
        negative_patterns=[r"os\.Open\s*\(\s*\""],
    ),
    SinkPattern(
        id="go-path-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.GO],
        pattern=r"\bos\.ReadFile\s*\(\s*[^\"'][^)]*\)",
        function_name="os.ReadFile(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="os.ReadFile with variable path",
        cwe="CWE-22",
        negative_patterns=[r"os\.ReadFile\s*\(\s*\""],
    ),
    SinkPattern(
        id="go-path-003",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.GO],
        pattern=r"\bos\.Create\s*\(\s*[^\"'][^)]*\)",
        function_name="os.Create(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="os.Create with variable path -- arbitrary file write",
        cwe="CWE-22",
        negative_patterns=[r"os\.Create\s*\(\s*\""],
    ),
    SinkPattern(
        id="go-path-004",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.GO],
        pattern=r"\bfilepath\.Join\s*\([^)]*[^\"'][^)]*\)",
        function_name="filepath.Join(variable)",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="filepath.Join -- check if user input is a component",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="go-path-005",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.GO],
        pattern=r"\bhttp\.ServeFile\s*\(",
        function_name="http.ServeFile()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="http.ServeFile -- check filename source",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="go-path-006",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.GO],
        pattern=r"\bioutil\.ReadFile\s*\(\s*[^\"'][^)]*\)",
        function_name="ioutil.ReadFile(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="ioutil.ReadFile with variable path",
        cwe="CWE-22",
        negative_patterns=[r"ioutil\.ReadFile\s*\(\s*\""],
    ),
])

# ==============================================================================
# C / C++
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="c-path-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.C, Language.CPP],
        pattern=r"\bfopen\s*\(",
        function_name="fopen()",
        severity=Severity.HIGH,
        confidence=Confidence.LOW,
        description="fopen() -- check if path is user-controlled",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="c-path-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.C, Language.CPP],
        pattern=r"\bopen\s*\([^)]*O_WRONLY",
        function_name="open(O_WRONLY)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="open() for writing with variable path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="c-path-003",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.C, Language.CPP],
        pattern=r"\bunlink\s*\(",
        function_name="unlink()",
        severity=Severity.CRITICAL,
        confidence=Confidence.LOW,
        description="unlink() -- arbitrary file deletion risk",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="c-path-004",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.C, Language.CPP],
        pattern=r"\brmdir\s*\(",
        function_name="rmdir()",
        severity=Severity.CRITICAL,
        confidence=Confidence.LOW,
        description="rmdir() -- arbitrary directory removal risk",
        cwe="CWE-22",
    ),
])

# ==============================================================================
# C# / .NET
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="cs-path-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.CSHARP],
        pattern=r"File\.ReadAllText\s*\(\s*[^@\"'][^)]*\)",
        function_name="File.ReadAllText(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="File.ReadAllText with variable path",
        cwe="CWE-22",
        negative_patterns=[r"File\.ReadAllText\s*\(\s*[@\"]"],
    ),
    SinkPattern(
        id="cs-path-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.CSHARP],
        pattern=r"File\.WriteAllText\s*\(\s*[^@\"'][^,)]*",
        function_name="File.WriteAllText(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="File.WriteAllText with variable path",
        cwe="CWE-22",
        negative_patterns=[r"File\.WriteAllText\s*\(\s*[@\"]"],
    ),
    SinkPattern(
        id="cs-path-003",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.CSHARP],
        pattern=r"new FileStream\s*\(\s*[^@\"'][^,)]*",
        function_name="new FileStream(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="FileStream with variable path",
        cwe="CWE-22",
        negative_patterns=[r"FileStream\s*\(\s*[@\"]"],
    ),
    SinkPattern(
        id="cs-path-004",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.CSHARP],
        pattern=r"Path\.Combine\s*\([^)]*\$\"",
        function_name="Path.Combine($\"...\")",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Path.Combine with interpolated string",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="cs-path-005",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.CSHARP],
        pattern=r"File\.Delete\s*\(\s*[^@\"'][^)]*\)",
        function_name="File.Delete(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="File.Delete with variable path",
        cwe="CWE-22",
        negative_patterns=[r"File\.Delete\s*\(\s*[@\"]"],
    ),
])

PATTERN_COUNT = len(PATTERNS)
