"""
SQL Injection patterns -- ~150 patterns across 6 languages.

Coverage:
- TypeScript/JavaScript: query(), execute(), raw(), Prisma, Knex, Sequelize, MongoDB $where
- Python: cursor.execute(), Django raw(), SQLAlchemy text(), pandas read_sql()
- Go: Query(), Exec(), GORM Raw()
- C#: SqlCommand, Entity Framework FromSqlRaw
- Java: PreparedStatement misuse, JPA/Hibernate
- Rust: sqlx raw queries
"""

from mcpsec.static.patterns.base import (
    SinkPattern, Language, VulnType, Severity, Confidence
)

PATTERNS: list[SinkPattern] = []

# ==============================================================================
# TYPESCRIPT / JAVASCRIPT
# ==============================================================================

# -- Generic DB drivers --
PATTERNS.extend([
    SinkPattern(
        id="js-sql-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.query\s*\(\s*[^'\"`\[)\s][^)]*\)",
        function_name=".query(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Database query with non-literal SQL string",
        cwe="CWE-89",
        remediation="Use parameterized queries with $ placeholders",
        negative_patterns=[
            r"\.query\s*\(\s*['\"`]",
            r"\.query\s*\(\s*\{",
            r"\.query\s*\(\s*\[",
        ],
    ),
    SinkPattern(
        id="js-sql-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.query\s*\(\s*`[^`]*\$\{[^}]+\}",
        function_name=".query(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Database query with template literal interpolation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-003",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.query\s*\([^)]*\+[^)]*\)",
        function_name=".query(a + b)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Database query with string concatenation",
        cwe="CWE-89",
        negative_patterns=[r"\.query\s*\(\s*['\"`].*\+\s*['\"`]"],
    ),
    SinkPattern(
        id="js-sql-004",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.execute\s*\(\s*`[^`]*\$\{[^}]+\}",
        function_name=".execute(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="DB execute() with template literal",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-005",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.execute\s*\([^)]*\+[^)]*\)",
        function_name=".execute(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="DB execute() with concatenation",
        cwe="CWE-89",
    ),
])

# -- Sequelize raw() --
PATTERNS.extend([
    SinkPattern(
        id="js-sql-010",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"sequelize\.query\s*\(\s*`[^`]*\$\{",
        function_name="sequelize.query(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Sequelize query with template literal",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-011",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"sequelize\.query\s*\([^)]*\+",
        function_name="sequelize.query(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Sequelize query with concatenation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-012",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"Model\.findAll\s*\(\s*\{[^}]*where\s*:\s*\{[^}]*\$\{",
        function_name="Model.findAll({where: ...})",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Sequelize findAll where clause with interpolation",
        cwe="CWE-89",
    ),
])

# -- Knex --
PATTERNS.extend([
    SinkPattern(
        id="js-sql-020",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"knex\.raw\s*\(\s*`[^`]*\$\{",
        function_name="knex.raw(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Knex raw query with template literal",
        cwe="CWE-89",
        remediation="Use knex.raw('SELECT * WHERE id = ?', [id]) with bindings",
    ),
    SinkPattern(
        id="js-sql-021",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"knex\.raw\s*\([^)]*\+",
        function_name="knex.raw(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Knex raw with string concatenation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-022",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.whereRaw\s*\(\s*[^'\"`\[)\s][^)]*\)",
        function_name=".whereRaw(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Knex whereRaw with non-literal",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-023",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.whereRaw\s*\(\s*`[^`]*\$\{",
        function_name=".whereRaw(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Knex whereRaw with template literal",
        cwe="CWE-89",
    ),
])

# -- Prisma raw --
PATTERNS.extend([
    SinkPattern(
        id="js-sql-030",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"prisma\.\$queryRaw\s*`[^`]*\$\{",
        function_name="prisma.$queryRaw`${...}`",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Prisma $queryRaw with template literal interpolation",
        cwe="CWE-89",
        remediation="Use Prisma.sql tagged template or $queryRaw with Prisma.sql",
    ),
    SinkPattern(
        id="js-sql-031",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"prisma\.\$executeRaw\s*`[^`]*\$\{",
        function_name="prisma.$executeRaw`${...}`",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Prisma $executeRaw with template literal interpolation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-032",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"prisma\.\$queryRawUnsafe\s*\(",
        function_name="prisma.$queryRawUnsafe()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Prisma $queryRawUnsafe -- always dangerous",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-033",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"prisma\.\$executeRawUnsafe\s*\(",
        function_name="prisma.$executeRawUnsafe()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Prisma $executeRawUnsafe -- always dangerous",
        cwe="CWE-89",
    ),
])

# -- MongoDB NoSQL --
PATTERNS.extend([
    SinkPattern(
        id="js-nosql-001",
        vuln_type=VulnType.NOSQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.find\s*\(\s*\{[^}]*\$where",
        function_name=".find({$where})",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MongoDB $where operator -- JavaScript execution",
        cwe="CWE-943",
    ),
    SinkPattern(
        id="js-nosql-002",
        vuln_type=VulnType.NOSQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\$where\s*:",
        function_name="$where operator",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MongoDB $where operator in query",
        cwe="CWE-943",
    ),
    SinkPattern(
        id="js-nosql-003",
        vuln_type=VulnType.NOSQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.find\s*\(\s*JSON\.parse\s*\(",
        function_name=".find(JSON.parse(untrusted))",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MongoDB query from JSON.parse -- operator injection",
        cwe="CWE-943",
    ),
])

# ==============================================================================
# PYTHON
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-sql-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\.execute\s*\(\s*f['\"]",
        function_name="cursor.execute(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="DB cursor execute with f-string",
        cwe="CWE-89",
        remediation="Use parameterized queries: cursor.execute('SELECT * WHERE id = %s', (id,))",
    ),
    SinkPattern(
        id="py-sql-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\.execute\s*\(\s*['\"][^'\"]*['\"].*%.*\)",
        function_name="cursor.execute(sql % value)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="DB cursor execute with % string formatting",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-003",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\.execute\s*\([^)]*\.format\s*\(",
        function_name="cursor.execute(.format())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="DB cursor execute with .format() interpolation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-004",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\.execute\s*\([^)]*\+[^)]*\)",
        function_name="cursor.execute(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="DB cursor execute with string concatenation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-005",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\.executemany\s*\(\s*f['\"]",
        function_name="cursor.executemany(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="DB cursor executemany with f-string",
        cwe="CWE-89",
    ),
])

# -- Django ORM --
PATTERNS.extend([
    SinkPattern(
        id="py-sql-010",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\.raw\s*\(\s*f['\"]",
        function_name="django.raw(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Django raw query with f-string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-011",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\.raw\s*\([^)]*\.format\s*\(",
        function_name="django.raw(.format())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Django raw query with format()",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-012",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\.extra\s*\(\s*where\s*=\s*\[",
        function_name="queryset.extra(where=[])",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Django queryset.extra() -- SQL injection risk",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-013",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"RawSQL\s*\(\s*f['\"]",
        function_name="RawSQL(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Django RawSQL with f-string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-014",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"connection\.cursor\(\).*\.execute\(",
        function_name="connection.cursor().execute()",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="Django connection cursor -- check query construction",
        cwe="CWE-89",
    ),
])

# -- SQLAlchemy --
PATTERNS.extend([
    SinkPattern(
        id="py-sql-020",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\btext\s*\(\s*f['\"]",
        function_name="sqlalchemy.text(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQLAlchemy text() with f-string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-021",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\btext\s*\([^)]*\.format\s*\(",
        function_name="sqlalchemy.text(.format())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQLAlchemy text() with format()",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-022",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"session\.execute\s*\(\s*f['\"]",
        function_name="session.execute(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQLAlchemy session execute with f-string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-023",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"engine\.execute\s*\(\s*f['\"]",
        function_name="engine.execute(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQLAlchemy engine execute with f-string",
        cwe="CWE-89",
    ),
])

# -- pandas --
PATTERNS.extend([
    SinkPattern(
        id="py-sql-030",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"pd\.read_sql\s*\(\s*f['\"]",
        function_name="pd.read_sql(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="pandas read_sql with f-string query",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-031",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"pd\.read_sql_query\s*\(\s*f['\"]",
        function_name="pd.read_sql_query(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="pandas read_sql_query with f-string",
        cwe="CWE-89",
    ),
])

# ==============================================================================
# GO
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="go-sql-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r"\bdb\.Query\s*\(\s*fmt\.Sprintf\s*\(",
        function_name="db.Query(Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQL query built with fmt.Sprintf",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="go-sql-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r"\bdb\.Exec\s*\(\s*fmt\.Sprintf\s*\(",
        function_name="db.Exec(Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQL exec built with fmt.Sprintf",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="go-sql-003",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r"\bdb\.QueryRow\s*\(\s*fmt\.Sprintf\s*\(",
        function_name="db.QueryRow(Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQL QueryRow built with fmt.Sprintf",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="go-sql-004",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r'db\.(?:Query|Exec|QueryRow)\s*\(\s*"[^"]*"\s*\+',
        function_name="db.Query(string +)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQL query with string concatenation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="go-sql-005",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r"\bRaw\s*\(\s*fmt\.Sprintf\s*\(",
        function_name="GORM Raw(Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="GORM Raw query with Sprintf",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="go-sql-006",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r"\bWhere\s*\(\s*fmt\.Sprintf\s*\(",
        function_name="GORM Where(Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="GORM Where clause with Sprintf",
        cwe="CWE-89",
    ),
])

# ==============================================================================
# C# / .NET
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="cs-sql-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.CSHARP],
        pattern=r'new SqlCommand\s*\(\s*\$"',
        function_name="new SqlCommand($\"...\")",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SqlCommand with interpolated string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="cs-sql-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.CSHARP],
        pattern=r'CommandText\s*=\s*\$"',
        function_name="CommandText = $\"...\"",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SqlCommand.CommandText with interpolated string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="cs-sql-003",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.CSHARP],
        pattern=r'CommandText\s*=\s*"[^"]*"\s*\+',
        function_name="CommandText = concat",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SqlCommand.CommandText with concatenation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="cs-sql-004",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.CSHARP],
        pattern=r"\.FromSqlRaw\s*\(\s*\$\"",
        function_name="FromSqlRaw($\"...\")",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="EF Core FromSqlRaw with interpolation",
        cwe="CWE-89",
        remediation="Use FromSqlInterpolated() instead which is safe",
    ),
    SinkPattern(
        id="cs-sql-005",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.CSHARP],
        pattern=r"\.ExecuteSqlRaw\s*\(\s*\$\"",
        function_name="ExecuteSqlRaw($\"...\")",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="EF Core ExecuteSqlRaw with interpolation",
        cwe="CWE-89",
    ),
])

# ==============================================================================
# ADDITIONAL PATTERNS -- TypeScript/JavaScript, Python, Go, Rust, Java, C#
# ==============================================================================

# -- TypeScript: TypeORM --
PATTERNS.extend([
    SinkPattern(
        id="js-sql-040",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"getRepository\(\w+\)\.query\s*\(\s*`[^`]*\$\{",
        function_name="TypeORM repository.query(`${}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="TypeORM repository.query with template literal",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-041",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"createQueryBuilder\(\).*\.where\s*\(`[^`]*\$\{",
        function_name="TypeORM .where(`${}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="TypeORM QueryBuilder where with template literal",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-042",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.createQueryRunner\(\)\.query\s*\(\s*`[^`]*\$\{",
        function_name="TypeORM queryRunner.query(`${}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="TypeORM queryRunner.query with interpolation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-043",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"dataSource\.query\s*\(\s*`[^`]*\$\{",
        function_name="TypeORM dataSource.query(`${}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="TypeORM DataSource.query with template literal",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-044",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"em\.getConnection\(\)\.execute\s*\(\s*`[^`]*\$\{",
        function_name="MikroORM connection.execute(`${}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MikroORM raw connection execute with interpolation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-045",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"sql`[^`]*\$\{(?!sql`)[^}]+\}",
        function_name="sql template tag (unsafe)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="SQL template tag with raw interpolation (not sql.identifier/sql.value)",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-046",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"pg\.query\s*\(\s*`[^`]*\$\{",
        function_name="pg.query(`${}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="node-postgres pg.query with template literal",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-047",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"mysql\.(?:query|execute)\s*\(\s*`[^`]*\$\{",
        function_name="mysql.query(`${}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="mysql/mysql2 query with template literal",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-048",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"sqlite3\.(?:run|get|all|each)\s*\(\s*`[^`]*\$\{",
        function_name="sqlite3.run(`${}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="sqlite3 query with template literal",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-049",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"betterSqlite3\.prepare\s*\(\s*`[^`]*\$\{",
        function_name="better-sqlite3.prepare(`${}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="better-sqlite3 prepared statement with interpolation",
        cwe="CWE-89",
    ),
])

# -- Python: aiosqlite / asyncpg / aiomysql --
PATTERNS.extend([
    SinkPattern(
        id="py-sql-040",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bawait\s+conn\.execute\s*\(\s*f['\"]",
        function_name="await conn.execute(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Async DB execute with f-string (aiosqlite/asyncpg)",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-041",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bawait\s+conn\.fetch\s*\(\s*f['\"]",
        function_name="await conn.fetch(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="asyncpg conn.fetch with f-string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-042",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bawait\s+cursor\.execute\s*\(\s*f['\"]",
        function_name="await cursor.execute(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Async cursor execute with f-string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-043",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bdb\.execute\s*\(\s*f['\"]",
        function_name="db.execute(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Database execute with f-string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-044",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\btext\s*\([^)]*\+[^)]*\)",
        function_name="sqlalchemy.text(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQLAlchemy text() with string concatenation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-045",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bORMQuery\b.*\.filter\s*\(\s*f['\"]",
        function_name="ORMQuery.filter(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="ORM filter with f-string condition",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-046",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"peewee.*SQL\s*\(\s*f['\"]",
        function_name="peewee SQL(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Peewee raw SQL with f-string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-047",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"tortoise.*\.raw\s*\(\s*f['\"]",
        function_name="tortoise-orm raw(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Tortoise ORM raw query with f-string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-048",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"databases\.database\.execute\s*\(\s*f['\"]",
        function_name="databases.execute(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="encode/databases execute with f-string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-049",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bcassandra.*execute\s*\(\s*['\"].*%",
        function_name="cassandra.execute(% format)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Cassandra CQL with % string format",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-050",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"elasticsearch.*body\s*=\s*\{[^}]*f['\"]",
        function_name="elasticsearch query body with f-string",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Elasticsearch query constructed with f-strings",
        cwe="CWE-943",
    ),
])

# -- More Go patterns: sqlx, pgx, database/sql variations --
PATTERNS.extend([
    SinkPattern(
        id="go-sql-010",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r"\bdb\.MustExec\s*\(\s*fmt\.Sprintf\s*\(",
        function_name="sqlx.MustExec(Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="sqlx MustExec with Sprintf",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="go-sql-011",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r"\bdb\.Select\s*\([^,]+,\s*fmt\.Sprintf\s*\(",
        function_name="sqlx.Select(Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="sqlx Select with Sprintf",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="go-sql-012",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r"\bpgx.*Query\s*\(\s*context\.\w+,\s*fmt\.Sprintf\s*\(",
        function_name="pgx.Query(Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="pgx Query with Sprintf",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="go-sql-013",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r"\bdb\.NamedExec\s*\(\s*fmt\.Sprintf\s*\(",
        function_name="sqlx.NamedExec(Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="sqlx NamedExec with Sprintf",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="go-sql-014",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r"gorm.*\.Exec\s*\(\s*fmt\.Sprintf\s*\(",
        function_name="GORM.Exec(Sprintf())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="GORM Exec with Sprintf",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="go-sql-015",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r'strings\.Builder.*WriteString.*"SELECT|INSERT|UPDATE|DELETE"',
        function_name="strings.Builder SQL construction",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="SQL query built with strings.Builder",
        cwe="CWE-89",
    ),
])

# -- Rust: sqlx, diesel --
PATTERNS.extend([
    SinkPattern(
        id="rs-sql-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.RUST],
        pattern=r'sqlx::query\s*\(\s*&?format!\s*\(',
        function_name="sqlx::query(format!())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="sqlx raw query with format! macro",
        cwe="CWE-89",
        remediation="Use sqlx::query!(macro) with ? placeholders",
    ),
    SinkPattern(
        id="rs-sql-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.RUST],
        pattern=r'sqlx::query\s*\(\s*&[^\)]+\)',
        function_name="sqlx::query(&variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="sqlx::query with variable string",
        cwe="CWE-89",
        negative_patterns=[r'sqlx::query\s*\(\s*"'],
    ),
    SinkPattern(
        id="rs-sql-003",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.RUST],
        pattern=r'diesel::sql_query\s*\(\s*format!\s*\(',
        function_name="diesel::sql_query(format!())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Diesel raw SQL query with format!",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="rs-sql-004",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.RUST],
        pattern=r'diesel::sql_query\s*\(\s*&[^\)]+\)',
        function_name="diesel::sql_query(&variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Diesel raw SQL with variable",
        cwe="CWE-89",
        negative_patterns=[r'diesel::sql_query\s*\(\s*"'],
    ),
])

# -- Java: JDBC, JPA, Hibernate, Spring Data --
PATTERNS.extend([
    SinkPattern(
        id="java-sql-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.JAVA],
        pattern=r"createQuery\s*\(\s*\"[^\"]*\"\s*\+",
        function_name="createQuery(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="JPA createQuery with string concatenation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="java-sql-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.JAVA],
        pattern=r"createNativeQuery\s*\(\s*\"[^\"]*\"\s*\+",
        function_name="createNativeQuery(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="JPA createNativeQuery with concatenation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="java-sql-003",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.JAVA],
        pattern=r"Statement\.executeQuery\s*\(",
        function_name="Statement.executeQuery()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="JDBC Statement executeQuery -- use PreparedStatement",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="java-sql-004",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.JAVA],
        pattern=r"jdbcTemplate\.query\s*\(\s*\"[^\"]*\"\s*\+",
        function_name="JdbcTemplate.query(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Spring JdbcTemplate query with concatenation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="java-sql-005",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.JAVA],
        pattern=r"Session\.createSQLQuery\s*\(\s*\"[^\"]*\"\s*\+",
        function_name="Hibernate createSQLQuery(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Hibernate createSQLQuery with concatenation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="java-sql-006",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.JAVA],
        pattern=r"@Query\s*\(\s*value\s*=\s*\"[^\"]*\"\s*\+",
        function_name="Spring @Query with concat",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Spring Data @Query annotation value with concatenation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="java-sql-007",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.JAVA],
        pattern=r"String\.format\s*\(\s*\"(?:SELECT|INSERT|UPDATE|DELETE|FROM|WHERE)[^\"]*\",",
        function_name="String.format(SQL query)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQL query built with String.format",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="java-sql-008",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.JAVA],
        pattern=r"mongoOps\.find\s*\(.*Query\.query\s*\(",
        function_name="MongoOperations.find(Query)",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="Spring Data MongoDB find -- verify query source",
        cwe="CWE-943",
    ),
    SinkPattern(
        id="java-sql-009",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.JAVA],
        pattern=r'"(?:SELECT|INSERT|UPDATE|DELETE)[^"]*"\s*\+\s*\w+',
        function_name="SQL string + variable",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SQL string literal concatenated with variable",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="java-sql-010",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.JAVA],
        pattern=r"conn\.prepareStatement\s*\([^)]*\+",
        function_name="prepareStatement(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PreparedStatement with concatenated SQL",
        cwe="CWE-89",
    ),
])

# -- PHP patterns for completeness --
PATTERNS.extend([
    SinkPattern(
        id="php-sql-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PHP],
        pattern=r"\$(?:mysqli|pdo|db).*query\s*\(\s*\"[^\"]*\"\s*\.",
        function_name="mysqli/PDO query(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP DB query with string concatenation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="php-sql-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PHP],
        pattern=r"mysql_query\s*\(",
        function_name="mysql_query()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Deprecated mysql_query -- no parameterization",
        cwe="CWE-89",
        tags=["deprecated"],
    ),
])

PATTERN_COUNT = len(PATTERNS)

