"""
Web vulnerability patterns -- XSS, CSRF, ReDoS, Mass Assignment, gRPC injection.
Also covers many additional framework-specific patterns.
"""

from mcpsec.static.patterns.base import (
    SinkPattern, Language, VulnType, Severity, Confidence
)

PATTERNS: list[SinkPattern] = []

# ==============================================================================
# COMMAND INJECTION -- many more framework-specific patterns
# ==============================================================================

# Python async frameworks
PATTERNS.extend([
    SinkPattern(
        id="py-cmdi-fw-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"asyncio\.create_subprocess_shell\s*\(",
        function_name="asyncio.create_subprocess_shell()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="asyncio.create_subprocess_shell -- full shell, injection risk",
        cwe="CWE-78",
        remediation="Use create_subprocess_exec() with argument list",
    ),
    SinkPattern(
        id="py-cmdi-fw-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"asyncio\.create_subprocess_exec\s*\(\s*[^'\"\[\s][^,)]*,.*format\s*\(",
        function_name="asyncio.create_subprocess_exec(format())",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="asyncio.create_subprocess_exec with format() in args",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmdi-fw-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"paramiko\.exec_command\s*\(\s*f['\"]",
        function_name="SSHClient.exec_command(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Paramiko SSH exec_command with f-string",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmdi-fw-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"paramiko\.exec_command\s*\([^)]*\+",
        function_name="SSHClient.exec_command(concat)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Paramiko SSH exec_command with concatenation",
        cwe="CWE-78",
        negative_patterns=[r"exec_command\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-cmdi-fw-005",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"invoke\.run\s*\(\s*f['\"]",
        function_name="invoke.run(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Invoke task runner with f-string command",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmdi-fw-006",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"\bplumbum\b.*\[f['\"]",
        function_name="plumbum command[f-string]",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Plumbum command execution with f-string",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmdi-fw-007",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"sh\.\w+\s*\(\s*f['\"]",
        function_name="sh.cmd(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="sh library command with f-string argument",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="py-cmdi-fw-008",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"commands\.getoutput\s*\(",
        function_name="commands.getoutput()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Deprecated commands.getoutput -- shell injection",
        cwe="CWE-78",
        tags=["deprecated"],
    ),
])

# TypeScript/JS -- more Node.js patterns
PATTERNS.extend([
    SinkPattern(
        id="js-cmdi-fw-001",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"require\s*\(\s*['\"]child_process['\"].*\)\.",
        function_name="require('child_process').*",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="child_process module usage -- check exec/spawn calls",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmdi-fw-002",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"(?:await\s+)?execAsync\s*\(\s*`[^`]*\$\{",
        function_name="execAsync(`${...}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Promisified exec with template literal",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmdi-fw-003",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"util\.promisify\s*\(\s*exec\s*\)",
        function_name="util.promisify(exec)",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="Promisified exec -- check subsequent calls",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmdi-fw-004",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"import\s+\{[^}]*exec[^}]*\}\s+from\s+['\"]child_process['\"]",
        function_name="import {exec} from 'child_process'",
        severity=Severity.LOW,
        confidence=Confidence.LOW,
        description="child_process exec import -- track usage",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmdi-fw-005",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"bun\.spawnSync\s*\(",
        function_name="Bun.spawnSync()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Bun.spawnSync -- check command source",
        cwe="CWE-78",
    ),
    SinkPattern(
        id="js-cmdi-fw-006",
        vuln_type=VulnType.COMMAND_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"bun\.\$`[^`]*\$\{",
        function_name="Bun.$`${cmd}`",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Bun shell template tag with interpolation",
        cwe="CWE-78",
    ),
])

# ==============================================================================
# PATH TRAVERSAL -- more framework-specific
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-path-fw-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"aiofiles\.open\s*\(\s*f['\"]",
        function_name="aiofiles.open(f-string)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="aiofiles async open with f-string path",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="py-path-fw-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"aiofiles\.open\s*\([^)]*\+[^)]*\)",
        function_name="aiofiles.open(concat)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="aiofiles async open with concatenated path",
        cwe="CWE-22",
        negative_patterns=[r"aiofiles\.open\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-path-fw-003",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"FileResponse\s*\(\s*[^'\"\s][^,)]*\)",
        function_name="FileResponse(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="FastAPI/Starlette FileResponse with variable path",
        cwe="CWE-22",
        negative_patterns=[r"FileResponse\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-path-fw-004",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"StaticFiles\s*\(\s*directory\s*=\s*[^'\"\s][^,)]*\)",
        function_name="StaticFiles(directory=variable)",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="FastAPI StaticFiles with variable directory",
        cwe="CWE-22",
        negative_patterns=[r"directory\s*=\s*['\"]"],
    ),
    SinkPattern(
        id="py-path-fw-005",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"tarfile\.extractall\s*\(",
        function_name="tarfile.extractall()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="tarfile.extractall -- zip slip, path traversal in archives",
        cwe="CWE-22",
        tags=["zipslip"],
    ),
    SinkPattern(
        id="py-path-fw-006",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.PYTHON],
        pattern=r"zipfile\.ZipFile.*extract\s*\(",
        function_name="ZipFile.extract()",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="zipfile extraction without path validation -- zip slip",
        cwe="CWE-22",
        tags=["zipslip"],
    ),
    SinkPattern(
        id="js-path-fw-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"express\.static\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="express.static(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="express.static() with variable directory",
        cwe="CWE-22",
        negative_patterns=[r"express\.static\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-path-fw-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.pipe\s*\(\s*fs\.createWriteStream\s*\(\s*[^'\"`\s][^)]*\)",
        function_name=".pipe(createWriteStream(variable))",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="Stream pipe to createWriteStream with variable path",
        cwe="CWE-22",
        negative_patterns=[r"createWriteStream\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-path-fw-003",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"adm-zip|adm_zip.*extract\s*\(",
        function_name="AdmZip.extract()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="AdmZip extraction -- check for zip slip",
        cwe="CWE-22",
    ),
    SinkPattern(
        id="go-path-fw-001",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.GO],
        pattern=r"archive/zip.*File.*Open\s*\(",
        function_name="zip.File.Open()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Go zip file extraction -- check for zip slip",
        cwe="CWE-22",
    ),
])

# ==============================================================================
# SSRF -- more patterns
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-ssrf-fw-001",
        vuln_type=VulnType.SSRF,
        languages=[Language.PYTHON],
        pattern=r"grpc\.insecure_channel\s*\(\s*[^'\"\s][^)]*\)",
        function_name="grpc.insecure_channel(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="gRPC channel to variable address -- SSRF",
        cwe="CWE-918",
        negative_patterns=[r"grpc\.insecure_channel\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-ssrf-fw-002",
        vuln_type=VulnType.SSRF,
        languages=[Language.PYTHON],
        pattern=r"grpc\.secure_channel\s*\(\s*[^'\"\s][^,)]*",
        function_name="grpc.secure_channel(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="gRPC secure channel to variable address",
        cwe="CWE-918",
        negative_patterns=[r"grpc\.secure_channel\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-ssrf-fw-003",
        vuln_type=VulnType.SSRF,
        languages=[Language.PYTHON],
        pattern=r"pika\.BlockingConnection\s*\(\s*pika\.ConnectionParameters\s*\(\s*host\s*=\s*[^'\"\s]",
        function_name="pika.ConnectionParameters(host=variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="RabbitMQ/pika connection to variable host",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="py-ssrf-fw-004",
        vuln_type=VulnType.SSRF,
        languages=[Language.PYTHON],
        pattern=r"redis\.Redis\s*\(\s*host\s*=\s*[^'\"\s][^,)]*",
        function_name="redis.Redis(host=variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Redis connection to variable host",
        cwe="CWE-918",
        negative_patterns=[r"host\s*=\s*['\"]"],
    ),
    SinkPattern(
        id="py-ssrf-fw-005",
        vuln_type=VulnType.SSRF,
        languages=[Language.PYTHON],
        pattern=r"smtp(?:lib)?\.SMTP\s*\(\s*[^'\"\s][^,)]*",
        function_name="smtplib.SMTP(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="SMTP connection to variable host",
        cwe="CWE-918",
        negative_patterns=[r"SMTP\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="js-ssrf-fw-001",
        vuln_type=VulnType.SSRF,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"new\s+URL\s*\(\s*[^'\"`\s][^)]*\).*fetch",
        function_name="new URL(variable) + fetch",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="URL constructed from variable then used in fetch",
        cwe="CWE-918",
        negative_patterns=[r"new\s+URL\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-ssrf-fw-002",
        vuln_type=VulnType.SSRF,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"https?\.request\s*\(\s*\{[^}]*host(?:name)?\s*:(?!.*['\"][a-zA-Z0-9][a-zA-Z0-9.]*['\"])[^}]*\}",
        function_name="https.request({hostname: variable})",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Node.js http.request with variable hostname",
        cwe="CWE-918",
    ),
    SinkPattern(
        id="go-ssrf-fw-001",
        vuln_type=VulnType.SSRF,
        languages=[Language.GO],
        pattern=r"grpc\.Dial\s*\(\s*[^\"'][^,)]*",
        function_name="grpc.Dial(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="gRPC Dial to variable address",
        cwe="CWE-918",
        negative_patterns=[r"grpc\.Dial\s*\(\s*\""],
    ),
    SinkPattern(
        id="go-ssrf-fw-002",
        vuln_type=VulnType.SSRF,
        languages=[Language.GO],
        pattern=r"http\.Get\s*\(\s*fmt\.Sprintf\s*\([^)]*,",
        function_name="http.Get(fmt.Sprintf(...))",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="HTTP GET with Sprintf-built URL",
        cwe="CWE-918",
    ),
])

# ==============================================================================
# NOSQL INJECTION -- more patterns
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-nosql-001",
        vuln_type=VulnType.NOSQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"collection\.find\s*\(\s*\{[^}]*\$where",
        function_name="collection.find({$where})",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PyMongo $where operator -- JavaScript execution",
        cwe="CWE-943",
    ),
    SinkPattern(
        id="py-nosql-002",
        vuln_type=VulnType.NOSQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"collection\.find\s*\(\s*json\.loads\s*\(",
        function_name="collection.find(json.loads(user))",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PyMongo find from JSON.loads -- operator injection",
        cwe="CWE-943",
    ),
    SinkPattern(
        id="py-nosql-003",
        vuln_type=VulnType.NOSQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"db\.\w+\.find_one\s*\(\s*[^{'\"\s)][^)]*\)",
        function_name="db.collection.find_one(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="PyMongo find_one with non-dict query",
        cwe="CWE-943",
        negative_patterns=[r"find_one\s*\(\s*[{'\"]"],
    ),
    SinkPattern(
        id="js-nosql-004",
        vuln_type=VulnType.NOSQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.findOne\s*\(\s*JSON\.parse\s*\(",
        function_name=".findOne(JSON.parse(user))",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Mongoose findOne from parsed JSON",
        cwe="CWE-943",
    ),
    SinkPattern(
        id="js-nosql-005",
        vuln_type=VulnType.NOSQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"mongoose\.model\s*\(\s*\w+\s*\)\.find\s*\(\s*req\.",
        function_name="Model.find(req.body)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Mongoose find with req body directly",
        cwe="CWE-943",
    ),
    SinkPattern(
        id="js-nosql-006",
        vuln_type=VulnType.NOSQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"collection\.findOne\s*\(\s*\{.*\$gt\s*:",
        function_name="collection.findOne({$gt: ...})",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="MongoDB $gt operator in query -- check if user-supplied",
        cwe="CWE-943",
    ),
    SinkPattern(
        id="js-nosql-007",
        vuln_type=VulnType.NOSQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"collection\.aggregate\s*\(\s*\[.*\$function",
        function_name="collection.aggregate([$function])",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MongoDB $function aggregation -- server-side JS",
        cwe="CWE-943",
    ),
])

# ==============================================================================
# XML/XXE -- more patterns
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-xxe-ext-001",
        vuln_type=VulnType.XXE,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"cheerio\.load\s*\(\s*[^'\"`\s][^,)]*",
        function_name="cheerio.load(variable)",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="Cheerio HTML/XML parser -- check for XML with entities",
        cwe="CWE-611",
        negative_patterns=[r"cheerio\.load\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="py-xxe-ext-001",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern=r"\bElementTree\b.*fromstring\s*\(",
        function_name="ElementTree.fromstring()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="ElementTree fromstring -- billion laughs vulnerable",
        cwe="CWE-611",
    ),
    SinkPattern(
        id="py-xxe-ext-002",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern=r"untangle\.parse\s*\(",
        function_name="untangle.parse()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="untangle XML parser -- check entity settings",
        cwe="CWE-611",
    ),
    SinkPattern(
        id="py-xxe-ext-003",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern=r"pyexpat.*ExpatError|xml\.parsers\.expat",
        function_name="pyexpat parser",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="pyexpat XML parser -- DTD processing",
        cwe="CWE-611",
    ),
])

# ==============================================================================
# DESERIALIZATION -- more patterns
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-deser-fw-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern=r"msgpack\.unpackb\s*\(",
        function_name="msgpack.unpackb()",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="msgpack.unpackb -- check raw/strict_map options",
        cwe="CWE-502",
    ),
    SinkPattern(
        id="py-deser-fw-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern=r"torch\.load\s*\(",
        function_name="torch.load()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PyTorch torch.load -- arbitrary code via pickle",
        cwe="CWE-502",
        tags=["mlsec"],
    ),
    SinkPattern(
        id="py-deser-fw-003",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern=r"numpy\.load\s*\([^)]*allow_pickle\s*=\s*True",
        function_name="numpy.load(allow_pickle=True)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="NumPy load with allow_pickle=True -- code execution",
        cwe="CWE-502",
        tags=["mlsec"],
    ),
    SinkPattern(
        id="py-deser-fw-004",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.PYTHON],
        pattern=r"joblib\.load\s*\(",
        function_name="joblib.load()",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="joblib.load -- uses pickle, arbitrary code",
        cwe="CWE-502",
        tags=["mlsec"],
    ),
    SinkPattern(
        id="js-deser-fw-001",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"flatted\.parse\s*\(",
        function_name="flatted.parse()",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="flatted.parse -- check for prototype pollution",
        cwe="CWE-502",
    ),
    SinkPattern(
        id="js-deser-fw-002",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"qs\.parse\s*\(\s*[^'\"`\s][^,)]*",
        function_name="qs.parse(variable)",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="qs.parse with user input -- prototype pollution via __proto__",
        cwe="CWE-1321",
        negative_patterns=[r"qs\.parse\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-deser-fw-003",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"_.merge\s*\(\s*\{\s*\},\s*[^'\"`\s][^)]*\)",
        function_name="_.merge({}, variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Lodash _.merge with user input -- prototype pollution < 4.17.5",
        cwe="CWE-1321",
        tags=["known-vuln"],
    ),
    SinkPattern(
        id="js-deser-fw-004",
        vuln_type=VulnType.DESERIALIZATION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"extend\s*\(true,\s*\{\s*\},\s*[^'\"`\s][^)]*\)",
        function_name="extend(true, {}, variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="jQuery.extend deep with user input -- prototype pollution",
        cwe="CWE-1321",
    ),
])

# ==============================================================================
# TEMPLATE INJECTION -- more patterns
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-tpl-fw-001",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"Template\s*\(\s*[^'\"\s][^)]*\)\.safe_substitute",
        function_name="Template(variable).safe_substitute()",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="string.Template from variable input",
        cwe="CWE-94",
        negative_patterns=[r"Template\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="py-tpl-fw-002",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"chevron\.render\s*\(\s*[^'\"\s][^,)]*",
        function_name="chevron.render(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="chevron Mustache render from variable template",
        cwe="CWE-94",
        negative_patterns=[r"chevron\.render\s*\(\s*['\"]"],
    ),
    SinkPattern(
        id="js-tpl-fw-001",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"doT\.template\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="doT.template(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="doT.js template from user input -- SSTI",
        cwe="CWE-94",
        negative_patterns=[r"doT\.template\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-tpl-fw-002",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"art\.compile\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="art-template.compile(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="art-template compile with user input",
        cwe="CWE-94",
        negative_patterns=[r"compile\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-tpl-fw-003",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"_.template\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="_.template(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Lodash _.template with user input -- SSTI/code execution",
        cwe="CWE-94",
        negative_patterns=[r"_.template\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-tpl-fw-004",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"mustache\.render\s*\(\s*[^'\"`\s][^,)]*",
        function_name="mustache.render(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Mustache render from user template",
        cwe="CWE-94",
        negative_patterns=[r"mustache\.render\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-tpl-fw-005",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"vm2\.Script\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="vm2.Script(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="vm2 Script with user input -- sandbox escape known",
        cwe="CWE-94",
        tags=["known-vuln"],
        negative_patterns=[r"vm2\.Script\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-tpl-fw-006",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"isolated-vm.*Script\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="isolated-vm Script(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="isolated-vm Script from user input",
        cwe="CWE-94",
        negative_patterns=[r"Script\s*\(\s*['\"`]"],
    ),
])

# ==============================================================================
# CRYPTO WEAKNESS -- more patterns
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-crypto-hw-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"crypto\.createCipher\s*\(",
        function_name="crypto.createCipher() -- deprecated",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="Node.js crypto.createCipher -- deprecated, uses null IV",
        cwe="CWE-327",
        tags=["deprecated"],
    ),
    SinkPattern(
        id="js-crypto-hw-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"createHmac\s*\(\s*['\"]md5['\"]",
        function_name="createHmac('md5')",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="HMAC with MD5 -- weak hash",
        cwe="CWE-327",
    ),
    SinkPattern(
        id="js-crypto-hw-003",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"createHmac\s*\(\s*['\"]sha1['\"]",
        function_name="createHmac('sha1')",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="HMAC with SHA-1 -- weak hash",
        cwe="CWE-327",
    ),
    SinkPattern(
        id="py-crypto-hw-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern=r"SSL_PROTOCOL_SSLv2|SSLContext.*PROTOCOL_SSLv2",
        function_name="SSLv2 protocol",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="SSLv2 protocol -- critically vulnerable",
        cwe="CWE-326",
    ),
    SinkPattern(
        id="py-crypto-hw-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern=r"hmac\.new\s*\([^,]+,\s*[^,]+,\s*hashlib\.md5\s*\)",
        function_name="hmac.new(key, msg, md5)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="HMAC with MD5",
        cwe="CWE-327",
    ),
    SinkPattern(
        id="go-crypto-hw-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern=r"hmac\.New\s*\(\s*md5\.New\b",
        function_name="hmac.New(md5.New)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="HMAC with MD5",
        cwe="CWE-327",
    ),
    SinkPattern(
        id="go-crypto-hw-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern=r"\btls\.Config\s*\{[^}]*MaxVersion\s*:\s*tls\.VersionTLS10\b",
        function_name="tls.Config{MaxVersion: TLS1.0}",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="TLS max version set to TLS 1.0 -- weak",
        cwe="CWE-326",
    ),
    SinkPattern(
        id="go-crypto-hw-003",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.GO],
        pattern=r"rand\.Read\s*\((?!.*crypto/rand)",
        function_name="rand.Read (math/rand)",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="Non-crypto rand.Read",
        cwe="CWE-338",
    ),
])

# ==============================================================================
# SQL INJECTION -- more driver-specific patterns
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="py-sql-ext-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"psycopg2\.connect\(\).*cursor\(\)\.execute\s*\(\s*f['\"]",
        function_name="psycopg2 cursor.execute(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="psycopg2 cursor execute with f-string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-ext-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"pymysql.*cursor\(\)\.execute\s*\(\s*f['\"]",
        function_name="PyMySQL cursor.execute(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PyMySQL cursor execute with f-string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-ext-003",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"sqlite3\.connect\(\).*execute\s*\(\s*f['\"]",
        function_name="sqlite3 execute(f-string)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="sqlite3 execute with f-string",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="py-sql-ext-004",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"motor\.motor_asyncio.*find\s*\(\s*\{.*\$where",
        function_name="Motor MongoDB find({$where})",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Motor async MongoDB $where operator",
        cwe="CWE-943",
    ),
    SinkPattern(
        id="js-sql-ext-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"Sequelize\.literal\s*\(\s*[^'\"`\s][^)]*\)",
        function_name="Sequelize.literal(variable)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Sequelize.literal with variable -- SQL injection",
        cwe="CWE-89",
        negative_patterns=[r"Sequelize\.literal\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-sql-ext-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"Sequelize\.literal\s*\(\s*`[^`]*\$\{",
        function_name="Sequelize.literal(`${}`)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="Sequelize.literal with template literal",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="js-sql-ext-003",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"\.orderBy\s*\(\s*[^'\"`\s][^,)]*,",
        function_name=".orderBy(variable)",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="DB orderBy with variable column -- SQL injection in sort",
        cwe="CWE-89",
        negative_patterns=[r"\.orderBy\s*\(\s*['\"`]"],
    ),
    SinkPattern(
        id="js-sql-ext-004",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"drizzle.*sql`[^`]*\$\{(?!sql|[a-z]+`)",
        function_name="drizzle sql`${}`",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Drizzle ORM sql template with unsafe interpolation",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="go-sql-ext-001",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r"squirrel.*ToSql\s*\(\s*\)",
        function_name="squirrel.ToSql()",
        severity=Severity.LOW,
        confidence=Confidence.LOW,
        description="squirrel SQL builder -- check dynamic conditions",
        cwe="CWE-89",
    ),
    SinkPattern(
        id="go-sql-ext-002",
        vuln_type=VulnType.SQL_INJECTION,
        languages=[Language.GO],
        pattern=r"bun\.\w+\s*\(\s*\"[^\"]*\?\"\s*,\s*\w+\s*\+",
        function_name="bun.DB.query(concat args)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="go-bun DB query with concatenated argument",
        cwe="CWE-89",
    ),
])

# ==============================================================================
# JWT WEAK SIGNING -- Security misconfiguration
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="js-jwt-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"jwt\.sign\s*\([^,]+,\s*['\"][^'\"]{1,15}['\"]",
        function_name="jwt.sign(payload, short_secret)",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="JWT signed with short/weak secret",
        cwe="CWE-326",
    ),
    SinkPattern(
        id="js-jwt-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"jwt\.sign\s*\([^,]+,\s*['\"]['\"]",
        function_name="jwt.sign(payload, '')",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="JWT signed with empty secret",
        cwe="CWE-326",
    ),
    SinkPattern(
        id="js-jwt-003",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"jwt\.verify\s*\([^,]+,\s*[^,)]*algorithm.*none",
        function_name="jwt.verify(token, ..., {algorithm: none})",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="JWT verify with 'none' algorithm -- authentication bypass",
        cwe="CWE-327",
        tags=["known-vuln"],
    ),
    SinkPattern(
        id="py-jwt-001",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern=r"jwt\.decode\s*\([^,]+,\s*[^,]+,\s*algorithms\s*=\s*\[\s*['\"]none['\"]\s*\]",
        function_name="jwt.decode(token, ..., algorithms=['none'])",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PyJWT decode with 'none' algorithm",
        cwe="CWE-327",
    ),
    SinkPattern(
        id="py-jwt-002",
        vuln_type=VulnType.CRYPTO,
        languages=[Language.PYTHON],
        pattern=r"jwt\.decode\s*\([^,]+,\s*options\s*=\s*\{[^}]*verify_signature\s*:\s*False",
        function_name="jwt.decode(verify_signature=False)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PyJWT disabled signature verification",
        cwe="CWE-347",
    ),
])

# ==============================================================================
# PHP EVAL / DYNAMIC EXECUTION
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="php-eval-001",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PHP],
        pattern=r"\beval\s*\(\s*\$(?:_GET|_POST|_REQUEST|_COOKIE)",
        function_name="eval($_GET)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP eval with user-supplied code -- direct RCE",
        cwe="CWE-94",
    ),
    SinkPattern(
        id="php-eval-002",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PHP],
        pattern=r"preg_replace\s*\(\s*['\"][^'\"]*e['\"]",
        function_name="preg_replace(/pattern/e, ...)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP preg_replace with /e modifier -- code execution",
        cwe="CWE-94",
        tags=["deprecated"],
    ),
    SinkPattern(
        id="php-eval-003",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PHP],
        pattern=r"create_function\s*\(\s*\$",
        function_name="create_function($args, $body)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP create_function with variable -- RCE",
        cwe="CWE-94",
        tags=["deprecated"],
    ),
    SinkPattern(
        id="php-eval-004",
        vuln_type=VulnType.CODE_EXECUTION,
        languages=[Language.PHP],
        pattern=r"assert\s*\(\s*\$(?:_GET|_POST|_REQUEST)",
        function_name="assert($_GET)",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="PHP assert with user input -- RCE in PHP 5",
        cwe="CWE-94",
    ),
])

# ==============================================================================
# MCP-Specific Prompt Injection via Resources
# ==============================================================================

PATTERNS.extend([
    SinkPattern(
        id="mcp-resource-001",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"server\.resource\s*\([^)]+,\s*async\s*\([^)]*\)\s*=>\s*\{[^}]*`[^`]*\$\{",
        function_name="server.resource handler -> template literal",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="MCP resource handler with template literal -- prompt injection risk",
        cwe="CWE-94",
        tags=["mcp", "resource-handler"],
    ),
    SinkPattern(
        id="mcp-resource-002",
        vuln_type=VulnType.PATH_TRAVERSAL,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"server\.resource\s*\([^)]+,\s*async\s*\([^)]*\)\s*=>\s*\{[^}]*readFile\s*\(",
        function_name="server.resource handler -> readFile()",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="MCP resource handler with readFile -- path traversal risk",
        cwe="CWE-22",
        tags=["mcp", "resource-handler"],
    ),
    SinkPattern(
        id="mcp-prompt-inj-001",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern=r"server\.prompt\s*\([^)]+,\s*async\s*\([^)]*\)\s*=>\s*\{[^}]*`[^`]*\$\{",
        function_name="server.prompt handler -> template literal",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MCP prompt handler with interpolated content -- prompt injection",
        cwe="CWE-94",
        tags=["mcp", "prompt-injection"],
    ),
    SinkPattern(
        id="mcp-prompt-inj-002",
        vuln_type=VulnType.TEMPLATE_INJECTION,
        languages=[Language.PYTHON],
        pattern=r"@mcp\.prompt\b.*\ndef\s+\w+.*f['\"]",
        function_name="@mcp.prompt handler with f-string",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="MCP Python prompt handler with f-string -- prompt injection",
        cwe="CWE-94",
        tags=["mcp", "prompt-injection"],
    ),
])

PATTERN_COUNT = len(PATTERNS)
