import re
from mcpsec.static.patterns.base import SinkPattern, VulnType, Language, Severity, Confidence

PATTERNS = [
    SinkPattern(
        id="java-xxe-001",
        vuln_type=VulnType.XXE,
        languages=[Language.JAVA],
        pattern='DocumentBuilderFactory\\.newInstance\\s*\\(\\s*\\)',
        function_name='DocumentBuilderFactory.newInstance()',
        description='JAX DocumentBuilderFactory without entity disabling',
        cwe='CWE-611',
        remediation='Call dbf.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true)',
    ),
    SinkPattern(
        id="java-xxe-002",
        vuln_type=VulnType.XXE,
        languages=[Language.JAVA],
        pattern='SAXParserFactory\\.newInstance\\s*\\(\\s*\\)',
        function_name='SAXParserFactory.newInstance()',
        description='SAX parser without external entity disabling',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="java-xxe-003",
        vuln_type=VulnType.XXE,
        languages=[Language.JAVA],
        pattern='XMLInputFactory\\.newInstance\\s*\\(\\s*\\)',
        function_name='XMLInputFactory.newInstance()',
        description='StAX XMLInputFactory -- check entity settings',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="cs-xxe-001",
        vuln_type=VulnType.XXE,
        languages=[Language.CSHARP],
        pattern='XmlDocument\\s*\\(\\s*\\)\\.Load\\s*\\(',
        function_name='XmlDocument.Load()',
        description='C# XmlDocument.Load -- check ProhibitDtd',
        cwe='CWE-611',
        remediation='Set XmlDocument.XmlResolver = null',
    ),
    SinkPattern(
        id="cs-xxe-002",
        vuln_type=VulnType.XXE,
        languages=[Language.CSHARP],
        pattern='XDocument\\.Load\\s*\\(',
        function_name='XDocument.Load()',
        description='C# XDocument.Load -- check DTD settings',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="go-xxe-001",
        vuln_type=VulnType.XXE,
        languages=[Language.GO],
        pattern='xml\\.Unmarshal\\s*\\(',
        function_name='xml.Unmarshal()',
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description="Go xml.Unmarshal -- Go's stdlib is not XXE vulnerable, but check custom parsers",
        cwe='CWE-611',
    ),
    SinkPattern(
        id="rs-xxe-001",
        vuln_type=VulnType.XXE,
        languages=[Language.RUST],
        pattern='quick_xml::Reader::from_str\\s*\\(',
        function_name='quick_xml::Reader::from_str()',
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description='quick_xml parser -- verify entity expansion settings',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="py-xxe-etree-001",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='ET\\.fromstring\\s*\\(\\s*(?![\\"\\\'])[a-zA-Z_]\\w*',
        function_name='ET.fromstring(variable)',
        description='XML parsing without disabling external entities',
        cwe='CWE-611',
        remediation='Use defusedxml library or disable external entity processing',
    ),
    SinkPattern(
        id="py-xxe-etree-002",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='xml\\.etree\\.ElementTree\\.fromstring\\s*\\(',
        function_name='xml.etree.ElementTree.fromstring()',
        description='XML parsing with default parser - XXE possible',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="php-xxe-001",
        vuln_type=VulnType.XXE,
        languages=[Language.PHP],
        pattern='simplexml_load_string\\s*\\(\\s*\\$(?:_GET|_POST|_REQUEST)',
        function_name='simplexml_load_string($_GET)',
        confidence=Confidence.HIGH,
        description='PHP simplexml_load_string with user input',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="php-xxe-002",
        vuln_type=VulnType.XXE,
        languages=[Language.PHP],
        pattern='new\\s+DOMDocument\\s*\\(\\s*\\).*loadXML\\s*\\(',
        function_name='DOMDocument.loadXML()',
        description='PHP DOMDocument loadXML -- XXE if entity expansion enabled',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="js-xxe-ext-001",
        vuln_type=VulnType.XXE,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='cheerio\\.load\\s*\\(\\s*[^\'\\"`\\s][^,)]*',
        function_name='cheerio.load(variable)',
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description='Cheerio HTML/XML parser -- check for XML with entities',
        cwe='CWE-611',
        negative_patterns=['cheerio\\.load\\s*\\(\\s*[\'\\"`]'],
    ),
    SinkPattern(
        id="py-xxe-ext-001",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='\\bElementTree\\b.*fromstring\\s*\\(',
        function_name='ElementTree.fromstring()',
        description='ElementTree fromstring -- billion laughs vulnerable',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="py-xxe-ext-002",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='untangle\\.parse\\s*\\(',
        function_name='untangle.parse()',
        description='untangle XML parser -- check entity settings',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="py-xxe-ext-003",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='pyexpat.*ExpatError|xml\\.parsers\\.expat',
        function_name='pyexpat parser',
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description='pyexpat XML parser -- DTD processing',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="py-xxe-001",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='\\blxml\\.etree\\.parse\\s*\\(',
        function_name='lxml.etree.parse()',
        description='lxml.etree.parse -- XXE enabled by default',
        cwe='CWE-611',
        remediation='Use defusedxml or disable entity resolution: parser = etree.XMLParser(no_network=True, resolve_entities=False)',
    ),
    SinkPattern(
        id="py-xxe-002",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='\\blxml\\.etree\\.fromstring\\s*\\(',
        function_name='lxml.etree.fromstring()',
        description='lxml.etree.fromstring -- XXE-capable parser',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="py-xxe-003",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='\\bxml\\.etree\\.ElementTree\\.parse\\s*\\(',
        function_name='xml.etree.ElementTree.parse()',
        description='stdlib XML parser -- vulnerable to billion laughs attack',
        cwe='CWE-611',
        remediation='Use defusedxml.ElementTree instead',
    ),
    SinkPattern(
        id="py-xxe-004",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='\\bxml\\.etree\\.ElementTree\\.fromstring\\s*\\(',
        function_name='xml.etree.ElementTree.fromstring()',
        description='stdlib XML fromstring -- vulnerable to entity expansion',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="py-xxe-005",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='\\bxml\\.sax\\.parseString\\s*\\(',
        function_name='xml.sax.parseString()',
        description='xml.sax.parseString -- external entity processing',
        cwe='CWE-611',
        remediation='Use defusedxml.sax instead',
    ),
    SinkPattern(
        id="py-xxe-006",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='\\bxml\\.dom\\.minidom\\.parseString\\s*\\(',
        function_name='xml.dom.minidom.parseString()',
        description='minidom parseString -- XXE vulnerable',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="py-xxe-007",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='\\bxml\\.dom\\.minidom\\.parse\\s*\\(',
        function_name='xml.dom.minidom.parse()',
        description='minidom parse -- XXE vulnerable',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="py-xxe-008",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='\\bxmltodict\\.parse\\s*\\(',
        function_name='xmltodict.parse()',
        severity=Severity.MEDIUM,
        description='xmltodict.parse -- check XML library used underneath',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="py-xxe-009",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='\\bBeautifulSoup\\s*\\([^)]*[\'\\"]xml[\'\\"]',
        function_name="BeautifulSoup(html, 'xml')",
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description='BeautifulSoup with xml parser -- check lxml usage',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="py-xxe-010",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='\\breturn\\s*etree\\.XMLParser\\s*\\([^)]*\\)\\s*(?!.*no_network|.*resolve_entities)',
        function_name='etree.XMLParser() without safety flags',
        description='lxml XMLParser without security restrictions',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="py-xxe-011",
        vuln_type=VulnType.XXE,
        languages=[Language.PYTHON],
        pattern='etree\\.XMLParser\\s*\\(\\s*\\)',
        function_name='etree.XMLParser() default',
        confidence=Confidence.HIGH,
        description='etree.XMLParser with no args -- entity resolution enabled by default',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="js-xxe-001",
        vuln_type=VulnType.XXE,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='\\bxml2js\\.parseString\\s*\\(',
        function_name='xml2js.parseString()',
        severity=Severity.MEDIUM,
        confidence=Confidence.LOW,
        description='xml2js.parseString -- XXE depends on configuration',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="js-xxe-002",
        vuln_type=VulnType.XXE,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='\\bfxp\\.XMLParser\\s*\\(\\s*\\{[^}]*(?!processEntities\\s*:\\s*false)[^}]*\\}',
        function_name='fast-xml-parser without processEntities:false',
        description='fast-xml-parser without disabling entity processing',
        cwe='CWE-611',
        remediation='Set processEntities: false in fast-xml-parser options',
    ),
    SinkPattern(
        id="js-xxe-003",
        vuln_type=VulnType.XXE,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='\\bnew\\s+fxp\\.XMLParser\\s*\\(\\s*\\)',
        function_name='new XMLParser() defaults',
        confidence=Confidence.HIGH,
        description='fast-xml-parser XMLParser with defaults -- entities enabled',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="js-xxe-004",
        vuln_type=VulnType.XXE,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='\\blibxmljs\\.parseXml\\s*\\(',
        function_name='libxmljs.parseXml()',
        description='libxmljs.parseXml -- check entity expansion settings',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="js-xxe-005",
        vuln_type=VulnType.XXE,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='\\bDOMParser\\b.*parseFromString\\s*\\(',
        function_name='DOMParser.parseFromString()',
        description='DOMParser.parseFromString -- XXE in some environments',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="js-xxe-006",
        vuln_type=VulnType.XXE,
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        pattern='\\bsax\\.createStream\\s*\\([^)]*xmlns\\s*:\\s*true',
        function_name='sax.createStream({xmlns:true})',
        severity=Severity.MEDIUM,
        description='sax stream with namespace processing',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="c-xxe-001",
        vuln_type=VulnType.XXE,
        languages=[Language.C, Language.CPP],
        pattern='\\bxmlReadMemory\\s*\\(',
        function_name='xmlReadMemory()',
        description='libxml2 xmlReadMemory -- entity substitution may be enabled',
        cwe='CWE-611',
        remediation='Set XML_PARSE_NOENT | XML_PARSE_DTDLOAD to 0',
    ),
    SinkPattern(
        id="c-xxe-002",
        vuln_type=VulnType.XXE,
        languages=[Language.C, Language.CPP],
        pattern='\\bxmlParseDoc\\s*\\(',
        function_name='xmlParseDoc()',
        description='libxml2 xmlParseDoc -- entity expansion by default',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="c-xxe-003",
        vuln_type=VulnType.XXE,
        languages=[Language.C, Language.CPP],
        pattern='\\bXML_PARSE_NOENT\\b',
        function_name='XML_PARSE_NOENT flag set',
        confidence=Confidence.HIGH,
        description='XML_PARSE_NOENT -- entity substitution explicitly enabled',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="cs-xxe-001_2",
        vuln_type=VulnType.XXE,
        languages=[Language.CSHARP],
        pattern='new\\s+XmlDocument\\s*\\(\\s*\\)',
        function_name='new XmlDocument()',
        description='XmlDocument -- DTD processing enabled by default in .NET < 4.0',
        cwe='CWE-611',
        remediation='Set XmlDocument.XmlResolver = null',
    ),
    SinkPattern(
        id="cs-xxe-002_2",
        vuln_type=VulnType.XXE,
        languages=[Language.CSHARP],
        pattern='XmlReaderSettings\\s*\\{\\s*[^}]*DtdProcessing\\s*=\\s*DtdProcessing\\.Parse',
        function_name='XmlReaderSettings{DtdProcessing.Parse}',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='XmlReader with DTD parsing enabled -- XXE',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="cs-xxe-003",
        vuln_type=VulnType.XXE,
        languages=[Language.CSHARP],
        pattern='XmlResolver\\s*=\\s*new\\s+XmlUrlResolver',
        function_name='XmlResolver = new XmlUrlResolver',
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description='XmlUrlResolver enables XXE via network requests',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="cs-xxe-004",
        vuln_type=VulnType.XXE,
        languages=[Language.CSHARP],
        pattern='XPathDocument\\s*\\(\\s*[^@\\"\'][^)]*\\)',
        function_name='XPathDocument(variable)',
        description='XPathDocument with variable -- check DTD settings',
        cwe='CWE-611',
    ),
    SinkPattern(
        id="cs-xxe-005",
        vuln_type=VulnType.XXE,
        languages=[Language.CSHARP],
        pattern='new\\s+XmlTextReader\\s*\\(',
        function_name='new XmlTextReader()',
        description='XmlTextReader -- DTD enabled by default before .NET 4.0',
        cwe='CWE-611',
    )
]
