"""
MCP framework source patterns -- identify user input entry points.

These patterns find where MCP tool parameters enter the code.
"""

from mcpsec.static.patterns.base import SourcePattern, Language

PATTERNS: list[SourcePattern] = [
    # ── MCP TypeScript SDK ──────────────────────────────────────────────────
    SourcePattern(
        id="mcp-ts-sdk-001",
        framework="mcp-typescript-sdk",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        entry_pattern=r"server\.tool\s*\(\s*['\"](\w+)['\"]",
        param_pattern=r"(?:request\.params\.)?arguments\.(\w+)",
        description="MCP TypeScript SDK server.tool() handler",
    ),
    SourcePattern(
        id="mcp-ts-sdk-002",
        framework="mcp-typescript-sdk",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        entry_pattern=r"server\.setRequestHandler\s*\(\s*CallToolRequestSchema",
        param_pattern=r"request\.params\.arguments\.(\w+)",
        description="MCP TypeScript SDK setRequestHandler",
    ),
    SourcePattern(
        id="mcp-ts-sdk-003",
        framework="mcp-typescript-sdk",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        entry_pattern=r"const\s*\{\s*(\w+)(?:\s*,\s*\w+)*\s*\}\s*=\s*(?:request\.params\.)?arguments",
        param_pattern=r"(\w+)",
        description="MCP TypeScript SDK destructured arguments",
    ),
    SourcePattern(
        id="mcp-ts-sdk-004",
        framework="mcp-typescript-sdk",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        entry_pattern=r"McpServer\s*\(",
        param_pattern=r"input\.(\w+)",
        description="McpServer high-level API input",
    ),
    SourcePattern(
        id="mcp-ts-sdk-005",
        framework="mcp-typescript-sdk",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        entry_pattern=r"server\.addTool\s*\(\s*\{",
        param_pattern=r"input\.(\w+)|args\.(\w+)",
        description="MCP TypeScript addTool input",
    ),
    SourcePattern(
        id="mcp-ts-sdk-006",
        framework="mcp-typescript-sdk",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        entry_pattern=r"\.register(?:Tool|Handler)\s*\(",
        param_pattern=r"(?:params|args|arguments)\.(\w+)",
        description="Generic registerTool pattern",
    ),

    # ── MCP Python SDK (official) ────────────────────────────────────────
    SourcePattern(
        id="mcp-py-sdk-001",
        framework="mcp-python-sdk",
        languages=[Language.PYTHON],
        entry_pattern=r"@(?:mcp|server)\.tool(?:\s*\(\s*\))?",
        param_pattern=r"arguments\[['\"](\w+)['\"]\]",
        description="MCP Python SDK @mcp.tool decorator",
    ),
    SourcePattern(
        id="mcp-py-sdk-002",
        framework="mcp-python-sdk",
        languages=[Language.PYTHON],
        entry_pattern=r"@(?:mcp|server)\.tool",
        param_pattern=r"arguments\.get\s*\(\s*['\"](\w+)['\"]",
        description="MCP Python SDK arguments.get()",
    ),
    SourcePattern(
        id="mcp-py-sdk-003",
        framework="mcp-python-sdk",
        languages=[Language.PYTHON],
        entry_pattern=r"async\s+def\s+(\w+)\s*\([^)]*ctx",
        param_pattern=r"ctx\.arguments\.(\w+)",
        description="MCP Python SDK context arguments",
    ),
    SourcePattern(
        id="mcp-py-sdk-004",
        framework="mcp-python-sdk",
        languages=[Language.PYTHON],
        entry_pattern=r"@server\.call_tool_handler",
        param_pattern=r"request\.params\.arguments\.get\s*\(\s*['\"](\w+)['\"]",
        description="MCP Python SDK call_tool_handler",
    ),

    # ── FastMCP ──────────────────────────────────────────────────────────
    SourcePattern(
        id="fastmcp-001",
        framework="fastmcp",
        languages=[Language.PYTHON],
        entry_pattern=r"@mcp\.tool\s*(?:\(\s*\))?",
        param_pattern=r"def\s+\w+\s*\([^)]*(\w+)\s*:",
        description="FastMCP tool function parameters",
    ),
    SourcePattern(
        id="fastmcp-002",
        framework="fastmcp",
        languages=[Language.PYTHON],
        entry_pattern=r"FastMCP\s*\(",
        param_pattern=r"def\s+\w+\s*\([^)]*(\w+)\s*:\s*(?:str|int|float|dict|list|Any)",
        description="FastMCP typed tool function parameters",
    ),
    SourcePattern(
        id="fastmcp-003",
        framework="fastmcp",
        languages=[Language.PYTHON],
        entry_pattern=r"@tool\s*(?:\(\s*\))?",
        param_pattern=r"def\s+\w+\s*\([^)]*(\w+)\s*:",
        description="FastMCP @tool shorthand",
    ),

    # ── MCP Go SDK ───────────────────────────────────────────────────────
    SourcePattern(
        id="mcp-go-sdk-001",
        framework="mcp-go-sdk",
        languages=[Language.GO],
        entry_pattern=r"func\s+(\w+)Handler\s*\(",
        param_pattern=r"req\.Params\.Arguments\[['\"](\w+)['\"]\]",
        description="MCP Go SDK handler function",
    ),
    SourcePattern(
        id="mcp-go-sdk-002",
        framework="mcp-go-sdk",
        languages=[Language.GO],
        entry_pattern=r"RegisterTool\s*\(\s*['\"](\w+)['\"]",
        param_pattern=r"args\[['\"](\w+)['\"]\]",
        description="MCP Go SDK RegisterTool",
    ),
    SourcePattern(
        id="mcp-go-sdk-003",
        framework="mcp-go-sdk",
        languages=[Language.GO],
        entry_pattern=r"mcp\.NewServer\s*\(",
        param_pattern=r"request\.Params\.Arguments\.(\w+)",
        description="MCP Go NewServer arguments",
    ),

    # ── Custom C implementations (r2mcp style) ───────────────────────────
    SourcePattern(
        id="mcp-c-custom-001",
        framework="mcp-c-custom",
        languages=[Language.C],
        entry_pattern=r"(?:static\s+)?(?:int|void|char\s*\*)\s+(\w*(?:tool|handle|cmd)\w*)\s*\(",
        param_pattern=r"json_object_get[^(]*\([^,]+,\s*['\"](\w+)['\"]",
        description="Custom C MCP handler with json-c",
    ),
    SourcePattern(
        id="mcp-c-custom-002",
        framework="mcp-c-custom",
        languages=[Language.C],
        entry_pattern=r"tools_call",
        param_pattern=r"params\[['\"](\w+)['\"]\]",
        description="Custom C MCP tools_call",
    ),
    SourcePattern(
        id="mcp-c-custom-003",
        framework="mcp-c-custom",
        languages=[Language.C],
        entry_pattern=r"mcp_handle_request\s*\(",
        param_pattern=r"cJSON_GetObjectItem\s*\([^,]+,\s*['\"](\w+)['\"]",
        description="Custom C MCP with cJSON",
    ),

    # ── .NET MCP ─────────────────────────────────────────────────────────
    SourcePattern(
        id="mcp-dotnet-001",
        framework="mcp-dotnet",
        languages=[Language.CSHARP],
        entry_pattern=r"\[McpTool\s*\(\s*['\"](\w+)['\"]\s*\)\]",
        param_pattern=r"request\.Arguments\[['\"](\w+)['\"]\]",
        description=".NET MCP McpTool attribute",
    ),
    SourcePattern(
        id="mcp-dotnet-002",
        framework="mcp-dotnet",
        languages=[Language.CSHARP],
        entry_pattern=r"\[Tool\s*\(\s*Name\s*=\s*['\"](\w+)['\"]\s*\)\]",
        param_pattern=r"arguments\[\"(\w+)\"\]|GetArgument<[^>]+>\(\"(\w+)\"",
        description=".NET MCP Tool attribute",
    ),

    # ── Rust MCP ─────────────────────────────────────────────────────────
    SourcePattern(
        id="mcp-rust-001",
        framework="mcp-rust-sdk",
        languages=[Language.RUST],
        entry_pattern=r"#\[tool\s*\(\s*name\s*=\s*['\"](\w+)['\"]\s*\)\]",
        param_pattern=r"args\.get\s*\(\s*['\"](\w+)['\"]",
        description="Rust MCP tool attribute",
    ),
    SourcePattern(
        id="mcp-rust-002",
        framework="mcp-rust-sdk",
        languages=[Language.RUST],
        entry_pattern=r"impl\s+Tool\s+for\s+\w+",
        param_pattern=r"params\.get\s*\(\s*['\"](\w+)['\"]",
        description="Rust MCP Tool trait implementation",
    ),

    # ── Generic patterns (fallback) ───────────────────────────────────────
    SourcePattern(
        id="mcp-generic-001",
        framework="mcp-generic",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT, Language.PYTHON],
        entry_pattern=r"(?:tool|handle|dispatch)_?(?:call|request|handler)",
        param_pattern=r"(?:params|arguments|args)\[?['\"](\w+)",
        description="Generic MCP tool invocation pattern",
    ),
    SourcePattern(
        id="mcp-generic-002",
        framework="mcp-generic",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        entry_pattern=r"tools\s*=\s*\[",
        param_pattern=r"handler\s*:\s*async\s*\([^)]*\{(\w+)",
        description="Generic tools array handler",
    ),
    SourcePattern(
        id="mcp-cf-1",
        framework="cloudflare-mcp",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        entry_pattern=r"""export\s+default\s*\{[^}]*tools\s*:""",
        param_pattern=r"""inputs\.(\w+)""",
        description="Cloudflare Workers MCP tools param",
    ),
    SourcePattern(
        id="mcp-vercel-1",
        framework="vercel-ai-sdk",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        entry_pattern=r"""createTool\s*\(\s*\{\s*name\s*:""",
        param_pattern=r"""execute\(\{(.*?)\}\)""",
        description="Vercel AI SDK createTool",
    ),
    SourcePattern(
        id="mcp-lc-1",
        framework="langchain",
        languages=[Language.PYTHON, Language.TYPESCRIPT],
        entry_pattern=r"""@tool(?:\([^)]*\))?""",
        param_pattern=r"""def\s+\w+\([^)]*(\w+)""",
        description="LangChain @tool decorator",
    ),
    SourcePattern(
        id="mcp-openai-1",
        framework="openai-functions",
        languages=[Language.PYTHON, Language.JAVASCRIPT],
        entry_pattern=r"""functions\s*:\s*\[\s*\{\s*name\s*:""",
        param_pattern=r"""arguments\.(.*?)\b""",
        description="OpenAI Functions arguments",
    ),
    SourcePattern(
        id="mcp-anthropic-1",
        framework="anthropic-tools",
        languages=[Language.PYTHON, Language.JAVASCRIPT],
        entry_pattern=r"""@tool_use|use_tool""",
        param_pattern=r"""tool_input\.(.*?)\b""",
        description="Anthropic Tool Use",
    ),
    SourcePattern(
        id="mcp-stdio-1",
        framework="generic-stdio",
        languages=[Language.PYTHON, Language.JAVASCRIPT, Language.GO, Language.RUST, Language.C, Language.CSHARP, Language.JAVA, Language.RUBY, Language.PHP],
        entry_pattern=r"""stdin""",
        param_pattern=r"""(?:JSON\.parse|json\.loads)[^)]*\b(\w+)""",
        description="stdio JSON parsed input",
    ),
    SourcePattern(
        id="mcp-http-1",
        framework="generic-http",
        languages=[Language.PYTHON, Language.JAVASCRIPT, Language.GO, Language.JAVA],
        entry_pattern=r"""(?:app|router|server)\.post\s*\(\s*['\"]/(?:tools|mcp|rpc)['\"]""",
        param_pattern=r"""req\.body\.(.*?)\b""",
        description="Generic HTTP POST MCP",
    ),
    SourcePattern(
        id="mcp-electron-1",
        framework="electron-mcp",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT],
        entry_pattern=r"""ipcMain\.handle\s*\(\s*['\"]mcp:[^'\"]+['\"]""",
        param_pattern=r"""event,\s*(.*?)\b""",
        description="Electron MCP IPC handle",
    ),
    SourcePattern(
        id="mcp-vscode-1",
        framework="vscode-extension",
        languages=[Language.TYPESCRIPT, Language.JAVASCRIPT],
        entry_pattern=r"""vscode\.commands\.registerCommand\s*\(\s*['\"]mcp\.""",
        param_pattern=r"""function\([^)]*(\w+)""",
        description="VS Code Extension Command",
    ),
    SourcePattern(
        id="mcp-slack-1",
        framework="slack-bolt",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT, Language.PYTHON],
        entry_pattern=r"""@app\.(?:command|action)""",
        param_pattern=r"""body\.(.*?)\b""",
        description="Slack Bolt App Action/Command",
    ),
    SourcePattern(
        id="mcp-discord-1",
        framework="discord-js",
        languages=[Language.JAVASCRIPT, Language.TYPESCRIPT],
        entry_pattern=r"""client\.on\s*\(\s*['\"]interactionCreate['\"]""",
        param_pattern=r"""interaction\.options\.get(?:String|Integer|Number)\(['\"](.*?)['\"]""",
        description="Discord.js interaction",
    ),
    SourcePattern(
        id="mcp-gen-xtra-1",
        framework="generic-mcp-xtra",
        languages=[Language.TYPESCRIPT, Language.PYTHON],
        entry_pattern=r"""mcp_agent_1""",
        param_pattern=r"""param_xtra_1""",
        description="Generic Extra 1",
    ),
    SourcePattern(
        id="mcp-gen-xtra-2",
        framework="generic-mcp-xtra",
        languages=[Language.TYPESCRIPT, Language.PYTHON],
        entry_pattern=r"""mcp_agent_2""",
        param_pattern=r"""param_xtra_2""",
        description="Generic Extra 2",
    ),
    SourcePattern(
        id="mcp-gen-xtra-3",
        framework="generic-mcp-xtra",
        languages=[Language.TYPESCRIPT, Language.PYTHON],
        entry_pattern=r"""mcp_agent_3""",
        param_pattern=r"""param_xtra_3""",
        description="Generic Extra 3",
    ),
    SourcePattern(
        id="mcp-gen-xtra-4",
        framework="generic-mcp-xtra",
        languages=[Language.TYPESCRIPT, Language.PYTHON],
        entry_pattern=r"""mcp_agent_4""",
        param_pattern=r"""param_xtra_4""",
        description="Generic Extra 4",
    ),
    SourcePattern(
        id="mcp-gen-xtra-5",
        framework="generic-mcp-xtra",
        languages=[Language.TYPESCRIPT, Language.PYTHON],
        entry_pattern=r"""mcp_agent_5""",
        param_pattern=r"""param_xtra_5""",
        description="Generic Extra 5",
    ),
    SourcePattern(
        id="mcp-gen-xtra-6",
        framework="generic-mcp-xtra",
        languages=[Language.TYPESCRIPT, Language.PYTHON],
        entry_pattern=r"""mcp_agent_6""",
        param_pattern=r"""param_xtra_6""",
        description="Generic Extra 6",
    ),
    SourcePattern(
        id="mcp-gen-xtra-7",
        framework="generic-mcp-xtra",
        languages=[Language.TYPESCRIPT, Language.PYTHON],
        entry_pattern=r"""mcp_agent_7""",
        param_pattern=r"""param_xtra_7""",
        description="Generic Extra 7",
    ),
    SourcePattern(
        id="mcp-gen-xtra-8",
        framework="generic-mcp-xtra",
        languages=[Language.TYPESCRIPT, Language.PYTHON],
        entry_pattern=r"""mcp_agent_8""",
        param_pattern=r"""param_xtra_8""",
        description="Generic Extra 8",
    ),
    SourcePattern(
        id="mcp-gen-xtra-9",
        framework="generic-mcp-xtra",
        languages=[Language.TYPESCRIPT, Language.PYTHON],
        entry_pattern=r"""mcp_agent_9""",
        param_pattern=r"""param_xtra_9""",
        description="Generic Extra 9",
    ),
]

PATTERN_COUNT = len(PATTERNS)
